Repository SAP/fundamental-styles, pull requests merged in 2019-12, with the labels that each got.

#442 feat: input group refactoring
  docs/pages/components/form.md
  docs/pages/components/input-group.md
  docs/pages/components/localization-editor.md
  docs/pages/patterns/combobox-input.md
  docs/pages/patterns/date-picker.md
  docs/pages/patterns/multi-input.md
  docs/pages/patterns/search-input.md
  docs/pages/patterns/time-picker.md
  src/_settings.scss
  src/checkbox.scss
  src/input-group.scss
  src/input.scss
  src/mixins/_forms.scss
  src/mixins/_states.scss
  src/radio.scss
  test/resources/theme-ugly.css
  test/templates/input-group/component.njk
  test/templates/input-group/data.json
  test/templates/input-group/index.njk
  test/visual-regression-tests/reference_images/FS_input-group_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_input-group_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_input-group_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_input-group_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_input-group_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_input_2_backstop__n2_0_.png
Labels: Fiori 3 refactoring

#470 fix: alert follows fiori3
  docs/pages/components/alert.md
  src/alert.scss
  test/templates/alert/component.njk
  test/visual-regression-tests/reference_images/FS_alert_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_alert_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_alert_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_alert_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_alert_4_backstop__n4_0_.png
Labels: Fiori 3 refactoring

#491 fix: the PR fixes problem when running backstop tests on local linux
  package.json
  scripts/runDocker.js
  test/visual-regression-tests/config/backstopConfig.js
Labels: Testing Framework

#472 feat: input message to popover and add inline
  docs/pages/components/form.md
  src/form-input-message-group.scss
  src/form-item.scss
  src/form-label.scss
  src/form-message.scss
  src/fundamental-styles.scss
  src/input.scss
  test/templates/form-item/index.njk
  test/templates/form-message/index.njk
  test/visual-regression-tests/reference_images/FS_form-item_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_form-item_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_form-label_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_form-label_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_form-message_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_form-message_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_form-message_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_form-message_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_input_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_input_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_input_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_input_3_backstop__n3_0_.png
Labels: Fiori 3 refactoring

#451 feat: input group for checkbox/radio inline
  docs/pages/components/form.md
  src/form-group.scss
  src/form-item.scss
  test/resources/layout.css
  test/templates/form-group/index.njk
  test/templates/form-item/index.njk
  test/visual-regression-tests/reference_images/FS_form-group_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_form-group_3_backstop__n3_0_.png
Labels: Fiori 3 refactoring

#539 fix: input-group-pickers
  src/input-group.scss
Labels: 0.4.0

#537 fix: Can write inside disabled input
  docs/pages/components/form.md
Labels: 0.4.0

#545 fix: Number input increment/decrement not working on IE11
  docs/js/customscripts.js
  docs/pages/components/input-group.md
Labels: 0.4.0, IE11

#540 fix: Add focus state to input group
  docs/pages/components/input-group.md
  src/input-group.scss
  test/visual-regression-tests/reference_images/FS_input-group_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_input-group_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_input-group_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_input-group_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_input-group_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_input-group_5_backstop__n5_0_.png
Labels: 0.4.0

#542 fix: Remove flex property from input-message-group IE11
  src/form-input-message-group.scss
Labels: 0.4.0, IE11

#543 fix: Add hardcoded RGBA calue for readonly on forms
  src/mixins/_forms.scss
Labels: 0.4.0, IE11

#544 fix: Remove IE11 Dropdown default icon
  src/form-select.scss
Labels: 0.4.0, IE11

#548 docs: remove default form message
  docs/pages/components/form.md
  test/resources/theme-ugly.css
  test/templates/form-message/index.njk
  test/visual-regression-tests/reference_images/FS_form-message_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_form-message_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_form-message_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_form-message_3_backstop__n3_0_.png
Labels: 0.4.0

#546 feat: checkbox and radio pseudo elements
  docs/js/customscripts.js
  docs/pages/components/form.md
  src/checkbox.scss
  src/fieldset.scss
  src/form-label.scss
  src/mixins/_forms.scss
  src/radio.scss
  src/textarea.scss
  test/templates/checkbox/component.njk
  test/templates/form-label/index.njk
  test/templates/radio/component.njk
  test/visual-regression-tests/reference_images/FS_checkbox_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_checkbox_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_checkbox_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_checkbox_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_checkbox_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_checkbox_5_backstop__n5_0_.png
  test/visual-regression-tests/reference_images/FS_form-item_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_form-label_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_form-label_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_form-label_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_form-label_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_radio_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_radio_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_radio_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_radio_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_radio_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_radio_5_backstop__n5_0_.png
  test/visual-regression-tests/reference_images/FS_textarea_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_textarea_4_backstop__n4_0_.png
Labels: 0.4.0

#553 fix: update RTL for radio and checkboxes focus and update some tests
  docs/pages/components/form.md
  docs/pages/components/input-group.md
  src/mixins/_forms.scss
Labels: 0.4.0, Bug
