Repository SAP/fundamental-styles, pull requests merged in 2019-10, with the labels that each got.

#352 docs: remove SAP from the library name
  docs/_config.yml
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/_includes/topnav.html
  docs/index.html
  docs/pages/getting-started.md
  docs/pages/resources/fundamentals-libraries.md
  docs/pages/resources/index.md
Labels: Doc website

#364 feat: menu hover
  docs/pages/components/menu.md
  src/menu.scss
  test/templates/menu/component.njk
  test/templates/side-nav/index.njk
Labels: Bug

#373 feat: product switch
  docs/_data/components.yml
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/images/component-visual/notification.png
  docs/images/component-visual/product-switch.png
  docs/pages/components/product-switch.md
  docs/pages/components/shellbar.md
  src/_drag-and-drop.scss
  src/fundamental-styles.scss
  src/mixins/_mixins.scss
  src/product-switch.scss
  src/shellbar.scss
  test/resources/theme-ugly.css
  test/templates/index.njk
  test/templates/product-switch/index.njk
  test/visual-regression-tests/reference_images/FS_product-switch_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_product-switch_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_product-switch_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_shellbar_6_backstop__n6_0_.png
Labels: Enhancement

#379 fix: refactored link mixin using theme parameters
  docs/pages/components/link.md
  src/mixins/_mixins.scss
  test/visual-regression-tests/reference_images/FS_link_0_backstop_0_.png
Labels: Enhancement

#396 fix: update the focus and body border-radius
  docs/pages/components/product-switch.md
  src/product-switch.scss
  test/visual-regression-tests/reference_images/FS_product-switch_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_product-switch_1_backstop__n1_0_.png
Labels: Enhancement

#395 fix: updated the size of the icon used in Alert close btn
  src/alert.scss
  test/visual-regression-tests/reference_images/FS_alert_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_alert_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_alert_4_backstop__n4_0_.png
Labels: Enhancement

#401 fix: migrate breadcrums to use theming parameters
  src/breadcrumb.scss
  src/mixins/_mixins.scss
  test/visual-regression-tests/reference_images/FS_breadcrumb_0_backstop_0_.png
Labels: Enhancement

#387 fix: tile theme parameter refactoring
  src/mixins/_mixins.scss
  src/tile.scss
Labels: Enhancement
