Repository SAP/fundamental-styles, pull requests merged in 2019-11, with the labels that each got.

#412 fix: implement busy indicator
  docs/_data/components.yml
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/images/component-visual/busy-indicator.png
  docs/pages/components/busy-indicator.md
  docs/pages/patterns/index.md
  src/busy-indicator.scss
  src/fundamental-styles.scss
  test/resources/animation.css
  test/resources/controls.js
  test/resources/theme-ugly.css
  test/templates/busy-indicator/index.njk
  test/templates/index.njk
  test/templates/layout.njk
  test/visual-regression-tests/reference_images/FS_busy-indicator_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_busy-indicator_1_backstop__n1_0_.png
Labels: Enhancement

#420 fix: migrate buttons radius over theming parameters
  src/button-group.scss
  src/button-split.scss
  src/button.scss
  src/mixins/_mixins.scss
Labels: Enhancement

#421 fix: migrate counter over theming parameters
  src/counter.scss
  test/visual-regression-tests/reference_images/FS_counter_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_counter_1_backstop__n1_0_.png
Labels: Enhancement

#405 fix: product switch trunc
  docs/pages/components/product-switch.md
  src/product-switch.scss
  test/templates/product-switch/index.njk
  test/visual-regression-tests/reference_images/FS_product-switch_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_product-switch_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_product-switch_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_product-switch_3_backstop__n3_0_.png
Labels: Enhancement

#416 fix: menu width issue
  docs/_sass/_docs-display-component.scss
  src/menu.scss
  test/visual-regression-tests/reference_images/FS_menu_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_menu_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_menu_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_menu_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_menu_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_menu_5_backstop__n5_0_.png
  test/visual-regression-tests/reference_images/FS_menu_6_backstop__n6_0_.png
Labels: Bug

#422 fix: fix the width issue of time after refactoring forms
  src/time.scss
Labels: Bug

#446 docs: remove third level in the nested list/sidenav
  docs/pages/components/side-navigation.md
Labels: Doc website

#429 docs: remove SCSS from the landing page, update library name
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  config/postcss.config.js
  docs/_config.yml
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/_data/strings.yml
  docs/_includes/display-component.html
  docs/_includes/topnav.html
  docs/_layouts/full-width-page.html
  docs/_sass/_docs-display-component.scss
  docs/_sass/_docs-main-content.scss
  docs/images/component-visual/date-picker.png
  docs/images/component-visual/time-picker.png
  docs/index.html
  docs/pages/foundation/getting-started-designers.html
  docs/pages/foundation/index.md
  docs/pages/getting-started.md
  docs/pages/layouts/index.md
  docs/pages/patterns/index.md
  docs/pages/patterns/multi-input.md
  docs/pages/resources/design-system-utilities.md
  docs/pages/resources/fundamentals-libraries.md
  docs/pages/resources/index.md
  package.json
  src/_settings.scss
  test/templates/pages/layouts/starter.njk
Labels: Doc website

#464 fix: fixed breadcrumb spacing
  docs/pages/components/breadcrumb.md
  src/breadcrumb.scss
  test/templates/breadcrumb/component.njk
  test/visual-regression-tests/reference_images/FS_breadcrumb_0_backstop_0_.png
Labels: Fiori 3 refactoring

#463 docs: document some differences between Fundamental Library Styles and Fundamental
  README.md
Labels: Doc website
