Repository SAP/fundamental-styles, pull requests merged in 2020-10, with the labels that each got.

#1678 feat: Object list item Component styles
  src/_listNavigation.scss
  src/_listSelection.scss
  src/object-list.scss
  stories/object-list/__snapshots__/object-list.stories.storyshot
  stories/object-list/object-list.stories.js
  stories/object-list/object-list.visual.js
Labels: 1p-steel-thread, Fiori 3 New Component, ariba

#1746 docs: updated action bar documentation
  stories/action-bar/__snapshots__/action-bar.stories.storyshot
  stories/action-bar/action-bar.stories.js
Labels: Doc website

#1736 feat: add full class modifier
  src/layout-grid.scss
  stories/layout-grid/__snapshots__/layout-grid.stories.storyshot
  stories/layout-grid/layout-grid.stories.js
Labels: Enhancement

#1708 docs: updated feed input documentation
  stories/feed-input/__snapshots__/feed-input.stories.storyshot
  stories/feed-input/feed-input.stories.js
Labels: Doc website

#1714 fix: add fix for Notifications examples markup and for the max-width of the footer content
  src/notification.scss
  stories/notification/__snapshots__/notification.stories.storyshot
  stories/notification/notification.stories.js
Labels: Bug

#1756 fix: remove deprecated localization editor
  src/fundamental-styles.scss
  src/localization-editor.scss
  stories/localization-editor/__snapshots__/localization-editor.stories.storyshot
  stories/localization-editor/localization-editor.stories.js
  stories/localization-editor/localization-editor.visual.js
Labels: 0.13.0

#1763 docs: add additional selector for hcm radio color
  .storybook/static/windows-hcm-1.css
  .storybook/static/windows-hcm-2.css
  .storybook/static/windows-hcm-black.css
  .storybook/static/windows-hcm-white.css
Labels: A11y

#1745 docs: updated card documentation
  stories/card/__snapshots__/card.stories.storyshot
  stories/card/card.stories.js
Labels: Doc website

#1749 feat: introduce Dynamic Side Content
  src/dynamic-side-content.scss
  src/fundamental-styles.scss
  stories/dynamic-side-content/__snapshots__/dynamic-side-content.stories.storyshot
  stories/dynamic-side-content/dynamic-side-content.stories.js
Labels: Fiori 3 New Component

#1785 chore: fix storybook in IE
  .storybook/preview.js
  package-lock.json
  package.json
Labels: Bug, IE11

#1598 feat: introduce new component Dynamic Page Layout
  .storybook/custom/custom.scss
  src/dynamic-page.scss
  src/fundamental-styles.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
  stories/dynamic-page/__snapshots__/dynamic-page.stories.storyshot
  stories/dynamic-page/dynamic-page.stories.js
Labels: 1p, 1p-landing-page, 1p-product-details-page, 1p-search-results-page, 1p-steel-thread, ariba, gb, sourcing

#1791 docs: updated byline list documentation
  stories/list/byline/__snapshots__/byline-list.stories.storyshot
  stories/list/byline/byline-list.stories.js
Labels: Doc website, storybook

#1780 docs: updated standard list documentation
  stories/list/standard/__snapshots__/standard-list.stories.storyshot
  stories/list/standard/standard-list.stories.js
Labels: Doc website

#1793 docs: add story dependencies
  stories/avatar/__snapshots__/avatar.stories.storyshot
  stories/avatar/avatar.stories.js
  stories/card/__snapshots__/card.stories.storyshot
  stories/card/card.stories.js
  stories/carousel/__snapshots__/carousel.stories.storyshot
  stories/carousel/carousel.stories.js
  stories/combobox-input/combobox-input.stories.js
  stories/datepicker/datepicker.stories.js
  stories/feed-input/feed-input.stories.js
  stories/info-label/info-label.stories.js
  stories/input-group/input-group.stories.js
  stories/input/input.stories.js
  stories/multi-input/multi-input.stories.js
  stories/notification/__snapshots__/notification.stories.storyshot
  stories/notification/notification.stories.js
  stories/object-list/__snapshots__/object-list.stories.storyshot
  stories/object-list/object-list.stories.js
  stories/popover/__snapshots__/popover.stories.storyshot
  stories/popover/popover.stories.js
  stories/product-switch/product-switch.stories.js
  stories/select/select.stories.js
  stories/shellbar/shellbar.stories.js
  stories/specific-tile/__snapshots__/specific-tile.stories.storyshot
  stories/specific-tile/specific-tile.stories.js
  stories/table/table.stories.js
  stories/tabs/tabs.stories.js
  stories/time/time.stories.js
Labels: Doc website, storybook

#1789 fix: fiori 3 high contrast mode contrast ratios
  src/avatar.scss
  src/checkbox.scss
  src/radio.scss
  src/tabs.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
Labels: A11y, Fiori 3 High Contrast, WCAG AA

#1799 docs: updated message toast documentation
  stories/message-toast/__snapshots__/message-toast.stories.storyshot
  stories/message-toast/message-toast.stories.js
Labels: Doc website

#1797 docs: updated message strip documentation
  stories/message-strip/__snapshots__/message-strip.stories.storyshot
  stories/message-strip/message-strip.stories.js
Labels: Doc website

#1807 docs: updated byline list documentation
  stories/list/byline/__snapshots__/byline-list.stories.storyshot
  stories/list/byline/byline-list.stories.js
Labels: Doc website

#1806 docs: updated message page documentation
  stories/message-page/__snapshots__/message-page.stories.storyshot
  stories/message-page/message-page.stories.js
Labels: Doc website

#1761 feat: introduce Slider
  .storybook/custom/custom.scss
  src/slider.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
  stories/slider/__snapshots__/slider.stories.storyshot
  stories/slider/slider.stories.js
Labels: Fiori 3 New Component

#1812 fix: menu styles and improved accessibility
  stories/menu/__snapshots__/menu.stories.storyshot
  stories/menu/menu.stories.js
Labels: 0.13.0, Defect Hunting

#1811 fix: Calendar navigation button, add missing imports
  src/calendar.scss
  stories/calendar/calendar.stories.js
Labels: 0.13.0, Defect Hunting, denoland

#1814 fix: wcag aaa text color contrast
  src/_listBase.scss
  src/button.scss
  src/calendar.scss
  src/input-group.scss
  src/input.scss
  src/menu.scss
  src/popover.scss
  src/product-switch.scss
  src/select.scss
  src/side-nav.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
  src/time.scss
  src/token.scss
Labels: A11y, Fiori 3 High Contrast, Theming, WCAG AAA

#1809 docs: bring popover to action bar
  stories/action-bar/__snapshots__/action-bar.stories.storyshot
  stories/action-bar/action-bar.stories.js
Labels: 0.13.0, Defect Hunting, denoland

#1810 docs: bring different image into examples
  .storybook/static/assets/images/avatars/1.svg
  .storybook/static/assets/images/avatars/2.svg
  .storybook/static/assets/images/avatars/3.svg
  .storybook/static/assets/images/avatars/4.svg
  .storybook/static/assets/images/avatars/5.svg
  .storybook/static/assets/images/backgrounds/Godafoss_waterfall_in_northern_Iceland.jpg
  .storybook/static/assets/images/backgrounds/city.jpg
  .storybook/static/assets/images/backgrounds/windmills.jpg
  .storybook/static/assets/images/products/fitbit.png
  stories/avatar/__snapshots__/avatar.stories.storyshot
  stories/avatar/avatar.stories.js
  stories/bar/__snapshots__/bar.stories.storyshot
  stories/bar/bar.stories.js
  stories/card/__snapshots__/card.stories.storyshot
  stories/card/card.stories.js
  stories/carousel/__snapshots__/carousel.stories.storyshot
  stories/carousel/carousel.stories.js
  stories/feed-input/feed-input.stories.js
  stories/list/byline/__snapshots__/byline-list.stories.storyshot
  stories/list/byline/byline-list.stories.js
  stories/notification/__snapshots__/notification.stories.storyshot
  stories/notification/notification.stories.js
  stories/object-list/__snapshots__/object-list.stories.storyshot
  stories/object-list/object-list.stories.js
  stories/popover/__snapshots__/popover.stories.storyshot
  stories/popover/popover.stories.js
  stories/shellbar/__snapshots__/shellbar.stories.storyshot
  stories/shellbar/shellbar.stories.js
  stories/specific-tile/__snapshots__/specific-tile.stories.storyshot
  stories/specific-tile/specific-tile.stories.js
  stories/wizard/__snapshots__/wizard.stories.storyshot
  stories/wizard/wizard.stories.js
Labels: 0.13.0, Defect Hunting, denoland

#1815 fix: Remove focus on pressed button
  src/button.scss
Labels: 0.13.0, Defect Hunting, denoland

#1808 fix: popover accessibility improvements + fix popover and product switch snapshots
  .storybook/custom/custom.scss
  stories/popover/__snapshots__/popover.stories.storyshot
  stories/popover/popover.stories.js
  stories/product-switch/__snapshots__/product-switch.stories.storyshot
  stories/product-switch/product-switch.stories.js
Labels: 0.13.0, Defect Hunting, denoland

#1825 fix: high contrast black side navigation nested-list/icon text shadow
  src/_nested-list.scss
  src/side-nav.scss
Labels: A11y, Fiori 3 High Contrast, Theming, WCAG AAA

#1834 fix: Breadcrumb accessibility improvements + icon as <i> element
  .storybook/preview-head.html
  .storybook/static/preview-head.js
  src/breadcrumb.scss
  stories/breadcrumb/__snapshots__/breadcrumb.stories.storyshot
  stories/breadcrumb/breadcrumb.stories.js
Labels: icons

#1832 fix: Add RTL support for layout grid column offset
  src/layout-grid.scss
Labels: RTL

#1831 fix: multi-input accessibility + add iframe height to some examples
  stories/context-menu/__snapshots__/context-menu.stories.storyshot
  stories/context-menu/context-menu.stories.js
  stories/multi-input/__snapshots__/multi-input.stories.storyshot
  stories/multi-input/multi-input.stories.js
  stories/time-picker/__snapshots__/time-picker.stories.storyshot
  stories/time-picker/time-picker.stories.js
Labels: Defect Hunting, Doc website

#1827 docs: show storybook examples with themed background
  .storybook/custom/components/DocsPage.js
  .storybook/custom/components/Header.js
  .storybook/custom/custom.scss
  .storybook/custom/themeProvider.js
  .storybook/preview.js
Labels: Doc website, storybook
