Repository SAP/fundamental-styles, pull requests merged in 2020-04, with the labels that each got.

#834 fix: Show readonly mode popover on multi input
  src/input-group.scss
  src/tokenizer.scss
Labels: 0.8.1

#829 fix: menu border radius, fix IE11 issue
  docs/pages/components/action-bar.md
  docs/pages/components/table.md
  src/_mixins.scss
  src/menu.scss
  src/mixins/_popover.scss
  src/popover.scss
Labels: 0.8.1

#827 fix: update menu examples; add rounded corners for menu in popover
  docs/_includes/demo-page-components/shell-header.html
  docs/_includes/demo-page-components/table-page-content.html
  docs/_includes/topnav.html
  docs/js/customscripts.js
  docs/pages/components/action-bar.md
  docs/pages/components/button.md
  docs/pages/components/popover.md
  docs/pages/components/shellbar.md
  docs/pages/components/table.md
  docs/pages/components/tile.md
  docs/pages/components/tree.md
  docs/pages/patterns/contextual-menu.md
  docs/pages/patterns/multi-input.md
  docs/pages/patterns/search-input.md
  src/_mixins.scss
  src/menu.scss
  src/mixins/_popover.scss
  src/popover.scss
Labels: 0.8.1, Bug

#835 fix: update menu examples
  docs/_sass/_docs-top-nav.scss
  docs/pages/patterns/search-input.md
  src/menu.scss
Labels: 0.8.1

#806 docs: responsive issue for both component pages and grid pages
  docs/_includes/head_print.html
  docs/_sass/_docs-component-list.scss
  docs/_sass/_docs-general.scss
  docs/_sass/_docs-main-content.scss
  docs/_sass/_docs-side-nav.scss
  docs/_sass/_docs-top-nav.scss
  docs/_sass/_include-media.scss
  docs/_sass/_landingPage.scss
Labels: Doc website

#826 fix: introduce new Message Toast component
  docs/_data/components.yml
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/images/component-visual/message-toast.png
  docs/pages/components/message-toast.md
  src/_dialog-placeholders.scss
  src/dialog.scss
  src/fundamental-styles.scss
  src/message-box.scss
  src/message-toast.scss
  test/templates/index.njk
  test/templates/message-toast/index.njk
  test/visual-regression-tests/reference_images/FS_dialog_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_dialog_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_dialog_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_dialog_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_dialog_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_dialog_5_backstop__n5_0_.png
  test/visual-regression-tests/reference_images/FS_dialog_6_backstop__n6_0_.png
  test/visual-regression-tests/reference_images/FS_dialog_7_backstop__n7_0_.png
  test/visual-regression-tests/reference_images/FS_message-box_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_message-box_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_message-box_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_message-toast_0_backstop_0_.png
Labels: 0.9.0, Fiori 3 New Component

#864 chore: check if tag starts with 'v' not if contains v
  ci-scripts/publish.sh
Labels: tooling

#882 chore: bump theming version
  package-lock.json
  package.json
Labels: Dependencies, Theming

#861 fix: add RTL support for Tokenizer
  src/tokenizer.scss
Labels: Bug

#863 fix: add Byline and Selection features to List component
  docs/pages/components/list.md
  src/checkbox.scss
  src/list.scss
  src/mixins/_forms.scss
  src/radio.scss
  test/resources/layout.css
  test/templates/list/component.njk
  test/templates/list/index.njk
  test/visual-regression-tests/reference_images/FS_list_10_backstop__n10_0_.png
  test/visual-regression-tests/reference_images/FS_list_11_backstop__n11_0_.png
  test/visual-regression-tests/reference_images/FS_list_12_backstop__n12_0_.png
  test/visual-regression-tests/reference_images/FS_list_13_backstop__n13_0_.png
  test/visual-regression-tests/reference_images/FS_list_14_backstop__n14_0_.png
  test/visual-regression-tests/reference_images/FS_list_15_backstop__n15_0_.png
  test/visual-regression-tests/reference_images/FS_list_16_backstop__n16_0_.png
  test/visual-regression-tests/reference_images/FS_list_17_backstop__n17_0_.png
  test/visual-regression-tests/reference_images/FS_list_18_backstop__n18_0_.png
  test/visual-regression-tests/reference_images/FS_list_19_backstop__n19_0_.png
  test/visual-regression-tests/reference_images/FS_list_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_list_5_backstop__n5_0_.png
  test/visual-regression-tests/reference_images/FS_list_6_backstop__n6_0_.png
  test/visual-regression-tests/reference_images/FS_list_7_backstop__n7_0_.png
  test/visual-regression-tests/reference_images/FS_list_8_backstop__n8_0_.png
  test/visual-regression-tests/reference_images/FS_list_9_backstop__n9_0_.png
Labels: Enhancement, Fiori 3 New Feature

#815 fix: add subtle link, improve the tests
  docs/pages/components/link.md
  src/mixins/_mixins.scss
  test/resources/theme-ugly.css
  test/templates/link/index.njk
  test/visual-regression-tests/reference_images/FS_link_0_backstop_0_.png
Labels: 0.9.0, design review changes

#884 fix: Add Rtl support for form group
  src/form-group.scss
  test/visual-regression-tests/reference_images/FS_form-group_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_form-group_3_backstop__n3_0_.png
Labels: 0.9.0

#885 docs: Add aria attributes to Dialog examples
  docs/pages/components/dialog.md
Labels: Doc website

#855 fix: Introduce menu shortcut | Improve A11y | Fix Menu issues
  docs/pages/components/menu.md
  src/menu.scss
  test/templates/menu/component.njk
  test/templates/menu/index.njk
  test/visual-regression-tests/reference_images/FS_menu_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_menu_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_menu_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_menu_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_menu_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_menu_5_backstop__n5_0_.png
Labels: 0.9.0

#825 feat: side navigation expand icon
  docs/_sass/_docs-general.scss
  docs/pages/components/side-navigation.md
  src/_nested-list.scss
  src/side-nav.scss
  test/templates/_nested-list/index.njk
  test/visual-regression-tests/reference_images/FS__nested-list_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS__nested-list_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS__nested-list_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS__nested-list_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS__nested-list_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS__nested-list_5_backstop__n5_0_.png
  test/visual-regression-tests/reference_images/FS__nested-list_6_backstop__n6_0_.png
Labels: 0.9.0, design review changes

#877 fix: Apply fixes to Side nav's rtl
  src/side-nav.scss
  test/visual-regression-tests/reference_images/FS_side-nav_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_side-nav_1_backstop__n1_0_.png
Labels: 0.9.0

#801 feat: Adapt time to fiori3
  docs/_sass/_docs-time.scss
  docs/css/docs-all.scss
  docs/pages/components/time.md
  docs/pages/patterns/time-picker.md
  src/mixins/_mixins.scss
  src/time.scss
  src/tokenizer.scss
  test/templates/time/component.njk
  test/templates/time/data.json
  test/templates/time/index.njk
  test/visual-regression-tests/reference_images/FS_time_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_time_10_backstop__n10_0_.png
  test/visual-regression-tests/reference_images/FS_time_11_backstop__n11_0_.png
  test/visual-regression-tests/reference_images/FS_time_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_time_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_time_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_time_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_time_5_backstop__n5_0_.png
  test/visual-regression-tests/reference_images/FS_time_6_backstop__n6_0_.png
  test/visual-regression-tests/reference_images/FS_time_7_backstop__n7_0_.png
  test/visual-regression-tests/reference_images/FS_time_8_backstop__n8_0_.png
  test/visual-regression-tests/reference_images/FS_time_9_backstop__n9_0_.png
Labels: 0.9.0

#886 fix: IE11 popover with bar component
  src/bar.scss
Labels: 0.9.0, IE11

#888 docs: reduce some button examples(icon and text)
  docs/pages/components/button.md
Labels: 0.9.0, Doc website

#892 docs: Add deprecated note for native select
  docs/pages/components/form.md
Labels: 0.9.0

#850 docs: fix the doc side navigation vertical scrolling on tablet; update the components grid
  docs/_sass/_docs-component-list.scss
  docs/_sass/_docs-general.scss
  docs/_sass/_docs-headers.scss
  docs/_sass/_docs-home.scss
  docs/_sass/_docs-main-content.scss
  docs/_sass/_docs-search-box.scss
  docs/_sass/_docs-side-nav.scss
  docs/_sass/_docs-top-nav.scss
  docs/_sass/_landingPage.scss
  docs/images/component-visual/Rectangle 7.png
  docs/images/component-visual/action-bar.png
  docs/images/component-visual/bar.png
  docs/images/component-visual/breadcrumb.png
  docs/images/component-visual/busy-indicator.png
  docs/images/component-visual/buton.png
  docs/images/component-visual/button-group.png
  docs/images/component-visual/button.png
  docs/images/component-visual/combobox-input.png
  docs/images/component-visual/contextual-menu.png
  docs/images/component-visual/date-picker.png
  docs/images/component-visual/dialog.png
  docs/images/component-visual/dropdown.png
  docs/images/component-visual/form.png
  docs/images/component-visual/icon.png
  docs/images/component-visual/icons.png
  docs/images/component-visual/identifier.png
  docs/images/component-visual/image.png
  docs/images/component-visual/info-label.png
  docs/images/component-visual/inline-help.png
  docs/images/component-visual/input-group.png
  docs/images/component-visual/link.png
  docs/images/component-visual/list-group.png
  docs/images/component-visual/list.png
  docs/images/component-visual/loading-spinner.png
  docs/images/component-visual/localization-editor.png
  docs/images/component-visual/message-box.png
  docs/images/component-visual/message-strip.png
  docs/images/component-visual/multi-input.png
  docs/images/component-visual/notification.png
  docs/images/component-visual/object-status.png
  docs/images/component-visual/pagination.png
  docs/images/component-visual/product-switch.png
  docs/images/component-visual/search-input.png
  docs/images/component-visual/select.png
  docs/images/component-visual/shellbar.png
  docs/images/component-visual/side-navigation.png
  docs/images/component-visual/status-indicators.png
  docs/images/component-visual/step-input.png
  docs/images/component-visual/switch.png
  docs/images/component-visual/table.png
  docs/images/component-visual/tabs.png
  docs/images/component-visual/tile.png
  docs/images/component-visual/time-picker.png
  docs/images/component-visual/tree.png
  docs/images/land-page-assets/newsletterIcon.png
  docs/index.html
  docs/pages/components/index.html
  docs/pages/patterns/index.md
Labels: Doc website

#836 fix: update identifier to avatar
  docs/_data/components.yml
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/_sass/_docs-component-list.scss
  docs/images/component-visual/avatar.png
  docs/images/component-visual/identifier.png
  docs/pages/components/avatar.md
  docs/pages/components/identifier.md
  docs/pages/components/notification.md
  docs/pages/components/popover.md
  docs/pages/components/shellbar.md
  docs/pages/components/tile.md
  src/avatar.scss
  src/fundamental-styles.scss
  src/shellbar.scss
  test/resources/layout.css
  test/templates/avatar/component.njk
  test/templates/avatar/data.json
  test/templates/avatar/index.njk
  test/templates/identifier/data.json
  test/templates/index.njk
  test/templates/pages/tiles.njk
  test/templates/shellbar/component.njk
  test/visual-regression-tests/reference_images/FS_avatar_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_avatar_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_avatar_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_avatar_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_avatar_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_avatar_5_backstop__n5_0_.png
Labels: Fiori 3 New Feature

#902 chore: delete unused code, add size testing and improve travis build times
  .travis.yml
  config/bundlesize.json
  package-lock.json
  package.json
  src/_container.scss
  src/_nested-list.scss
  src/_product-switcher.scss
  src/action-bar.scss
  src/alert.scss
  src/bar.scss
  src/breadcrumb.scss
  src/busy-indicator.scss
  src/button-split.scss
  src/button.scss
  src/calendar.scss
  src/checkbox.scss
  src/counter.scss
  src/dialog.scss
  src/form-input-message-group.scss
  src/form-item.scss
  src/form-label.scss
  src/functions/_space.scss
  src/image.scss
  src/info-label.scss
  src/input-group.scss
  src/input.scss
  src/layout-grid.scss
  src/link.scss
  src/list.scss
  src/menu.scss
  src/message-box.scss
  src/message-strip.scss
  src/message-toast.scss
  src/mixins/_breakpoints.scss
  src/mixins/_mixins.scss
  src/mixins/_states.scss
  src/mixins/button/_button-helper.scss
  src/notification.scss
  src/object-status.scss
  src/page.scss
  src/popover.scss
  src/product-switch.scss
  src/radio.scss
  src/segmented-button.scss
  src/select.scss
  src/shellbar.scss
  src/side-nav.scss
  src/switch.scss
  src/tabs.scss
  src/textarea.scss
  src/time.scss
  src/token.scss
  src/tokenizer.scss
Labels: 0.9.0

#887 fix: introduce Navigation Indication functionality to List component
  docs/pages/components/list.md
  src/list.scss
  test/resources/layout.css
  test/templates/list/component.njk
  test/templates/list/data.json
  test/templates/list/index.njk
  test/visual-regression-tests/reference_images/FS_list_10_backstop__n10_0_.png
  test/visual-regression-tests/reference_images/FS_list_11_backstop__n11_0_.png
  test/visual-regression-tests/reference_images/FS_list_12_backstop__n12_0_.png
  test/visual-regression-tests/reference_images/FS_list_13_backstop__n13_0_.png
  test/visual-regression-tests/reference_images/FS_list_14_backstop__n14_0_.png
  test/visual-regression-tests/reference_images/FS_list_15_backstop__n15_0_.png
  test/visual-regression-tests/reference_images/FS_list_16_backstop__n16_0_.png
  test/visual-regression-tests/reference_images/FS_list_17_backstop__n17_0_.png
  test/visual-regression-tests/reference_images/FS_list_18_backstop__n18_0_.png
  test/visual-regression-tests/reference_images/FS_list_19_backstop__n19_0_.png
  test/visual-regression-tests/reference_images/FS_list_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_list_5_backstop__n5_0_.png
  test/visual-regression-tests/reference_images/FS_list_6_backstop__n6_0_.png
  test/visual-regression-tests/reference_images/FS_list_7_backstop__n7_0_.png
  test/visual-regression-tests/reference_images/FS_list_8_backstop__n8_0_.png
Labels: Enhancement, Fiori 3 New Feature

#911 fix: remove fading from drag and drop
  src/_drag-and-drop.scss
  src/product-switch.scss
Labels: Fiori 3 refactoring, Theming

#909 fix: add opacity parameter to disabled switch
  src/switch.scss
Labels: 0.9.0, Fiori 3 refactoring

#908 fix: button disabled opacity to use theming parameter
  src/button.scss
Labels: 0.9.0, Fiori 3 refactoring

#921 chore: expand stylelint to all files
  .stylelintignore
  docs/_sass/_docs-colors.scss
  docs/_sass/_docs-component-list.scss
  docs/_sass/_docs-display-component.scss
  docs/_sass/_docs-display-responsive-component.scss
  docs/_sass/_docs-footer.scss
  docs/_sass/_docs-functions.scss
  docs/_sass/_docs-general.scss
  docs/_sass/_docs-headers.scss
  docs/_sass/_docs-home.scss
  docs/_sass/_docs-icons.scss
  docs/_sass/_docs-main-content.scss
  docs/_sass/_docs-right-nav.scss
  docs/_sass/_docs-search-box.scss
  docs/_sass/_docs-settings.scss
  docs/_sass/_docs-side-nav.scss
  docs/_sass/_docs-spacing.scss
  docs/_sass/_docs-top-nav.scss
  docs/_sass/_docs-type.scss
  docs/_sass/_docs-utils.scss
  docs/_sass/_include-media.scss
  docs/_sass/_landingPage.scss
  docs/css/printstyles.css
  docs/css/syntax.css
  package.json
Labels: tooling

#906 chore: update readme
  README.md
Labels: Doc website

#919 chore: upgrade standard version
  package-lock.json
  package.json
Labels: tooling
