Repository SAP/fundamental-styles, pull requests merged in 2020-12, with the labels that each got.

#1930 fix: center the content of Button by default
  src/button.scss
Labels: Defect Hunting, button

#1929 fix: add fix for missing space between Menu Button text and expand arrow
  src/button.scss
Labels: Defect Hunting

#1926 fix: add fix for missing icons in RTL mode for Message Strip
  src/message-strip.scss
Labels: 0.22.0, Defect Hunting

#1925 fix: date time picker segmented button
  stories/datepicker/__snapshots__/datepicker.stories.storyshot
  stories/datepicker/datepicker.stories.js
Labels: 0.22.0, Defect Hunting

#1918 docs: update Slider documentation
  stories/slider/__snapshots__/slider.stories.storyshot
  stories/slider/slider.stories.js
Labels: Doc website

#1915 docs: update Side Navigation documentation
  stories/side-navigation/__snapshots__/side-navigation.stories.storyshot
  stories/side-navigation/side-navigation.stories.js
Labels: Doc website

#1937 fix: remove padding from button in Flexible Column Layout
  src/flexible-column-layout.scss
Labels: Defect Hunting

#1934 docs: add height for the iframe in Grid List examples
  stories/list-grid/__snapshots__/list-grid.stories.storyshot
  stories/list-grid/list-grid.stories.js
Labels: Defect Hunting, Doc website

#1933 fix: add fixes for buttons not changing position in RTL in IE11 and cut badges in RTL
  src/badge.scss
  src/tile.scss
Labels: Defect Hunting

#1928 fix: (Core) add fix for Carousel button position on click
  src/carousel.scss
Labels: Defect Hunting

#1938 docs: update ShellBar documentation
  stories/shellbar/shellbar.stories.js
Labels: Doc website

#1935 docs: update Step Input documentation
  stories/step-input/__snapshots__/step-input.stories.storyshot
  stories/step-input/step-input.stories.js
Labels: Doc website

#1940 fix: add fix for overflowing card numeric content
  src/card.scss
  src/numeric-content.scss
Labels: Bug, Defect Hunting

#1942 fix: form controls in Table
  src/popover.scss
  stories/table/__snapshots__/table.stories.storyshot
  stories/table/table.stories.js
Labels: Bug, Defect Hunting

#1945 fix: add missing icons to semantic Message Box
  .storybook/custom/custom.scss
  src/message-box.scss
  stories/message-box/__snapshots__/message-box.stories.storyshot
  stories/message-box/message-box.stories.js
Labels: denoland

#1951 fix: change min width when a user image will disappear Feed Input
  src/feed-input.scss
Labels: Bug, Defect Hunting

#1952 fix: Shellbar menu button focus outline
  src/shellbar.scss
Labels: Bug

#1939 fix: add fix for missing spacing in Multi Combobox secondary data in IE11
  src/_listDropdown.scss
Labels: Defect Hunting

#1962 fix: add fix for Rating indicator parse error
  src/rating-indicator.scss
Labels: 0.13.0

#1955 chore: bump theming-base-content to version 11.1.24
  package-lock.json
  package.json
Labels: Theming

#1954 fix: checkbox focus with margin
  src/checkbox.scss
Labels: winter 2020

#1956 feat: add Toggle Button to Buttons
  src/button.scss
  src/mixins/button/_attention.scss
  src/mixins/button/_button-helper.scss
  src/mixins/button/_button-transparent.scss
  src/mixins/button/_emphasized.scss
  src/mixins/button/_ghost.scss
  src/mixins/button/_negative.scss
  src/mixins/button/_positive.scss
  src/mixins/button/_standard.scss
  stories/button/__snapshots__/button.stories.storyshot
  stories/button/button.stories.js
Labels: Enhancement, button, denoland

#1965 docs: update dead link on README.md
  README.md
Labels: Doc website

#1964 fix: add fix for Slider labels not being centered in IE11
  src/slider.scss
Labels: Defect Hunting, IE11

#1966 fix: inherit font weight on button text
  src/button.scss
Labels: button

#1958 fix: add avatar selector under the header
  src/card.scss
Labels: winter 2020

#1949 fix: improve class structure for Switch component
  src/switch.scss
  stories/switch/switch.stories.js
Labels: Enhancement

#1960 chore: add font and icon instructions to README for project config
  README.md
Labels: winter 2020

#1953 docs: update Tabs component documentation
  stories/tabs/__snapshots__/tabs.stories.storyshot
  stories/tabs/tabs.stories.js
Labels: Doc website

#1968 docs: update Toolbar component documentation
  stories/toolbar/__snapshots__/toolbar.stories.storyshot
  stories/toolbar/toolbar.stories.js
Labels: Doc website

#1959 docs: update Time component documentation
  stories/time/__snapshots__/time.stories.storyshot
  stories/time/time.stories.js
Labels: Doc website

#1957 chore: change master to main and update travis.yml
  .travis.yml
  CHANGELOG.md
  README.md
  ci-scripts/publish.sh
  config/postcss.config.js
  scripts/publish-release.sh
Labels: winter 2020

#1984 docs: update form item documentation
  stories/form-item/form-item.stories.js
Labels: Doc website

#1985 docs: update form label documentation
  stories/form-label/form-label.stories.js
Labels: Doc website

#1983 docs: update form header documentation
  stories/form-header/__snapshots__/form-header.stories.storyshot
  stories/form-header/form-header.stories.js
Labels: Doc website

#1982 docs: update form group documentation
  stories/form-group/__snapshots__/form-group.stories.storyshot
  stories/form-group/form-group.stories.js
Labels: Doc website

#1961 docs: update token component documentation
  stories/token/__snapshots__/token.stories.storyshot
  stories/token/token.stories.js
Labels: Doc website

#1971 docs: update tree documentation
  stories/tree/__snapshots__/tree.stories.storyshot
  stories/tree/tree.stories.js
Labels: Doc website

#1974 fix: add fd-title to global styles
  src/fundamental-styles.scss
Labels: winter 2020

#1970 feat: more control over no gap for grid layout
  src/layout-grid.scss
  stories/layout-grid/__snapshots__/layout-grid.stories.storyshot
  stories/layout-grid/layout-grid.stories.js
Labels: winter 2020

#1969 fix: outline color of breakcrumb icon overflow
  src/breadcrumb.scss
Labels: winter 2020

#1898 feat: introduce Quick View component
  .storybook/custom/custom.scss
  src/fundamental-styles.scss
  src/quick-view.scss
  stories/quick-view/__snapshots__/quick-view.stories.storyshot
  stories/quick-view/quick-view.stories.js
Labels: Fiori 3 New Component

#1993 fix: segmented button on calendar
  stories/calendar/calendar.stories.js
Labels: winter 2020

#1992 fix: table footer background color
  src/table.scss
Labels: winter 2020

#1976 fix: hover text decoration of icon with link
  src/link.scss
  stories/link/link.stories.js
Labels: winter 2020

#1973 fix: focus of select
  src/select.scss
Labels: winter 2020
