Repository SAP/fundamental-styles, pull requests merged in 2020-09, with the labels that each got.

#1533 fix: update Calendar dismiss button
  src/calendar.scss
  stories/calendar/__snapshots__/calendar.stories.storyshot
  stories/calendar/calendar.stories.js
  stories/datepicker/datepicker.stories.js
  storybook-testing/__image_snapshots__/Calendar-snap.png
  storybook-testing/__image_snapshots__/DatePicker-snap.png
Labels: Bug

#1524 docs: updated icon documentation
  stories/icon/icon.stories.js
Labels: Doc website

#1570 docs: updated icon documentation (2)
  stories/icon/icon.stories.js
Labels: Doc website

#1576 fix: Change size in panel title
  src/panel.scss
  stories/panel/__snapshots__/panel.stories.storyshot
  stories/panel/panel.stories.js
  storybook-testing/__image_snapshots__/Panel-snap.png
Labels: Fiori 3 refactoring

#1571 fix: add text-shadow for better contrast
  src/mixins/_mixins.scss
  src/object-status.scss
  src/table.scss
  storybook-testing/__image_snapshots__/Link-snap.png
  storybook-testing/__image_snapshots__/ObjectStatus-snap.png
  storybook-testing/__image_snapshots__/Table-snap.png
Labels: A11y

#1419 feat: Object Number new component
  src/object-number.scss
  stories/object-number/__snapshots__/object-number.stories.storyshot
  stories/object-number/custom.scss
  stories/object-number/object-number.stories.js
  stories/object-number/object-number.visual.js
  storybook-testing/__image_snapshots__/ObjectNumber-snap.png
Labels: Valor, ariba

#1569 fix: Add spacing for list selection
  src/_listDefinitions.scss
  src/_listNavigation.scss
  src/_listSelection.scss
Labels: Fiori 3 refactoring

#1578 feat: new component Action Sheet
  .storybook/custom/components/tags.json
  .storybook/preview-head.html
  src/action-sheet.scss
  src/button.scss
  src/mixins/_layouts.scss
  src/mixins/_popover.scss
  src/popover.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
  stories/action-sheet/__snapshots__/action-sheet.stories.storyshot
  stories/action-sheet/action-sheet.stories.js
  stories/action-sheet/action-sheet.visual.js
Labels: Fiori 3 New Component

#1529 docs: updated info label documentation
  stories/info-label/__snapshots__/info-label.stories.storyshot
  stories/info-label/info-label.stories.js
  storybook-testing/__image_snapshots__/InfoLabel-snap.png
Labels: Doc website

#1582 docs: updated link documentation
  stories/link/__snapshots__/link.stories.storyshot
  stories/link/link.stories.js
Labels: Doc website

#1610 chore: align storybook packages' versions
  package-lock.json
  package.json
Labels: storybook

#1609 chore: bump sap-theming package version
  package-lock.json
  package.json
  storybook-testing/__image_snapshots__/Tree-snap.png
Labels: Theming

#1611 chore: bump package.json libraries versions
  package-lock.json
  package.json
Labels: Dependencies

#1465 feat: new Rating Indicator component
  package.json
  src/fundamental-styles.scss
  src/rating-indicator.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
  stories/rating-indicator/custom.scss
  stories/rating-indicator/rated.png
  stories/rating-indicator/rating-indicator.stories.js
  stories/rating-indicator/rating-indicator.visual.js
  stories/rating-indicator/unrated.png
Labels: Fiori 3 New Component, Valor, ariba, gb

#1622 fix: remove unused rating indicator delta theming variables
  src/rating-indicator.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
Labels: Theming

#1607 docs: update menu documentation
  stories/menu/__snapshots__/menu.stories.storyshot
  stories/menu/menu.stories.js
Labels: Doc website

#1642 fix: Create base SCSS mixins for icons
  src/mixins/_mixins.scss
Labels: Enhancement

#1645 fix: Reset font-style on icons
  src/icon.scss
Labels: icons

#1567 fix: updating Notifications according to the latest design
  src/mixins/_mixins.scss
  src/notification.scss
  stories/notification/__snapshots__/notification.stories.storyshot
  stories/notification/notification.stories.js
  stories/notification/notification.visual.js
Labels: 0.12.0, Fiori 3 refactoring

#1660 chore: rename the delta theming parameters with fd prefix
  src/action-sheet.scss
  src/object-status.scss
  src/rating-indicator.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
Labels: Theming

#1621 feat: new Fiori 3 Wizard component
  .storybook/custom/custom.scss
  config/bundlesize.json
  src/bar.scss
  src/fundamental-styles.scss
  src/mixins/_mixins.scss
  src/page.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
  src/wizard.scss
  stories/bar/__snapshots__/bar.stories.storyshot
  stories/bar/bar.stories.js
  stories/wizard/__snapshots__/wizard.stories.storyshot
  stories/wizard/wizard.stories.js
  stories/wizard/wizard.visual.js
  storybook-testing/__image_snapshots__/Wizard-snap.png
Labels: 0.12.0, Fiori 3 New Component

#1592 fix: padding fix for compact radio button
  src/mixins/_forms.scss
  src/radio.scss
  stories/radio/__snapshots__/radio.stories.storyshot
  stories/radio/radio.stories.js
Labels: Bug, Defect Hunting

#1653 fix: Menu - Refactor icons usage
  src/menu.scss
  stories/menu/__snapshots__/menu.stories.storyshot
  stories/menu/menu.stories.js
Labels: 0.12.0, Enhancement, icons

#1662 fix: Remove redundant focus on empty forms
  src/checkbox.scss
  src/mixins/_forms.scss
  src/radio.scss
Labels: 0.12.0

#1646 fix: Apply icons changes to tabs
  src/tabs.scss
  stories/tabs/__snapshots__/tabs.stories.storyshot
  stories/tabs/tabs.stories.js
Labels: 0.12.0, icons

#1650 fix: refactor icons in switch
  src/switch.scss
  stories/switch/switch.stories.js
Labels: 0.12.0, Enhancement, icons

#1657 fix: Refactor icons and text in object marker
  src/object-marker.scss
  stories/object-marker/__snapshots__/object-marker.stories.storyshot
  stories/object-marker/object-marker.stories.js
Labels: 0.12.0, Enhancement

#1652 fix: change icons on product switch
  src/product-switch.scss
  stories/product-switch/product-switch.stories.js
Labels: 0.12.0, icons

#1675 fix: Side Navigation - Refactor icons usage - #2
  src/_nested-list.scss
  stories/side-navigation/side-navigation.stories.js
Labels: Enhancement, icons

#1677 fix: Table, List - Refactor icons usage - #2
  src/_listBase.scss
  src/_listByline.scss
  src/table.scss
  stories/card/card.stories.js
  stories/list/byline/__snapshots__/byline-list.stories.storyshot
  stories/list/byline/byline-list.stories.js
  stories/list/standard/standard-list.stories.js
  stories/select/select.stories.js
  stories/table/__snapshots__/table.stories.storyshot
  stories/table/table.stories.js
Labels: 0.12.0, Enhancement, icons

#1676 fix: Message Page - Refactor icons usage - #2
  src/message-page.scss
  stories/message-page/message-page.stories.js
Labels: 0.12.0, Enhancement, icons

#1674 fix: Numeric Content - Refactor icons usage #2
  src/numeric-content.scss
  stories/card/card.stories.js
  stories/generictile/__snapshots__/generic-tile.stories.storyshot
  stories/generictile/generic-tile.stories.mdx
  stories/numeric-content/__snapshots__/numeric-content.stories.storyshot
  stories/numeric-content/numeric-content.stories.js
Labels: 0.12.0, Enhancement, icons

#1649 fix: Info label - Refactor icons usage
  src/info-label.scss
  stories/info-label/__snapshots__/info-label.stories.storyshot
  stories/info-label/info-label.stories.js
Labels: 0.12.0, Enhancement, icons

#1647 fix: Tile - Refactor icons usage
  src/tile.scss
  stories/generictile/__snapshots__/generic-tile.stories.storyshot
  stories/generictile/generic-tile.stories.mdx
Labels: 0.12.0, Enhancement, icons

#1644 fix: Avatar - refactor icons usage
  src/avatar.scss
  stories/avatar/__snapshots__/avatar.stories.storyshot
  stories/avatar/avatar.stories.js
Labels: 0.12.0, Enhancement, icons

#1643 fix: Apply icons changes to tree
  config/bundlesize.json
  src/button.scss
  src/tree.scss
  stories/tree/__snapshots__/tree.stories.storyshot
  stories/tree/tree.stories.js
Labels: 0.12.0, icons

#1655 fix: Refactor object status icons and text
  src/object-status.scss
  stories/object-status/__snapshots__/object-status.stories.storyshot
  stories/object-status/object-status.stories.js
Labels: 0.12.0, Enhancement, icons

#1698 fix: update icons in tile actions
  src/mixins/button/_button-helper.scss
  src/tile.scss
  stories/generictile/__snapshots__/generic-tile.stories.storyshot
  stories/generictile/generic-tile.stories.mdx
Labels: 0.12.0, Defect Hunting, icons

#1694 docs: 0.12.0 minor docs issues
  .storybook/preview-head.html
  stories/action-bar/__snapshots__/action-bar.stories.storyshot
  stories/action-bar/action-bar.stories.js
  stories/breadcrumb/__snapshots__/breadcrumb.stories.storyshot
  stories/breadcrumb/breadcrumb.stories.js
  stories/feed-input/feed-input.stories.js
  stories/form-message/form-message.stories.js
Labels: 0.12.0, Defect Hunting

#1695 docs: A11y on form grid examples
  stories/form-grid/__snapshots__/form-grid.stories.storyshot
  stories/form-grid/form-grid.stories.js
Labels: 0.12.0, A11y, Defect Hunting

#1696 fix: Unique id values in list examples
  stories/list/byline/byline-list.stories.js
  stories/list/standard/standard-list.stories.js
Labels: 0.12.0, Defect Hunting

#1699 fix: Input States documentation
  stories/input/__snapshots__/input.stories.storyshot
  stories/input/input.stories.js
Labels: 0.12.0, Defect Hunting, Doc website

#1691 fix: Remove double outline from side navigation expand button
  src/_nested-list.scss
  stories/side-navigation/side-navigation.stories.js
Labels: 0.12.0, Defect Hunting, icons

#1689 docs: update 2 column select button example
  stories/select/select.stories.js
Labels: 0.12.0, Doc website

#1697 fix: update Avatar in Object Card example
  stories/card/card.stories.js
Labels: 0.12.0, Defect Hunting, Doc website

#1673 docs: updated checkbox documentation
  stories/checkbox/__snapshots__/checkbox.stories.storyshot
  stories/checkbox/checkbox.stories.js
Labels: Doc website

#1704 fix: rating indicator halves IE11
  src/rating-indicator.scss
Labels: 0.12.0, Bug, Defect Hunting, IE11

#1728 chore: replace toolbar temporary variable
  src/toolbar.scss
Labels: Theming
