Repository SAP/fundamental-styles, pull requests merged in 2020-05, with the labels that each got.

#894 feat: Modify examples with doubled menu box shadow
  docs/pages/components/action-bar.md
  docs/pages/components/button.md
  docs/pages/components/localization-editor.md
  docs/pages/components/popover.md
  docs/pages/components/shellbar.md
  docs/pages/components/table.md
  docs/pages/components/tile.md
  docs/pages/components/tree.md
  docs/pages/patterns/contextual-menu.md
  docs/pages/patterns/multi-input.md
  docs/pages/patterns/search-input.md
Labels: 0.9.0, Doc website

#930 fix: debug standard version
  CHANGELOG.md
  ci-scripts/publish.sh
Labels: tooling

#922 feat: migrate pagination with theming parameters
  config/bundlesize.json
  docs/pages/components/pagination.md
  src/pagination.scss
  test/templates/pagination/component.njk
  test/visual-regression-tests/reference_images/FS_pagination_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_pagination_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_pagination_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_pagination_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_pagination_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_pagination_5_backstop__n5_0_.png
Labels: Theming

#891 fix: Add RTL padding to list message
  src/list.scss
  test/visual-regression-tests/reference_images/FS_list_19_backstop__n19_0_.png
Labels: Bug

#937 fix: deprecate Image
  docs/pages/components/avatar.md
  docs/pages/components/image.md
  package-lock.json
Labels: 0.9.0

#910 fix: add ActionListItem functionality to List component
  config/bundlesize.json
  docs/pages/components/list.md
  src/list.scss
  test/templates/list/component.njk
  test/templates/list/index.njk
  test/visual-regression-tests/reference_images/FS_DS_Store_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_list_14_backstop__n14_0_.png
  test/visual-regression-tests/reference_images/FS_list_17_backstop__n17_0_.png
  test/visual-regression-tests/reference_images/FS_list_18_backstop__n18_0_.png
  test/visual-regression-tests/reference_images/FS_list_19_backstop__n19_0_.png
Labels: Fiori 3 New Feature

#893 fix: Remove overflow:hidden from switch
  src/switch.scss
Labels: 0.9.0

#942 docs: Change markup for datepicker
  docs/pages/patterns/date-picker.md
Labels: 0.9.0

#939 fix: Add RTL support for select
  src/select.scss
  test/visual-regression-tests/reference_images/FS_select_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_select_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_select_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_select_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_select_4_backstop__n4_0_.png
Labels: 0.9.0

#949 feat: Remove search input
  docs/_data/patterns.yml
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/_sass/_docs-display-component.scss
  docs/images/component-visual/search-input.png
  docs/pages/components/shellbar.md
  docs/pages/patterns/search-input.md
  src/_search-input.scss
  src/shellbar.scss
  test/templates/shellbar/component.njk
Labels: 0.9.0

#947 fix: Add RTL support to Avatar
  docs/pages/components/message-box.md
  src/avatar.scss
  test/templates/avatar/component.njk
  test/templates/avatar/data.json
  test/templates/avatar/index.njk
  test/visual-regression-tests/reference_images/FS_avatar_6_backstop__n6_0_.png
Labels: 0.9.0, Bug

#917 docs: remove margin with list
  docs/_sass/_docs-headers.scss
  docs/_sass/_docs-main-content.scss
Labels: Doc website

#944 fix: Add margin reset to mobile menu sub-list
  docs/pages/components/menu.md
  src/menu.scss
Labels: Bug

#945 fix: RTL calendar landscape orientation
  docs/_sass/_docs-display-component.scss
  src/calendar.scss
  test/templates/calendar/index.njk
  test/visual-regression-tests/reference_images/FS_calendar_4_backstop__n4_0_.png
Labels: 0.9.0

#950 docs: Display icon for each message-box example
  docs/pages/components/message-box.md
Labels: Doc website

#943 fix: multi-input take margin from checkbox on RTL
  src/list.scss
Labels: 0.9.0

#940 fix: Shellbar remove padding on buttons
  src/shellbar.scss
Labels: 0.9.0

#954 docs: info about RTL mode added
  docs/pages/components/form.md
Labels: 0.9.0

#953 docs: hide Selection List and List with Byline from documentation page
  docs/pages/components/list.md
Labels: 0.9.0, Doc website

#946 fix: fixed more content arrow on rtl mode
  src/side-nav.scss
  test/resources/layout.css
  test/visual-regression-tests/reference_images/FS_side-nav_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_side-nav_1_backstop__n1_0_.png
Labels: 0.9.0

#923 feat: breadcrumb popover with proper fiori 3
  docs/pages/components/breadcrumb.md
  src/breadcrumb.scss
  test/visual-regression-tests/reference_images/FS_breadcrumb_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_breadcrumb_1_backstop__n1_0_.png
Labels: 0.9.0

#955 docs: remove obsolete demo pages
  docs/_includes/demo-page-components/alert-app-overlay.html
  docs/_includes/demo-page-components/app-sidebar-content.html
  docs/_includes/demo-page-components/empty-page-content.html
  docs/_includes/demo-page-components/shell-header.html
  docs/_includes/demo-page-components/table-page-content.html
  docs/_includes/demo-page-components/tile-page-content.html
  docs/_includes/demo-page-components/tree-page-content.html
  docs/pages/demo-pages/empty.md
  docs/pages/demo-pages/full-width-app-demo.md
  docs/pages/demo-pages/index.md
  docs/pages/demo-pages/shell.md
  docs/pages/demo-pages/sidebar-app-demo.md
  docs/pages/demo-pages/table.md
  docs/pages/demo-pages/tiles.md
  docs/pages/demo-pages/tree.md
  docs/pages/layouts/index.md
Labels: Doc website

#957 docs: add responsive design for Calendar doc page
  docs/_sass/_docs-general.scss
  docs/pages/components/calendar.md
Labels: 0.9.0, Doc website

#962 chore: improve travis build time
  .travis.yml
Labels: tooling

#959 docs: removed empty th
  docs/pages/patterns/date-picker.md
Labels: 0.9.0

#966 fix: add fix for Action Bar actions not taking the whole width
  src/action-bar.scss
Labels: 0.9.0

#969 fix: add fix for ActionListItem missing active state in IE11
  src/list.scss
  test/templates/list/component.njk
  test/visual-regression-tests/reference_images/FS_list_14_backstop__n14_0_.png
  test/visual-regression-tests/reference_images/FS_list_19_backstop__n19_0_.png
Labels: 0.9.0

#968 fix: add fix for the text overflow in Shellbar
  docs/pages/components/shellbar.md
  src/shellbar.scss
Labels: 0.9.0

#967 fix: Fix dropdown fill content no ie11
  src/popover.scss
Labels: 0.9.0

#965 fix: Fix product switch mobile mode on ie11
  src/product-switch.scss
Labels: 0.9.0

#964 fix: IE11 popover list overflow fix
  src/list.scss
Labels: 0.9.0

#958 fix: multi input second button fix
  src/bar.scss
Labels: 0.9.0

#963 fix: remove x for IE in input
  src/input.scss
Labels: 0.9.0, Bug, IE11

#916 fix: shellbar product menu padding bug
  src/shellbar.scss
  test/visual-regression-tests/reference_images/FS_shellbar_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_shellbar_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_shellbar_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_shellbar_5_backstop__n5_0_.png
Labels: Bug, shellbar

#971 docs: deprecate number input
  docs/pages/components/input-group.md
Labels: 0.9.0, Doc website

#972 docs: update list example using old fd-colors
  docs/pages/components/list.md
Labels: 0.9.0, Doc website

#973 docs: remove some popover examples
  docs/pages/components/popover.md
Labels: 0.9.0, Doc website

#974 docs: remove old doc utilities
  docs/pages/resources/design-system-utilities.md
Labels: 0.9.0, Doc website

#977 fix: overflow removed in order to show popover
  src/shellbar.scss
Labels: 0.9.0

#975 docs: removed styles which causes problem with rtl
  docs/_sass/_docs-general.scss
  docs/pages/components/calendar.md
  docs/pages/components/dialog.md
  docs/pages/components/message-box.md
  docs/pages/components/side-navigation.md
Labels: 0.9.0

#982 fix: dialog resize handle in RTL mode
  src/dialog.scss
Labels: Bug, RTL

#904 chore: story book integration
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  .storybook/resources/theme-ugly.css
  .storybook/resources/unnormalize.css
  babel.config.js
  config/jest.config.js
  config/storyshots-setup.js
  integration/__image_snapshots__/storyshots-test-js-image-storyshots-button-text-1-snap.png
  integration/storyshots.test.js
  jest-puppeteer.config.js
  package-lock.json
  package.json
  stories/base.css
  stories/button/button.html
  stories/button/button.stories.js
Labels: tooling

#985 test: storybook doesn't dettect changes made on component
  .storybook/main.js
  integration/__image_snapshots__/storyshots-test-js-image-storyshots-button-text-1-snap.png
  integration/storyshots.test.js
  package.json
  stories/base.scss
  stories/button/button.stories.js
Labels: tooling

#988 docs: update google analytics
  docs/_config.yml
  docs/_includes/head.html
Labels: Doc website

#983 feat: remove group list component
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/images/component-visual/list-group.png
  docs/pages/components/list-group.md
  docs/pages/components/list.md
  src/fundamental-styles.scss
  src/list-group.scss
  test/templates/index.njk
  test/templates/list-group/component.njk
  test/templates/list-group/data.json
  test/templates/list-group/index.njk
  test/visual-regression-tests/reference_images/FS_list-group_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_list-group_1_backstop__n1_0_.png
Labels: 0.10.0

#1013 feat: Select component reference markup
  docs/pages/components/select.md
  test/templates/select/component.njk
Labels: A11y

#989 feat: remove status indicator components
  docs/_data/components.yml
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/images/component-visual/counter.png
  docs/pages/components/asset-upload.md
  docs/pages/components/counter.md
  docs/pages/components/icon.md
  docs/pages/components/inline-help.md
  docs/pages/components/notification.md
  docs/pages/components/status-indicators.md
  docs/pages/components/table.md
  docs/pages/components/tree.md
  src/badge.scss
  src/fundamental-styles.scss
  src/info-label.scss
  src/label.scss
  src/status-label.scss
  test/templates/badge/component.njk
  test/templates/badge/data.json
  test/templates/badge/index.njk
  test/templates/index.njk
  test/templates/label/component.njk
  test/templates/label/data.json
  test/templates/label/index.njk
  test/templates/pages/panel.njk
  test/templates/pages/section.njk
  test/templates/pages/tiles.njk
  test/templates/status-label/component.njk
  test/templates/status-label/data.json
  test/templates/status-label/index.njk
  test/visual-regression-tests/reference_images/FS_DS_Store_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_badge_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_badge_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_badge_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_badge_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_label_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_status-label_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_status-label_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_status-label_2_backstop__n2_0_.png
Labels: 0.10.0

#986 fix: Step Input
  docs/_data/components.yml
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/pages/components/step-input.md
  package-lock.json
  src/form-label.scss
  src/fundamental-styles.scss
  src/mixins/_states.scss
  src/step-input.scss
  stories/step-input/step-input.html
  stories/step-input/step-input.stories.js
  test/templates/form-label/component.njk
  test/templates/form-label/data.json
  test/templates/form-label/index.njk
  test/templates/index.njk
  test/templates/step-input/component.njk
  test/templates/step-input/data.json
  test/templates/step-input/index.njk
  test/visual-regression-tests/reference_images/FS_form-label_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_form-label_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_form-label_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_step-input_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_step-input_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_step-input_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_step-input_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_step-input_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_step-input_5_backstop__n5_0_.png
  test/visual-regression-tests/reference_images/FS_step-input_6_backstop__n6_0_.png
  test/visual-regression-tests/reference_images/FS_step-input_7_backstop__n7_0_.png
Labels: 0.10.0

#1039 docs: add favicon
  docs/_includes/head.html
  docs/_layouts/default-no-sidebar.html
  docs/_layouts/default.html
  docs/favicon.ico
  package-lock.json
Labels: Doc website

#1040 chore: update dependencies from package.json
  package-lock.json
  package.json
Labels: Dependencies

#1027 fix: add shellbar button hover styles to :focus as well
  src/shellbar.scss
Labels: A11y, Bug

#1056 fix: remove the spacing from the last page indicator
  src/tile.scss
Labels: Bug

#1022 fix: introduce toolbar component
  .gitignore
  .storybook/main.js
  .storybook/resources/theme-ugly.css
  docs/_data/components.yml
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/images/component-visual/toolbar.png
  docs/pages/components/toolbar.md
  integration/__image_snapshots__/storyshots-test-js-image-storyshots-button-text-1-snap.png
  integration/__image_snapshots__/storyshots-test-js-image-storyshots-step-input-all-cases-1-snap.png
  integration/__image_snapshots__/storyshots-test-js-image-storyshots-toolbar-default-1-snap.png
  integration/__image_snapshots__/storyshots-test-js-image-storyshots-toolbar-overflow-menu-opened-1-snap.png
  integration/__image_snapshots__/storyshots-test-js-image-storyshots-toolbar-rtl-1-snap.png
  package-lock.json
  package.json
  src/fundamental-styles.scss
  src/toolbar.scss
  stories/toolbar/toolbar.html
  stories/toolbar/toolbar.stories.js
Labels: 0.10.0

#1062 fix: removed active state except info, test updated for docker
  docs/pages/components/toolbar.md
  integration/__image_snapshots__/storyshots-test-js-image-storyshots-numeric-content-all-cases-1-snap.png
  integration/__image_snapshots__/storyshots-test-js-image-storyshots-step-input-all-cases-1-snap.png
  integration/__image_snapshots__/storyshots-test-js-image-storyshots-tile-all-cases-1-snap.png
  integration/__image_snapshots__/storyshots-test-js-image-storyshots-toolbar-default-1-snap.png
  integration/__image_snapshots__/storyshots-test-js-image-storyshots-toolbar-overflow-menu-opened-1-snap.png
  integration/__image_snapshots__/storyshots-test-js-image-storyshots-toolbar-rtl-1-snap.png
  src/toolbar.scss
Labels: 0.10.0

#1065 docs: Fix header on IE11
  docs/_sass/_docs-top-nav.scss
Labels: 0.10.0

#1063 docs: layout styles fixed
  docs/_sass/_docs-general.scss
  docs/_sass/_docs-tile.scss
  docs/css/docs-all.scss
  src/mixins/_layouts.scss
Labels: 0.10.0, Bug, Doc website

#1064 docs: multi-input - add example showing use of "show all" text
  docs/pages/patterns/multi-input.md
Labels: Bug, Doc website

#1070 chore: update getting started guide to point to font downloads
  docs/pages/getting-started.md
Labels: Doc website

#1073 feat: rename Panel to Layout Panel, migrate to theme parameters
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/_sass/_docs-display-component.scss
  docs/pages/components/loading-spinner.md
  docs/pages/layouts/grid.md
  docs/pages/layouts/index.md
  docs/pages/layouts/layout-grid.md
  docs/pages/layouts/layout-panel.md
  docs/pages/layouts/panel.md
  docs/pages/layouts/section.md
  integration/__image_snapshots__/storyshots-test-js-image-storyshots-layout-panel-all-cases-1-snap.png
  src/fundamental-styles.scss
  src/layout-panel.scss
  src/mixins/_mixins.scss
  src/panel.scss
  stories/layout-panel/layout-panel.html
  stories/layout-panel/layout-panel.stories.js
  test/resources/layout.css
  test/templates/index.njk
  test/templates/layout-grid/index.njk
  test/templates/layout-panel/component.njk
  test/templates/layout-panel/data.json
  test/templates/layout-panel/index.njk
  test/templates/layout/component.njk
  test/templates/pages/app/product-overview.njk
  test/templates/pages/grid.njk
  test/templates/pages/layout-panel.njk
  test/templates/panel/data.json
  test/templates/panel/index.njk
  test/templates/spinner/index.njk
  test/visual-regression-tests/reference_images/FS_layout-panel_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_panel_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_panel_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_panel_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_panel_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_panel_4_backstop__n4_0_.png
Labels: 0.10.0

#1024 fix: introduce panel component
  docs/_data/components.yml
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/images/component-visual/panel.png
  docs/pages/components/panel.md
  integration/__image_snapshots__/storyshots-test-js-image-storyshots-expand-panel-all-cases-1-snap.png
  src/fundamental-styles.scss
  src/mixins/_mixins.scss
  src/panel.scss
  stories/panel/panel.html
  stories/panel/panel.stories.js
Labels: 0.10.0

#1075 docs: introduce tags for component doc pages
  docs/_data/tags.yml
  docs/_layouts/page.html
  docs/pages/components/button.md
Labels: 0.10.0

#1071 docs: make the new List types visible in the documentation
  docs/pages/components/list.md
Labels: Doc website

#1076 docs: add tags on component docs pages
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/_data/tags.yml
  docs/pages/components/action-bar.md
  docs/pages/components/alert.md
  docs/pages/components/asset-upload.md
  docs/pages/components/avatar.md
  docs/pages/components/bar.md
  docs/pages/components/breadcrumb.md
  docs/pages/components/busy-indicator.md
  docs/pages/components/calendar.md
  docs/pages/components/counter.md
  docs/pages/components/dialog.md
  docs/pages/components/form.md
  docs/pages/components/generic-tile.md
  docs/pages/components/icon.md
  docs/pages/components/image.md
  docs/pages/components/info-label.md
  docs/pages/components/inline-help.md
  docs/pages/components/input-group.md
  docs/pages/components/link.md
  docs/pages/components/list.md
  docs/pages/components/localization-editor.md
  docs/pages/components/menu.md
  docs/pages/components/message-box.md
  docs/pages/components/message-strip.md
  docs/pages/components/message-toast.md
  docs/pages/components/notification.md
  docs/pages/components/object-status.md
  docs/pages/components/pagination.md
  docs/pages/components/panel.md
  docs/pages/components/popover.md
  docs/pages/components/product-switch.md
  docs/pages/components/select.md
  docs/pages/components/shellbar.md
  docs/pages/components/side-navigation.md
  docs/pages/components/step-input.md
  docs/pages/components/switch.md
  docs/pages/components/table.md
  docs/pages/components/tabs.md
  docs/pages/components/time.md
  docs/pages/components/token.md
  docs/pages/components/toolbar.md
  docs/pages/components/tree.md
  docs/pages/patterns/combobox-input.md
  docs/pages/patterns/contextual-menu.md
  docs/pages/patterns/date-picker.md
  docs/pages/patterns/multi-input.md
  docs/pages/patterns/step-input.md
  docs/pages/patterns/time-picker.md
Labels: 0.10.0, Doc website

#1077 docs: a minor doc issue list components
  docs/pages/components/list.md
Labels: 0.10.0, Doc website
