Repository SAP/fundamental-styles, pull requests merged in 2020-01, with the labels that each got.

#558 fix: (InputGroup) Add min-width property only for ie10+, fix addon truncation
  src/input-group.scss
Labels: 0.4.0

#559 docs: landing page
  docs/_layouts/default-no-sidebar.html
  docs/_sass/_docs-main-content.scss
  docs/_sass/_landingPage.scss
  docs/css/docs-all.scss
  docs/images/land-page-assets/about_background.png
  docs/images/land-page-assets/angular.png
  docs/images/land-page-assets/collaborative.png
  docs/images/land-page-assets/css_html.png
  docs/images/land-page-assets/flexible.png
  docs/images/land-page-assets/foundational.png
  docs/images/land-page-assets/github.png
  docs/images/land-page-assets/hero_background.png
  docs/images/land-page-assets/logo.svg
  docs/images/land-page-assets/logo_text.png
  docs/images/land-page-assets/modular.png
  docs/images/land-page-assets/react.png
  docs/images/land-page-assets/sap.png
  docs/images/land-page-assets/slack.png
  docs/images/land-page-assets/twitter.png
  docs/images/land-page-assets/vue.png
  docs/images/land-page-assets/youtube.png
  docs/index.html
Labels: Doc website

#550 fix: Broken product switch on mobile devices - IE11
  src/product-switch.scss
Labels: 0.5.0

#551 fix: Misaligned check in table header context menu (documentation)
  docs/pages/components/table.md
Labels: 0.5.0

#473 feat:popover refactoring
  docs/pages/components/popover.md
  src/popover.scss
  test/resources/theme-ugly.css
  test/templates/popover/component.njk
  test/templates/popover/index.njk
  test/visual-regression-tests/reference_images/FS_popover_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_popover_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_popover_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_popover_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_popover_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_popover_5_backstop__n5_0_.png
  test/visual-regression-tests/reference_images/FS_popover_6_backstop__n6_0_.png
  test/visual-regression-tests/reference_images/FS_popover_7_backstop__n7_0_.png
  test/visual-regression-tests/reference_images/FS_popover_8_backstop__n8_0_.png
Labels: 0.5.0, Fiori 3 refactoring

#587 docs: Change usage of checkbox in multi input example
  docs/pages/patterns/multi-input.md
Labels: 0.5.0

#490 fix: Align side-nav navigation arrow on IE11
  src/_nested-list.scss
  test/templates/side-nav/index.njk
  test/visual-regression-tests/reference_images/FS_side-nav_2_backstop__n2_0_.png
Labels: 0.5.0

#471 feat: Adjust tabs to fiori3 specification
  docs/pages/components/tabs.md
  src/tabs.scss
  test/templates/tabs/index.njk
  test/visual-regression-tests/reference_images/FS_tabs_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_tabs_10_backstop__n10_0_.png
  test/visual-regression-tests/reference_images/FS_tabs_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_tabs_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_tabs_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_tabs_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_tabs_5_backstop__n5_0_.png
  test/visual-regression-tests/reference_images/FS_tabs_6_backstop__n6_0_.png
  test/visual-regression-tests/reference_images/FS_tabs_7_backstop__n7_0_.png
  test/visual-regression-tests/reference_images/FS_tabs_8_backstop__n8_0_.png
  test/visual-regression-tests/reference_images/FS_tabs_9_backstop__n9_0_.png
Labels: 0.5.0, Fiori 3 refactoring

#492 feat: toggle follow fiori3
  docs/pages/components/toggle.md
  src/form-label.scss
  src/fundamental-styles.scss
  src/switch.scss
  src/toggle.scss
  test/templates/index.njk
  test/templates/switch/component.njk
  test/templates/switch/data.json
  test/templates/switch/index.njk
  test/templates/toggle/component.njk
  test/templates/toggle/data.json
  test/visual-regression-tests/reference_images/FS_switch_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_switch_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_switch_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_switch_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_switch_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_toggle_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_toggle_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_toggle_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_toggle_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_toggle_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_toggle_5_backstop__n5_0_.png
Labels: 0.5.0, Fiori 3 refactoring

#475 fix: Match link and breadcrumb to fiori3
  docs/_sass/_docs-display-component.scss
  docs/pages/components/breadcrumb.md
  docs/pages/components/link.md
  src/breadcrumb.scss
  src/mixins/_mixins.scss
  src/mixins/_states.scss
  test/templates/breadcrumb/component.njk
  test/templates/breadcrumb/data.json
  test/templates/breadcrumb/index.njk
  test/templates/link/data.json
  test/templates/link/index.njk
  test/visual-regression-tests/reference_images/FS_breadcrumb_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_breadcrumb_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_link_0_backstop_0_.png
Labels: 0.5.0, Fiori 3 refactoring

#488 fix: section lines added according to Fiori 3
  src/product-switch.scss
  test/visual-regression-tests/reference_images/FS_product-switch_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_product-switch_3_backstop__n3_0_.png
Labels: 0.5.0

#591 fix: form messages margin fix for textarea
  docs/pages/components/form.md
  src/textarea.scss
  test/visual-regression-tests/reference_images/FS_textarea_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_textarea_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_textarea_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_textarea_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_textarea_4_backstop__n4_0_.png
Labels: 0.5.0

#500 feat: token and tokenizer
  docs/pages/components/token.md
  docs/pages/patterns/multi-input.md
  src/fundamental-styles.scss
  src/token.scss
  src/tokenizer.scss
  test/templates/index.njk
  test/templates/token/component.njk
  test/templates/token/index.njk
  test/templates/tokenizer/component.njk
  test/templates/tokenizer/data.json
  test/templates/tokenizer/index.njk
  test/visual-regression-tests/reference_images/FS_token_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_token_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_token_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_token_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_token_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_tokenizer_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_tokenizer_1_backstop__n1_0_.png
Labels: 0.5.0

#603 docs: updated and improved landingpage
  docs/_sass/_landingPage.scss
  docs/images/land-page-assets/about_background.jpg
  docs/images/land-page-assets/about_background.png
  docs/images/land-page-assets/angular.png
  docs/images/land-page-assets/angular.svg
  docs/images/land-page-assets/collaborative.png
  docs/images/land-page-assets/css_html.png
  docs/images/land-page-assets/css_html.svg
  docs/images/land-page-assets/flexible.png
  docs/images/land-page-assets/foundational.png
  docs/images/land-page-assets/github.png
  docs/images/land-page-assets/hero_background.jpg
  docs/images/land-page-assets/hero_background.png
  docs/images/land-page-assets/logo.svg
  docs/images/land-page-assets/logo_text.png
  docs/images/land-page-assets/modular.png
  docs/images/land-page-assets/react.png
  docs/images/land-page-assets/react.svg
  docs/images/land-page-assets/sap.png
  docs/images/land-page-assets/slack.png
  docs/images/land-page-assets/twitter.png
  docs/images/land-page-assets/vue.png
  docs/images/land-page-assets/vue.svg
  docs/images/land-page-assets/youtube.png
  docs/index.html
Labels: Doc website

#586 feat: refactor Shellbar component to match Fiori 3 specs
  docs/_includes/demo-page-components/modal-app-overlay.html
  docs/_includes/demo-page-components/shell-header.html
  docs/_includes/topnav.html
  docs/_sass/_landingPage.scss
  docs/index.html
  docs/pages/components/shellbar.md
  src/_product-menu.scss
  src/shellbar.scss
  test/resources/theme-ugly.css
  test/templates/shellbar/component.njk
  test/templates/shellbar/index.njk
  test/visual-regression-tests/reference_images/FS_shellbar_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_shellbar_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_shellbar_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_shellbar_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_shellbar_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_shellbar_5_backstop__n5_0_.png
Labels: 0.6.0, Fiori 3 refactoring

#619 docs: correct alert navigation link in the documentation
  docs/_includes/demo-page-components/alert-app-overlay.html
  docs/pages/components/alert.md
Labels: 0.6.0, Doc website

#618 fix: Update table with checkbox docs example | Fix text-wrapping in textarea on Firefox
  docs/pages/components/table.md
  src/textarea.scss
Labels: 0.6.0, Bug

#620 fix: replace non-unique radio button id property values
  docs/pages/components/form.md
Labels: 0.6.0, Doc website

#621 docs: apply unified approach for loading images in the documentation
  docs/pages/components/identifier.md
  docs/pages/components/image.md
  docs/pages/components/popover.md
  docs/pages/components/shellbar.md
  docs/pages/components/table.md
  docs/pages/components/tile.md
Labels: 0.6.0
