Repository SAP/fundamental-styles, pull requests merged in 2020-03, with the labels that each got.

#714 feat: update message strip markup, update styling
  docs/pages/components/message-strip.md
  src/alert.scss
  src/message-strip.scss
  test/resources/layout.css
  test/templates/alert/component.njk
  test/templates/alert/data.json
  test/templates/alert/index.njk
  test/templates/index.njk
  test/templates/message-strip/component.njk
  test/templates/message-strip/index.njk
  test/visual-regression-tests/reference_images/FS_alert_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_alert_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_alert_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_alert_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_alert_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_message-strip_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_message-strip_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_message-strip_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_message-strip_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_message-strip_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_message-strip_5_backstop__n5_0_.png
  test/visual-regression-tests/reference_images/FS_message-strip_6_backstop__n6_0_.png
  test/visual-regression-tests/reference_images/FS_message-strip_7_backstop__n7_0_.png
Labels: 0.7.0, Bug

#716 fix:update notification dismiss button
  docs/pages/components/notification.md
  src/notification.scss
  test/templates/notification/index.njk
  test/visual-regression-tests/reference_images/FS_notification_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_notification_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_notification_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_notification_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_notification_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_notification_5_backstop__n5_0_.png
  test/visual-regression-tests/reference_images/FS_notification_6_backstop__n6_0_.png
  test/visual-regression-tests/reference_images/FS_notification_7_backstop__n7_0_.png
  test/visual-regression-tests/reference_images/FS_notification_8_backstop__n8_0_.png
Labels: 0.7.0, Bug

#701 feat: refactor action bar as per the fiori 3 colors and spacing
  docs/pages/components/action-bar.md
  src/action-bar.scss
  test/templates/action-bar/component.njk
  test/visual-regression-tests/reference_images/FS_action-bar_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_action-bar_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_action-bar_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_action-bar_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_action-bar_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_action-bar_5_backstop__n5_0_.png
Labels: 0.8.0, Fiori 3 refactoring

#638 feat:status indicator refactoring to infoLabel
  docs/_data/components.yml
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/_sass/_docs-component-list.scss
  docs/images/component-visual/info-label.png
  docs/pages/components/info-label.md
  docs/pages/components/status-indicators.md
  src/fundamental-styles.scss
  src/info-label.scss
  test/templates/index.njk
  test/templates/info-label/component.njk
  test/templates/info-label/data.json
  test/templates/info-label/index.njk
  test/visual-regression-tests/reference_images/FS_info-label_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_info-label_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_info-label_2_backstop__n2_0_.png
Labels: 0.7.0, Fiori 3 refactoring

#724 docs: update button in the dialog documentation
  docs/pages/components/dialog.md
Labels: 0.7.0, Doc website

#717 chore: update dev packages versions
  package-lock.json
  package.json
Labels: 0.8.0, Dependencies

#726 docs: datepicker button fix
  docs/pages/patterns/date-picker.md
Labels: 0.8.0, Bug

#728 fix: Cannot scroll Dialog body
  docs/pages/components/dialog.md
  src/dialog.scss
Labels: Bug

#729 docs: button update
  docs/pages/components/notification.md
  docs/pages/components/popover.md
  docs/pages/components/select.md
  docs/pages/patterns/combobox-input.md
  docs/pages/patterns/multi-input.md
Labels: 0.8.0

#725 fix: underline issue on side navigation
  docs/_sass/_landingPage.scss
Labels: 0.8.0, Bug

#731 chore:separate Fiori 3 variables from the old variables
  src/_new-settings.scss
  src/_settings.scss
  src/action-bar.scss
  src/alert.scss
  src/bar.scss
  src/breadcrumb.scss
  src/busy-indicator.scss
  src/button-split.scss
  src/button.scss
  src/calendar.scss
  src/checkbox.scss
  src/counter.scss
  src/dialog.scss
  src/form-input-message-group.scss
  src/form-item.scss
  src/form-label.scss
  src/form-message.scss
  src/info-label.scss
  src/input-group.scss
  src/input.scss
  src/link.scss
  src/list.scss
  src/message-strip.scss
  src/notification.scss
  src/page.scss
  src/popover.scss
  src/product-switch.scss
  src/radio.scss
  src/segmented-button.scss
  src/select.scss
  src/shellbar.scss
  src/side-nav.scss
  src/switch.scss
  src/tabs.scss
  src/textarea.scss
  src/token.scss
  src/tokenizer.scss
  test/visual-regression-tests/reference_images/FS_icon_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_select_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_select_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_select_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_select_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_select_4_backstop__n4_0_.png
Labels: 0.8.0

#506 feat: refactor Calendar component to match Fiori 3 specs
  docs/_includes/display-component.html
  docs/_sass/_docs-display-component.scss
  docs/pages/components/calendar.md
  docs/pages/patterns/date-picker.md
  src/calendar.scss
  test/templates/calendar/component.njk
  test/templates/calendar/data.json
  test/templates/calendar/index.njk
  test/visual-regression-tests/reference_images/FS_calendar_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_calendar_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_calendar_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_calendar_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_calendar_4_backstop__n4_0_.png
Labels: 0.8.0, Fiori 3 refactoring

#753 fix: radio and checkbox button RTL alignments
  src/checkbox.scss
  src/mixins/_forms.scss
  src/radio.scss
  test/templates/checkbox/index.njk
  test/templates/radio/index.njk
  test/visual-regression-tests/reference_images/FS_checkbox_6_backstop__n6_0_.png
  test/visual-regression-tests/reference_images/FS_radio_6_backstop__n6_0_.png
Labels: Bug, RTL

#760 feat: screen-reader only utility class
  docs/pages/components/calendar.md
  src/calendar.scss
  src/mixins/_mixins.scss
  test/templates/calendar/component.njk
  test/visual-regression-tests/reference_images/FS_calendar_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_calendar_3_backstop__n3_0_.png
Labels: A11y

#694 fix: status indicator refactoring to object status
  docs/_data/components.yml
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/images/component-visual/object-status.png
  docs/pages/components/object-status.md
  src/fundamental-styles.scss
  src/object-status.scss
  test/resources/theme-ugly.css
  test/templates/index.njk
  test/templates/object-status/index.njk
  test/visual-regression-tests/reference_images/FS_object-status_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_object-status_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_object-status_2_backstop__n2_0_.png
Labels: 0.8.0, Fiori 3 refactoring

#770 docs: step input component into patterns
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/images/component-visual/step-input.png
  docs/pages/patterns/step-input.md
Labels: 0.8.0

#691 fix: Minimal input width on IE11
  src/input-group.scss
Labels: 0.8.0

#761 fix: added support for text truncation if button width is set
  src/button.scss
Labels: 0.8.0, Bug

#771 docs: minor text update
  docs/index.html
Labels: Doc website

#777 feat: add internal label to switch component
  docs/pages/components/switch.md
  src/switch.scss
  test/templates/switch/component.njk
  test/templates/switch/index.njk
  test/visual-regression-tests/reference_images/FS_switch_2_backstop__n2_0_.png
Labels: Fiori 3 refactoring

#744 fix: make Shellbar button styles more specific
  src/shellbar.scss
  test/visual-regression-tests/reference_images/FS_radio_6_backstop__n6_0_.png
  test/visual-regression-tests/reference_images/FS_shellbar_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_shellbar_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_shellbar_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_shellbar_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_shellbar_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_shellbar_5_backstop__n5_0_.png
Labels: 0.8.0, Bug, self-contained, shellbar

#775 fix: make compact tokenizer inner width: auto and make cozy mode horizontally scrollable
  docs/js/customscripts.js
  docs/pages/components/token.md
  src/tokenizer.scss
  test/visual-regression-tests/reference_images/FS_tokenizer_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_tokenizer_1_backstop__n1_0_.png
Labels: 0.7.1

#782 docs: remove semantic switch example
  docs/pages/components/switch.md
Labels: 0.8.0, Doc website

#781 docs: add deprecate label to loading spinner component page
  docs/pages/components/loading-spinner.md
Labels: Doc website

#783 docs: remove second semantic switch example
  docs/pages/components/switch.md
Labels: Doc website

#780 fix: update Object Status to reflect the latest design changes
  docs/pages/components/object-status.md
  src/object-status.scss
  test/visual-regression-tests/reference_images/FS_object-status_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_object-status_2_backstop__n2_0_.png
Labels: Fiori 3 refactoring

#795 fix: update the line-height of the Object Status
  docs/pages/components/object-status.md
  src/object-status.scss
  test/visual-regression-tests/reference_images/FS_object-status_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_object-status_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_object-status_2_backstop__n2_0_.png
Labels: design review changes

#797 chore: bump theming library package version
  package-lock.json
  package.json
Labels: 0.8.0

#798 fix: busy indicator circles blurry in Safari
  src/busy-indicator.scss
  test/visual-regression-tests/reference_images/FS_busy-indicator_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_busy-indicator_1_backstop__n1_0_.png
Labels: 0.8.0, design review changes

#803 fix: use different icon for shellbar menu arrow
  src/shellbar.scss
Labels: 0.8.0

#702 feat: Menu refactor to Fiori3
  docs/_sass/_docs-display-component.scss
  docs/pages/components/menu.md
  src/menu.scss
  test/templates/menu/component.njk
  test/templates/menu/data.json
  test/templates/menu/index.njk
  test/visual-regression-tests/reference_images/FS_menu_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_menu_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_menu_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_menu_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_menu_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_menu_5_backstop__n5_0_.png
  test/visual-regression-tests/reference_images/FS_menu_6_backstop__n6_0_.png
Labels: 0.8.0, Fiori 3 refactoring

#809 fix: Add theming parameter for disabled forms
  src/input-group.scss
  src/mixins/_forms.scss
Labels: 0.8.0

#810 fix: Add box shadow to form messages
  src/form-message.scss
  test/visual-regression-tests/reference_images/FS_form-message_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_form-message_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_form-message_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_form-message_3_backstop__n3_0_.png
Labels: 0.8.0, design review changes

#794 fix: added workaround for creating release notes
  ci-scripts/publish.sh
Labels: tooling

#813 fix: replace info label border parameters
  src/info-label.scss
  test/visual-regression-tests/reference_images/FS_info-label_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_info-label_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_info-label_2_backstop__n2_0_.png
Labels: 0.8.0, design review changes

#814 fix: update token border and background theming params
  src/token.scss
  test/visual-regression-tests/reference_images/FS_token_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_token_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_token_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_token_3_backstop__n3_0_.png
Labels: 0.8.0, design review changes

#816 fix: update Side Navigation - Utility section separator padding
  src/side-nav.scss
  test/visual-regression-tests/reference_images/FS_side-nav_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_side-nav_1_backstop__n1_0_.png
Labels: 0.8.0, design review changes

#823 fix: add border to the selected state in borderless design and fix outline-offset issue in IE11
  docs/pages/components/list.md
  src/list.scss
  test/visual-regression-tests/reference_images/FS_list_6_backstop__n6_0_.png
Labels: 0.8.0, design review changes

#808 fix: introduce new component Message Box
  docs/_data/components.yml
  docs/_data/sidebars/left-navigation-sidebar.yml
  docs/_sass/_docs-display-component.scss
  docs/images/component-visual/message-box.png
  docs/pages/components/dialog.md
  docs/pages/components/message-box.md
  src/_dialog-placeholders.scss
  src/dialog.scss
  src/fundamental-styles.scss
  src/message-box.scss
  test/resources/layout.css
  test/templates/dialog/component.njk
  test/templates/index.njk
  test/templates/message-box/index.njk
  test/visual-regression-tests/reference_images/FS_dialog_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_dialog_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_dialog_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_dialog_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_dialog_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_dialog_5_backstop__n5_0_.png
  test/visual-regression-tests/reference_images/FS_dialog_6_backstop__n6_0_.png
  test/visual-regression-tests/reference_images/FS_dialog_7_backstop__n7_0_.png
  test/visual-regression-tests/reference_images/FS_message-box_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_message-box_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_message-box_2_backstop__n2_0_.png
Labels: 0.8.0, Fiori 3 New Component

#811 fix: fixing size of button's icon
  src/button.scss
  test/visual-regression-tests/reference_images/FS_button_0_backstop_0_.png
  test/visual-regression-tests/reference_images/FS_button_1_backstop__n1_0_.png
  test/visual-regression-tests/reference_images/FS_button_2_backstop__n2_0_.png
  test/visual-regression-tests/reference_images/FS_button_3_backstop__n3_0_.png
  test/visual-regression-tests/reference_images/FS_button_4_backstop__n4_0_.png
  test/visual-regression-tests/reference_images/FS_button_5_backstop__n5_0_.png
  test/visual-regression-tests/reference_images/FS_button_6_backstop__n6_0_.png
Labels: 0.8.0
