Repository SAP/fundamental-styles, pull requests merged in 2021-05, with the labels that each got.

#2274 feat: avatar - add option to set background size contain
  src/avatar.scss
  stories/avatar/__snapshots__/avatar.stories.storyshot
  stories/avatar/avatar.stories.js
Labels: denoland

#2320 chore: revert the react version
  package-lock.json
  package.json
Labels: Dependencies

#2272 fix: cleanup unused classes in Notifications and minor code refactoring
  src/notification.scss
  stories/notification/__snapshots__/notification.stories.storyshot
  stories/notification/notification.stories.js
Labels: denoland

#2317 chore: remove unneeded icon import
  src/rating-indicator.scss
  src/resizable-card-layout.scss
  src/status-indicator.scss
Labels: Bug

#2297 fix: Carousel - add shadow for hover state for controls [ci visual]
  src/carousel.scss
Labels: Bug, denoland

#2296 fix: Avatar group - do not overlay outer shadow with inner component's shadow [ci visual]
  src/popover.scss
  stories/popover/__snapshots__/popover.stories.storyshot
  stories/popover/popover.stories.js
Labels: Bug, denoland

#2324 fix: Wizard - change styling priorities in order to apply correct styles for stacked steps
  src/wizard.scss
  stories/wizard/__snapshots__/wizard.stories.storyshot
  stories/wizard/wizard.stories.js
Labels: Bug, denoland

#2326 feat: introduce Fixed Card Layout component
  src/fixed-card-layout.scss
  src/fundamental-styles.scss
  stories/fixed-card-layout/__snapshots__/fixed-card-layout.stories.storyshot
  stories/fixed-card-layout/fixed-card-layout.stories.js
Labels: Fiori 3 New Component

#2340 chore: security scans
  .github/workflows/codeql-analysis.yml
Labels: security, tooling

#2342 chore: fix security issue
  package-lock.json
Labels: Dependencies, security

#2351 chore: update npm testing commands for windows
  package.json
Labels: tooling

#2349 feat: introduce Vertical Navigation component
  .storybook/static/preview-head.js
  config/bundlesize.json
  package-lock.json
  src/_listDefinitions.scss
  src/_listNavigationItem.scss
  src/_listNavigationItemIndication.scss
  src/_nested-list.scss
  src/fundamental-styles.scss
  src/list.scss
  src/mixins/_mixins.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
  src/vertical-nav.scss
  stories/side-navigation/side-navigation.stories.js
  stories/vertical-navigation/__snapshots__/vertical-navigation.stories.storyshot
  stories/vertical-navigation/vertical-navigation.stories.js
Labels: Fiori 3 New Component

#2339 feat: add Extended Busy Indicator
  src/busy-indicator.scss
  stories/busy-indicator/__snapshots__/busy-indicator.stories.storyshot
  stories/busy-indicator/busy-indicator.stories.js
Labels: Bug

#2380 chore: update commitlint rules
  commitlint.config.js
Labels: tooling

#2361 fix: class added for no outer border for table
  src/table.scss
  stories/table/__snapshots__/table.stories.storyshot
  stories/table/table.stories.js
Labels: Bug

#2381 docs: fix doc site for IE11
  .storybook/static/preview-head.js
  package-lock.json
  package.json
  scripts/build-accessibility-tests.js
Labels: Doc website, IE11

#2370 fix: Slider - fix ticks for windows [ci visual]
  src/slider.scss
Labels: Bug, ariba

#2367 fix: removal of extra margin on the labelled status indicator
  src/status-indicator.scss
  stories/status-indicator/__snapshots__/status-indicator.stories.storyshot
  stories/status-indicator/status-indicator.stories.js
Labels: Bug

#2383 fix: add focused state for buttons in input-groups
  src/input-group.scss
Labels: Bug
