Repository SAP/fundamental-styles, pull requests merged in 2021-03, with the labels that each got.

#2077 feat: introduce Facets- Form, Key-value, Image, and Rating Indicator
  src/dynamic-page.scss
  src/facet.scss
  src/fundamental-styles.scss
  src/object-number.scss
  stories/dynamic-page/__snapshots__/dynamic-page.stories.storyshot
  stories/dynamic-page/dynamic-page.stories.js
  stories/facets/__snapshots__/facets.stories.storyshot
  stories/facets/facets.stories.js
Labels: ariba

#2176 fix: center message toast text [ci visual]
  src/message-toast.scss
Labels: Fiori 3 refactoring

#2177 docs: update README badges
  README.md
Labels: Doc website

#2179 fix: add alignment and focus related fixes for Shellbar
  src/product-switch.scss
  src/shellbar.scss
  stories/shellbar/__snapshots__/shellbar.stories.storyshot
  stories/shellbar/shellbar.stories.js
Labels: dxp

#2186 fix: components in active table rows
  src/table.scss
  stories/table/__snapshots__/table.stories.storyshot
  stories/table/table.stories.js
Labels: Fiori 3 refactoring

#2187 docs: fix README typo
  README.md
Labels: Doc website

#2189 fix: add fix for button cutting on hover for Flexible Column Layout
  src/flexible-column-layout.scss
Labels: dxp

#2169 fix: migrate storybook to v.6.1.21 [ci visual]
  package-lock.json
  package.json
  stories/avatar-group/__snapshots__/avatar-group.stories.storyshot
  stories/avatar-group/avatar-group.stories.js
  stories/avatar/__snapshots__/avatar.stories.storyshot
  stories/avatar/avatar.stories.js
  stories/bar/__snapshots__/bar.stories.storyshot
  stories/bar/bar.stories.js
  stories/card/__snapshots__/card.stories.storyshot
  stories/card/card.stories.js
  stories/generic-tile/__snapshots__/generic-tile.stories.storyshot
  stories/generic-tile/generic-tile.stories.js
  stories/notification/__snapshots__/notification.stories.storyshot
  stories/notification/notification.stories.js
  stories/popover/__snapshots__/popover.stories.storyshot
  stories/popover/popover.stories.js
  stories/resizable-card-layout/__snapshots__/resizable-card-layout.stories.storyshot
  stories/resizable-card-layout/resizable-card-layout.stories.js
  stories/select/__snapshots__/select.stories.storyshot
  stories/select/select.stories.js
Labels: A11y, Dependencies, Testing Framework

#2190 docs: update optimized favicon
  .storybook/static/favicon.ico
Labels: Doc website

#2188 fix: add fix for Dynamic Page title alignment issues
  src/dynamic-page.scss
Labels: dxp

#2197 chore: bump node to version 15.11.0
  .nvmrc
Labels: Dependencies

#2195 fix: pagination colors
  src/pagination.scss
Labels: winter 2020

#2192 feat: Add no-data, remove borders from responsive mode
  src/table.scss
  stories/table/__snapshots__/table.stories.storyshot
  stories/table/table.stories.js
Labels: dxp

#2203 chore: bump node version to 15.11.0 for netlify
  netlify.toml
Labels: tooling

#2196 fix: toolbar button not having any margin
  src/toolbar.scss
Labels: winter 2020

#2204 fix: change the naming of status indicator classes to follow BEM
  src/status-indicator.scss
  stories/status-indicator/__snapshots__/status-indicator.stories.storyshot
  stories/status-indicator/status-indicator.stories.js
Labels: Bug

#2216 chore: upgrade to theming-base-content version 11.1.28
  package-lock.json
  package.json
Labels: Dependencies

#2214 fix: remove margin from Resizable-Card-Layout item
  .storybook/custom/custom.scss
  src/resizable-card-layout.scss
Labels: Fiori 3 refactoring

#2221 fix: Remove outline from radio button
  src/radio.scss
Labels: Defect Hunting
