Repository SAP/fundamental-styles, pull requests merged in 2021-11, with the labels that each got.

#2875 fix(styles): dark, hcb, hcw bundled CSS to contain the right colors
  src/styles/fundamental-styles.scss
  src/styles/variables.scss
Labels: Bug, Theming

#2879 fix(styles): add word break [ci visual]
  src/styles/list-grid.scss
Labels: Bug

#2883 fix(styles): empty icon tab bar
  src/styles/icon-tab-bar.scss
Labels: Bug

#2884 feat(styles): add horizon delta for Switch component
  src/styles/switch.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
Labels: Theming

#2880 fix: table - remove cell outline [ci visual]
  src/styles/table.scss
Labels: Bug

#2898 fix(styles): add padding for inline code [ci visual]
  src/styles/code.scss
Labels: dxp

#2888 feat(styles): button and segmented button horizon deltas
  .storybook/custom/custom.scss
  src/styles/button.scss
  src/styles/mixins/button/_attention.scss
  src/styles/mixins/button/_button-helper.scss
  src/styles/mixins/button/_emphasized.scss
  src/styles/mixins/button/_negative.scss
  src/styles/mixins/button/_positive.scss
  src/styles/mixins/button/_standard.scss
  src/styles/segmented-button.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
Labels: Enhancement, stale

#2886 feat: themeable scrollbar
  src/styles/scrollbar.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  stories/scrollbar/__snapshots__/scrollbar.stories.storyshot
  stories/scrollbar/scrollbar.stories.js
Labels: Enhancement, Fiori 3 New Feature, denoland

#2905 fix(styles): refactor checkbox to use a square not an icon for tristate
  src/styles/checkbox.scss
  src/styles/mixins/_forms.scss
  stories/checkbox/__snapshots__/checkbox.stories.storyshot
  stories/checkbox/checkbox.stories.js
Labels: denoland

#2911 fix(fn): inconsistent text field borders across zoom levels [ci visual]
  src/fn/fn-input.scss
Labels: fn components

#2909 test(styles): stop horizon visual regression
  scripts/build-visual-stories.js
Labels: Theming, tooling

#2903 feat: introduce Progress Indicator
  src/styles/progress-indicator.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  stories/progress-indicator/__snapshots__/progress-indicator.stories.storyshot
  stories/progress-indicator/progress-indicator.stories.js
Labels: Fiori 3 New Component, denoland

#2916 fix(fn): inconsistent selected item border in Select across zoom levels
  src/fn/fn-select.scss
Labels: fn components

#2912 fix(styles): pagination styles update
  src/styles/pagination.scss
  stories/pagination/__snapshots__/pagination.stories.storyshot
  stories/pagination/pagination.stories.js
  stories/table/__snapshots__/table.stories.storyshot
  stories/table/table.stories.js
Labels: Enhancement, denoland, dxp

#2907 fix: fix selection in menu styles
  src/styles/menu.scss
Labels: Enhancement

#2927 fix: select min-width
  src/styles/select.scss
Labels: Bug, Enhancement

#2930 fix(fn): add new color variables
  src/fn/_fn-new-variables.scss
  src/fn/_fn-settings.scss
Labels: Fiori Next

#2929 fix: fix correct label text placement [ci visual]
  src/styles/form-layout-grid.scss
Labels: Bug

#2932 fix(fn): update Button component to latest Fiori Next design
  src/fn/_fn-new-variables.scss
  src/fn/_fn-variables.scss
  src/fn/fn-button.scss
  src/fn/fn-checkbox.scss
  src/fn/fn-input.scss
  src/fn/fn-radio.scss
  src/fn/fn-search.scss
  src/fn/fn-segmented-button.scss
  src/fn/fn-select.scss
  src/fn/fn-switch.scss
  src/fn/fn-tabs.scss
  src/fn/fn-tag.scss
  src/fn/fundamental-next.scss
  stories/fn-button/__snapshots__/fn-button.stories.storyshot
  stories/fn-button/fn-button.stories.js
Labels: Fiori Next

#2933 docs(fn): update the documentation examples for FN Buttons
  stories/fn-button/__snapshots__/fn-button.stories.storyshot
  stories/fn-button/fn-button.stories.js
Labels: Fiori Next

#2934 fix(fn): update Switch to latest design [ci visual]
  src/fn/_fn-new-variables.scss
  src/fn/fn-switch.scss
Labels: Fiori Next

#2917 feat(styles): illustrated message
  src/styles/illustrated-message.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  stories/illustrated-message/__snapshots__/illustrated-message.stories.storyshot
  stories/illustrated-message/illustrated-message.stories.js
Labels: Enhancement

#2946 fix(fn): update the spacing between text and icon in FN Button
  src/fn/fn-button.scss
Labels: Fiori Next

#2948 fix(fn): update Radio and Checkbox to latest FN design [ci visual]
  src/fn/_fn-mixins.scss
  src/fn/_fn-new-variables.scss
  src/fn/fn-button.scss
  src/fn/fn-checkbox.scss
  src/fn/fn-fieldset.scss
  src/fn/fn-radio.scss
  src/fn/fundamental-next.scss
  stories/fn-toggles/__snapshots__/fn-toggles.stories.storyshot
  stories/fn-toggles/fn-toggles.stories.js
Labels: Fiori Next
