Repository SAP/fundamental-styles, pull requests merged in 2021-01, with the labels that each got.

#1979 docs: update form grid documentation
  stories/form-grid/__snapshots__/form-grid.stories.storyshot
  stories/form-grid/form-grid.stories.js
Labels: Doc website

#1986 docs: update form message documentation
  stories/form-message/form-message.stories.js
Labels: Doc website

#1996 fix: add delta theming for Forms
  src/form-message.scss
  src/mixins/_forms.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
Labels: Theming

#1967 docs: updated switch documentation
  stories/switch/__snapshots__/switch.stories.storyshot
  stories/switch/switch.stories.js
Labels: Doc website, denoland

#1997 feat: unread selection
  src/_listBase.scss
  stories/list/standard/__snapshots__/standard-list.stories.storyshot
  stories/list/standard/standard-list.stories.js
Labels: winter 2020

#1946 docs: updated table documentation
  stories/table/__snapshots__/table.stories.storyshot
  stories/table/table.stories.js
Labels: Doc website

#2010 fix: object status link focus
  src/object-status.scss
  stories/object-status/__snapshots__/object-status.stories.storyshot
  stories/object-status/object-status.stories.js
Labels: Bug

#2014 fix: Add theming to product switch
  src/product-switch.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
Labels: Theming, delta theming

#2015 fix: add delta theming for Combobox and Multi Input
  src/input-group.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
Labels: Theming, delta theming

#2028 fix: add delta theming for List
  src/_listBase.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
Labels: Theming, delta theming

#2018 fix: add delta theming for Link
  src/link.scss
  src/mixins/_mixins.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
Labels: Theming, delta theming

#2019 fix: add delta theming for Switch
  src/switch.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
Labels: Theming, delta theming

#2035 fix: unify delta theming variables naming
  src/_dialog-placeholders.scss
  src/flexible-column-layout.scss
  src/message-strip.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
Labels: Theming, delta theming

#2029 fix: add delta theming for Page
  src/page.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
Labels: Theming, delta theming

#2036 fix: add delta theming for Table
  src/table.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
Labels: Theming, delta theming

#2027 fix: add delta theming for Message Box
  src/message-box.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
Labels: Theming, delta theming

#2016 fix: add delta theming for Feed Input
  src/feed-input.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
Labels: Theming, delta theming

#1998 fix: checkbox label for required
  src/checkbox.scss
  stories/checkbox/__snapshots__/checkbox.stories.storyshot
  stories/checkbox/checkbox.stories.js
Labels: Bug

#2034 fix: add delta theming for Select
  src/select.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
Labels: Theming, delta theming

#2037 chore: bump bundlesize version
  package-lock.json
  package.json
Labels: Dependencies

#1975 fix: split button overflow
  src/button-split.scss
  stories/button/__snapshots__/button.stories.storyshot
  stories/button/button.stories.js
Labels: winter 2020

#2044 fix: fix Dynamic Page default scrollbar appearing in IE
  src/dynamic-page.scss
Labels: Bug, Defect Hunting, ariba

#2047 docs: Change example in checkbox field set
  stories/form-fieldset/__snapshots__/form-fieldset.stories.storyshot
  stories/form-fieldset/form-fieldset.stories.js
Labels: Defect Hunting

#2057 docs: add fix for missing box-shadow for Dialog in IE11
  .storybook/custom/custom.scss
Labels: Defect Hunting

#2056 docs: add fix for contextual menu not showing in Table example
  stories/table/__snapshots__/table.stories.storyshot
  stories/table/table.stories.js
Labels: Defect Hunting

#2055 docs: change the icon of the button showing/hiding the second level of Side Nav
  .storybook/static/preview-head.js
  stories/side-navigation/__snapshots__/side-navigation.stories.storyshot
  stories/side-navigation/side-navigation.stories.js
Labels: Defect Hunting

#2053 fix: change the cursor to pointer for MORE/LESS links in Feed List Item
  src/feed-list.scss
Labels: Defect Hunting

#2054 docs: button docs improvements
  .storybook/custom/custom.scss
  stories/button/__snapshots__/button.stories.storyshot
  stories/button/button.stories.js
Labels: Defect Hunting, Doc website

#2058 fix: put back button background color
  src/shellbar.scss
Labels: Bug, Defect Hunting

#2049 docs: center Dialog examples on IE11
  .storybook/custom/custom.scss
Labels: Defect Hunting

#2048 docs: multi input markup update
  stories/multi-combo-box/__snapshots__/multi-combo-box.stories.storyshot
  stories/multi-combo-box/multi-combo-box.stories.js
  stories/multi-input/__snapshots__/multi-input.stories.storyshot
  stories/multi-input/multi-input.stories.js
Labels: Defect Hunting

#2017 fix: add delta theming for Generic Tiles
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
  src/tile.scss
Labels: Theming, blocked, delta theming

#2059 chore: reduce chromatic theming tests
  scripts/build-visual-stories.js
Labels: Testing Framework, Visual Testing

#2062 fix: update semantic icons in object status and object list
  stories/object-list/__snapshots__/object-list.stories.storyshot
  stories/object-list/object-list.stories.js
  stories/object-status/__snapshots__/object-status.stories.storyshot
  stories/object-status/object-status.stories.js
Labels: Fiori 3 refactoring

#2064 docs: update buttons in compact bars
  stories/bar/__snapshots__/bar.stories.storyshot
  stories/bar/bar.stories.js
Labels: Doc website

#2069 fix: Quick View title gaps
  src/quick-view.scss
  stories/quick-view/__snapshots__/quick-view.stories.storyshot
  stories/quick-view/quick-view.stories.js
Labels: Bug

#2061 chore: update the rules for running chromatic in PRs
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/chromatic.yml
Labels: Testing Framework, Visual Testing

#2075 feat: button inside list
  src/_listBase.scss
  src/_listByline.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
  stories/list/byline/__snapshots__/byline-list.stories.storyshot
  stories/list/byline/byline-list.stories.js
  stories/list/standard/__snapshots__/standard-list.stories.storyshot
  stories/list/standard/standard-list.stories.js
Labels: Fiori 3 New Feature

#2066 feat: introduce Avatar Group component
  .storybook/custom/custom.scss
  src/avatar-group.scss
  src/avatar.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
  stories/avatar-group/__snapshots__/avatar-group.stories.storyshot
  stories/avatar-group/avatar-group.stories.js
Labels: Fiori 3 New Component

#2071 chore: update browserlist package version
  package-lock.json
Labels: Dependencies

#2084 feat: introduce expand example for the Text component
  src/text.scss
  stories/text/__snapshots__/text.stories.storyshot
  stories/text/text.stories.js
Labels: Enhancement

#2088 fix: add fix for Table text shadow and focus color
  src/_listDefinitions.scss
  src/table.scss
Labels: table
