Repository SAP/fundamental-styles, pull requests merged in 2021-09, with the labels that each got.

#2698 fix: focus indication provided for Inverted Link.
  src/mixins/_mixins.scss
  stories/link/__snapshots__/link.stories.storyshot
  stories/link/link.stories.js
Labels: A11y, ariba

#2712 chore: update storybook to version 6.3.8 [ci visual]
  package-lock.json
  package.json
Labels: Doc website, tooling, storybook

#2701 fix: introduce Flat Navigation, refactor Horizontal Navigation
  src/fundamental-styles.scss
  src/horizontal-navigation.scss
  src/icon-tab-bar.scss
  stories/horizontal-navigation/__snapshots__/horizontal-navigation.stories.storyshot
  stories/horizontal-navigation/horizontal-navigation.stories.js
  stories/icon-tab-bar/__snapshots__/icon-tab-bar.stories.storyshot
  stories/icon-tab-bar/icon-tab-bar.stories.js
Labels: Fiori 3 refactoring, BTP

#2718 fix: form layout grid, remove unnecessary styles
  src/form-layout-grid.scss
Labels: stale

#2717 fix: layout grid bug fixes, improvements, refactoring
  src/layout-grid.scss
  stories/layout-grid/__snapshots__/layout-grid.stories.storyshot
  stories/layout-grid/layout-grid.stories.js
Labels: Bug, layouts, stale

#2719 docs: remove rich text editor from storybook
  stories/rich-text-editor/__snapshots__/rich-text-editor.stories.storyshot
  stories/rich-text-editor/rich-text-editor.stories.js
Labels: storybook, stale

#2728 feat: introduce Micro Process Flow component
  src/fundamental-styles.scss
  src/micro-process-flow.scss
  src/mixins/_mixins.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
  stories/micro-process-flow/__snapshots__/micro-process-flow.stories.storyshot
  stories/micro-process-flow/micro-process-flow.stories.js
Labels: Fiori 3 New Component

#2735 fix: add focus style on clickable object marker
  src/object-marker.scss
  stories/object-marker/__snapshots__/object-marker.stories.storyshot
  stories/object-marker/object-marker.stories.js
Labels: Bug, A11y, QA approved, ready for merge

#2731 chore: update dependabot config
  .github/dependabot.yml
Labels: Dependencies

#2741 fix: fixes a bug where the nav item height could be incorrect
  src/_listNavigationItem.scss
  stories/vertical-navigation/__snapshots__/vertical-navigation.stories.storyshot
  stories/vertical-navigation/vertical-navigation.stories.js
Labels: Bug

#2751 fix: table condensed checkbox
  src/table.scss
Labels: Bug

#2755 feat: bring early version of horizon theme css variables
  .storybook/custom/components/Header.js
  .storybook/preview.js
  config/constants.js
  config/postcss-add-fallback.js
  src/theming/sap_horizon.scss
Labels: Theming

#2757 chore: update dependancies
  package-lock.json
  package.json
Labels: Dependencies
