Repository SAP/fundamental-styles, pull requests merged in 2021-04, with the labels that each got.

#2206 fix: bring back the vertical margin for Form Label in Toolbar
  src/toolbar.scss
Labels: winter 2020

#2215 feat: introduce Rich Text Editor component
  stories/rich-text-editor/__snapshots__/rich-text-editor.stories.storyshot
  stories/rich-text-editor/rich-text-editor.stories.js
Labels: Fiori 3 New Component, Fiori 3 refactoring

#2229 feat: introduce 2 new types of icons
  .storybook/custom/components/Header.js
  .storybook/preview-head.html
  README.md
  src/icon.scss
  src/icons/_settingsBusiness.scss
  src/icons/_settingsTNT.scss
  src/mixins/_icons.scss
  stories/icon/BusinessSuiteInAppSymbols/__snapshots__/iconBusinessSuite.stories.storyshot
  stories/icon/BusinessSuiteInAppSymbols/dataBusinessSuite.json
  stories/icon/BusinessSuiteInAppSymbols/iconBusinessSuite.stories.js
  stories/icon/SAPIcons/__snapshots__/icon.stories.storyshot
  stories/icon/SAPIcons/data.json
  stories/icon/SAPIcons/icon.stories.js
  stories/icon/TNTIcons/__snapshots__/iconTnt.stories.storyshot
  stories/icon/TNTIcons/dataTNT.json
  stories/icon/TNTIcons/iconTnt.stories.js
Labels: denoland

#2234 docs: update links to project configurations in Icons documentation
  stories/icon/BusinessSuiteInAppSymbols/iconBusinessSuite.stories.js
  stories/icon/SAPIcons/icon.stories.js
  stories/icon/TNTIcons/iconTnt.stories.js
Labels: Doc website

#2236 fix: move card styles from ngx to styles
  src/card.scss
  src/numeric-content.scss
Labels: Bug

#2247 chore: upgrade few package.json libraries' versions [ci visual]
  package-lock.json
  package.json
Labels: Dependencies

#2242 chore: cleanup redundant code for icons [ci visual]
  src/icon.scss
  src/mixins/_icons.scss
Labels: denoland

#2248 chore: migrate "add fallback plugin" and "remove font variables" to postCSS v.8
  config/postcss-add-fallback.js
  config/postcss-remove-fonts.js
Labels: denoland

#2250 chore: update package-lock.json
  package-lock.json
Labels: Dependencies, tooling

#2259 chore: update package-lock
  package-lock.json
Labels: Dependencies

#2260 fix: import object-number as part of the whole css file
  src/fundamental-styles.scss
Labels: Bug

#2225 chore: update node version to 15.11.0 for travis
  .travis.yml
Labels: tooling

#2237 feat: Introduce non fiori3 page footer component
  src/fundamental-styles.scss
  src/page-footer.scss
  stories/page-footer/__snapshots__/page-footer.stories.storyshot
  stories/page-footer/page-footer.stories.js
Labels: ariba

#2243 feat: introduce User Menu component
  src/badge.scss
  src/user-menu.scss
  stories/user-menu/__snapshots__/user-menu.stories.storyshot
  stories/user-menu/user-menu.stories.js
Labels: Fiori 3 New Component

#2270 chore: bump few library versions [ci visual]
  package-lock.json
  package.json
Labels: Dependencies

#2281 chore: bump minor lib versions
  .gitignore
  package-lock.json
  package.json
Labels: Dependencies

#2288 fix: add padding for user menu subheader
  src/user-menu.scss
Labels: Bug

#2303 chore: cleanup dependabot config
  .github/dependabot.yml
Labels: Dependencies, tooling

#2275 fix: Align borders properly for fixed columns
  src/table.scss
Labels: denoland

#2279 chore: introduce fd-expanded() mixin
  src/input.scss
  src/menu.scss
  src/mixins/_states.scss
  src/select.scss
  src/tabs.scss
  src/textarea.scss
  src/tree.scss
Labels: denoland

#2273 fix: avatar zoom icon issues
  src/avatar.scss
Labels: denoland

#2276 fix: vertically align close button for compact token
  src/token.scss
Labels: Bug, denoland

#2277 fix: checkbox make square smaller in order for browser to evenly move it from the center
  src/checkbox.scss
Labels: denoland
