Repository SAP/fundamental-styles, pull requests merged in 2021-07, with the labels that each got.

#2480 fix: provide padding if title is first element in bar
  src/bar.scss
  stories/bar/__snapshots__/bar.stories.storyshot
  stories/bar/bar.stories.js
Labels: Bug

#2481 docs: create theming preview sample pages
  theming-preview/README.md
  theming-preview/button.html
  theming-preview/calendar.html
  theming-preview/form.html
  theming-preview/header-footer.html
  theming-preview/icon.html
  theming-preview/index.html
  theming-preview/indication-colors.html
  theming-preview/input.html
  theming-preview/object-header.html
  theming-preview/panel.html
  theming-preview/semantic-colors.html
  theming-preview/shell-tile-card.html
  theming-preview/table.html
  theming-preview/test-file.html
  theming-preview/testsuite.json
  theming-preview/text.html
  theming-preview/toolbar.html
Labels: Theming

#2527 feat: introduce qr-code icon
  src/icons/_settings.scss
  stories/icon/SAPIcons/__snapshots__/icon.stories.storyshot
  stories/icon/SAPIcons/data.json
Labels: Fiori 3 New Feature

#2529 fix: update toolbar styling
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
  src/toolbar.scss
  stories/toolbar/__snapshots__/toolbar.stories.storyshot
  stories/toolbar/toolbar.stories.js
Labels: delta theming

#2544 fix: correct position for rtl icons for alert component
  src/alert.scss
Labels: Bug, denoland-porto

#2545 docs: correct fieldset css file name
  stories/form-fieldset/form-fieldset.stories.js
Labels: Bug, denoland-porto

#2547 fix: update border width for combobox button
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
Labels: Bug, denoland-porto

#2552 fix: added additional panding for slider [ci visual]
  src/slider.scss
Labels: denoland-porto

#2551 fix: box-sizing of wizard step in progress bar [ci visual]
  src/wizard.scss
Labels: Bug

#2549 fix: table fixed column borders fix, table improvements
  src/table.scss
  stories/table/__snapshots__/table.stories.storyshot
  stories/table/table.stories.js
Labels: Bug, Enhancement, ariba, table

#2540 fix: refactor bar documentation as suggested
  stories/bar/__snapshots__/bar.stories.storyshot
  stories/bar/bar.stories.js
Labels: ready for qa

#2555 fix: popover outline focus-visible
  src/popover.scss
Labels: Bug

#2550 feat: introduce Tool Header component from BTP design
  .storybook/custom/components/tags.json
  src/fundamental-styles.scss
  src/icon-tab-bar.scss
  src/mixins/_mixins.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
  src/tool-header.scss
  stories/tool-header/__snapshots__/tool-header.stories.storyshot
  stories/tool-header/tool-header.stories.js
  stories/vertical-navigation/vertical-navigation.stories.js
Labels: BTP, denoland

#2556 feat: introduce navigation for IconTabBar
  src/icon-tab-bar.scss
  stories/icon-tab-bar/__snapshots__/icon-tab-bar.stories.storyshot
  stories/icon-tab-bar/icon-tab-bar.stories.js
Labels: BTP, denoland

#2557 fix: remove line height to avoid List item title from getting cut
  src/_listBase.scss
Labels: Bug

#2572 fix: adding placeholder color and adding rtl to the button
  src/feed-input.scss
Labels: Defect Hunting, ariba, ready for qa

#2581 docs: update textarea validation messages
  stories/textarea/__snapshots__/textarea.stories.storyshot
  stories/textarea/textarea.stories.js
Labels: Doc website

#2582 docs: add missing class to inactive list item example [ci visual]
  stories/list/standard/__snapshots__/standard-list.stories.storyshot
  stories/list/standard/standard-list.stories.js
Labels: Doc website

#2587 fix: add fix for Card header focus offset
  src/card.scss
Labels: denoland-porto

#2588 docs: add fixed container size for Calendar in portrait mode
  stories/calendar/__snapshots__/calendar.stories.storyshot
  stories/calendar/calendar.stories.js
Labels: denoland-porto

#2590 fix: add fix for correct height of Grid List actions
  src/toolbar.scss
Labels: denoland-porto

#2591 fix: center tristate icon horizontally
  src/checkbox.scss
Labels: denoland-porto

#2573 fix: add active state background color for object list as per spec
  .storybook/static/preview-head.js
  src/_listDefinitions.scss
  src/object-list.scss
  stories/object-list/__snapshots__/object-list.stories.storyshot
  stories/object-list/object-list.stories.js
Labels: Defect Hunting, QA approved

#2595 fix: remove word-break from fixed-card-layout, leaking outside to other components
  src/fixed-card-layout.scss
Labels: Bug

#2596 fix: add missing features for Vertical Navigation
  src/_listNavigationItem.scss
  src/vertical-nav.scss
  stories/vertical-navigation/__snapshots__/vertical-navigation.stories.storyshot
  stories/vertical-navigation/vertical-navigation.stories.js
Labels: denoland-porto

#2597 fix: add focus to focusable disabled button
  config/bundlesize.json
  src/button.scss
Labels: denoland-porto

#2598 fix: remove code breaking documentation functionality and tristate for checkboxes
  .storybook/static/preview-head.js
Labels: Doc website

#2599 fix: add fix for RTL Object List Item With Row Selection And Navigation
  src/_listNavigation.scss
Labels: RTL, denoland-porto

#2600 feat: introduce Horizontal Navigation pattern
  src/icon-tab-bar.scss
  src/tool-header.scss
  stories/horizontal-navigation/__snapshots__/horizontal-navigation.stories.storyshot
  stories/horizontal-navigation/horizontal-navigation.stories.js
  stories/icon-tab-bar/__snapshots__/icon-tab-bar.stories.storyshot
  stories/icon-tab-bar/icon-tab-bar.stories.js
Labels: BTP

#2620 chore: trigger chromatic when pushing to main
  .github/workflows/chromatic.yml
Labels: Bug
