Repository SAP/fundamental-styles, pull requests merged in 2021-12, with the labels that each got.

#2984 feat(fn): introduce Generic Tag component
  src/fn/_fn-mixins.scss
  src/fn/_fn-new-variables.scss
  src/fn/fn-generic-tag.scss
  stories/fn-generic-tag/__snapshots__/fn-generic-tag.stories.storyshot
  stories/fn-generic-tag/fn-generic-tag.stories.js
Labels: Fiori Next

#2947 fix(styles): fix issues with progress indicator overflow text wrapping [ci visual]
  src/styles/progress-indicator.scss
  stories/progress-indicator/progress-indicator.stories.js
Labels: Bug

#2960 fix(fn): refactor Input fields to latest FN design
  src/fn/_fn-mixins.scss
  src/fn/_fn-new-variables.scss
  src/fn/_fn-variables.scss
  src/fn/fn-input.scss
  src/fn/fn-nested-button.scss
  src/fn/fn-search.scss
  src/fn/fn-select.scss
  src/fn/fundamental-next.scss
  stories/fn-button/__snapshots__/fn-button.stories.storyshot
  stories/fn-button/fn-button.stories.js
  stories/fn-input/__snapshots__/fn-input.stories.storyshot
  stories/fn-input/fn-input.stories.js
  stories/fn-search/__snapshots__/fn-search.stories.storyshot
  stories/fn-search/fn-search.stories.js
  stories/fn-select/__snapshots__/fn-select.stories.storyshot
  stories/fn-select/fn-select.stories.js
Labels: stale, Fiori Next

#2959 feat(fn): introduce dialog, message-box, link, title [ci visual]
  .storybook/preview-head.html
  README.md
  src/fn/_dialog-placeholders.scss
  src/fn/_fn-mixins.scss
  src/fn/_fn-new-variables.scss
  src/fn/fn-dialog.scss
  src/fn/fn-link.scss
  src/fn/fn-message-box.scss
  src/fn/fn-title.scss
  stories/fn-dialog/__snapshots__/fn-dialog.stories.storyshot
  stories/fn-dialog/fn-dialog.stories.js
  stories/fn-link/__snapshots__/fn-link.stories.storyshot
  stories/fn-link/fn-link.stories.js
  stories/fn-message-box/__snapshots__/fn-message-box.stories.storyshot
  stories/fn-message-box/fn-message-box.stories.js
  stories/fn-title/__snapshots__/title.stories.storyshot
  stories/fn-title/title.stories.js
  theming-preview/theme-manager.js
Labels: Fiori Next

#2972 fix: rating-indicator styles [ci visual]
  src/styles/rating-indicator.scss
  stories/rating-indicator/__snapshots__/rating-indicator.stories.storyshot
  stories/rating-indicator/rating-indicator.stories.js
Labels: Bug

#2983 feat(fn): refactor Slider and introduce Range Slider and Progress Bar
  src/fn/_fn-new-variables.scss
  src/fn/fn-progress-bar.scss
  src/fn/fn-slider.scss
  src/fn/fundamental-next.scss
  stories/fn-progress-bar/__snapshots__/fn-progress-bar.stories.storyshot
  stories/fn-progress-bar/fn-progress-bar.stories.js
  stories/fn-slider/__snapshots__/fn-slider.stories.storyshot
  stories/fn-slider/fn-slider.stories.js
Labels: stale, Fiori Next

#2998 fix(fn): add fix for Link states and docs improvements for Title
  src/fn/_fn-new-variables.scss
  src/fn/fn-link.scss
  stories/fn-link/__snapshots__/fn-link.stories.storyshot
  stories/fn-link/fn-link.stories.js
  stories/fn-title/__snapshots__/title.stories.storyshot
  stories/fn-title/title.stories.js
Labels: Fiori Next

#3003 chore(styles): bring hotfix script
  .ci-env/flags.sh
  .ci-env/flags.sh-e
  .travis.yml
  ci-scripts/hotfix-publish.sh
  package.json
  scripts/hotfix-publish-release.sh
Labels: tooling

#3005 feat(fn): introduce Avatar component
  src/fn/fn-avatar.scss
  src/fn/fundamental-next.scss
  stories/fn-avatar/__snapshots__/fn-avatar.stories.storyshot
  stories/fn-avatar/fn-avatar.stories.js
Labels: Fiori Next

#3009 fix: remove active page link when in long mode
  src/styles/pagination.scss
Labels: Enhancement

#3010 fix(fn): include missing components from fundamental-next.css
  src/fn/fundamental-next.scss
Labels: Fiori Next

#3007 fix(styles): use the theming variable for focus style
  src/styles/carousel.scss
  src/styles/mixins/button/_button-helper.scss
  src/styles/popover.scss
  src/styles/slider.scss
  src/styles/tree.scss
Labels: Theming

#3025 docs(styles,fn): update Icon link and slack link
  README.md
Labels: tooling, documentation

#3027 docs(styles,fn): minor README.md update
  README.md
Labels: documentation

#3031 fix: chromatic [ci visual]
  .github/workflows/chromatic.yml
  package-lock.json
Labels: Bug

#3032 docs(styles,fn): fix storybook site
  package-lock.json
Labels: storybook, documentation

#3012 fix(fn): refactor Tabs component
  src/fn/_fn-mixins.scss
  src/fn/fn-nested-button.scss
  src/fn/fn-tabs.scss
  stories/fn-tabs/__snapshots__/fn-tabs.stories.storyshot
  stories/fn-tabs/fn-tabs.stories.js
Labels: Fiori Next

#3034 test(fn): exclude fn-tabs from a11y tests
  scripts/build-accessibility-tests.js
  stories/fn-tabs/__snapshots__/fn-tabs.stories.storyshot
Labels: A11y, Fiori Next
