Repository SAP/fundamental-styles, pull requests merged in 2021-02, with the labels that each got.

#2103 docs: add Attachment list example to the documentation
  stories/list/byline/__snapshots__/byline-list.stories.storyshot
  stories/list/byline/byline-list.stories.js
Labels: Doc website

#2094 fix: positioning of overflowed shellbar notification counter
  src/shellbar.scss
  stories/shellbar/__snapshots__/shellbar.stories.storyshot
  stories/shellbar/shellbar.stories.js
Labels: Bug

#2096 fix: add z-index to floating footer bar
  src/bar.scss
Labels: Bug

#2098 fix: Step Input focus within
  src/mixins/_states.scss
  src/step-input.scss
Labels: Defect Hunting

#2112 chore: bump theme-base-content to 11.1.26 [ci visual]
  package-lock.json
  package.json
Labels: Dependencies, Theming

#2114 chore: improve chromatic to run dependabot PRs
  .github/workflows/chromatic.yml
Labels: Testing Framework, Visual Testing

#2099 feat: add busy state to the Action List
  src/_listBase.scss
  src/_listDefinitions.scss
  stories/list/standard/__snapshots__/standard-list.stories.storyshot
  stories/list/standard/standard-list.stories.js
Labels: Enhancement

#2072 feat: introduce status indicator component
  .storybook/custom/custom.scss
  .storybook/static/assets/images/status_indicator/bulb.svg
  .storybook/static/assets/images/status_indicator/cart.svg
  .storybook/static/assets/images/status_indicator/cereals.svg
  .storybook/static/assets/images/status_indicator/drop.svg
  .storybook/static/assets/images/status_indicator/euro.svg
  .storybook/static/assets/images/status_indicator/factory.svg
  .storybook/static/assets/images/status_indicator/heart.svg
  .storybook/static/assets/images/status_indicator/lung.svg
  .storybook/static/assets/images/status_indicator/plane.svg
  .storybook/static/assets/images/status_indicator/stomach.svg
  .storybook/static/assets/images/status_indicator/transfusion.svg
  .storybook/static/assets/images/status_indicator/turnip.svg
  .storybook/static/assets/images/status_indicator/vehicle_truck_1.svg
  .storybook/static/assets/images/status_indicator/vehicle_truck_3.svg
  src/status-indicator.scss
  stories/status-indicator/__snapshots__/status-indicator.stories.storyshot
  stories/status-indicator/status-indicator.stories.js
Labels: Fiori 3 New Component

#2118 fix: wizard - all stacked steps last:children should have padding-right
  src/wizard.scss
Labels: Bug

#2123 fix: remove font-smoothing #2100
  .storybook/custom/custom.scss
  src/mixins/_icons.scss
  src/mixins/_mixins.scss
Labels: Bug

#2113 feat: Add non-interactive state to card header
  src/card.scss
  stories/card/__snapshots__/card.stories.storyshot
  stories/card/card.stories.js
Labels: Enhancement

#2074 fix: byline list improvements
  src/_listByline.scss
  src/_listDefinitions.scss
  stories/list/byline/__snapshots__/byline-list.stories.storyshot
  stories/list/byline/byline-list.stories.js
Labels: Bug

#2115 fix: grid list styles
  src/list-grid.scss
Labels: Bug, Defect Hunting

#2127 docs: centered Quick View title
  stories/quick-view/__snapshots__/quick-view.stories.storyshot
  stories/quick-view/quick-view.stories.js
Labels: Defect Hunting

#2134 docs: add missing imports for Form Grid
  stories/form-grid/form-grid.stories.js
Labels: Defect Hunting

#2129 fix: add fix for IE related issues in Tiles
  src/tile.scss
Labels: Defect Hunting

#2124 fix: add fix for hover state in selected mode
  src/_listDefinitions.scss
Labels: denoland

#2135 docs: action bar popover needs to be right aligned
  stories/action-bar/__snapshots__/action-bar.stories.storyshot
  stories/action-bar/action-bar.stories.js
Labels: Doc website

#2133 docs: Add input import to tokenizer docs
  stories/token/token.stories.js
Labels: Defect Hunting

#2132 fix: Change height of title and solve counter issues on byline
  src/_listByline.scss
Labels: Defect Hunting

#2136 docs: cozy bar footer needs cozy buttons
  stories/bar/__snapshots__/bar.stories.storyshot
  stories/bar/bar.stories.js
Labels: Doc website

#2138 docs: updates to notification group docs
  stories/notification/__snapshots__/notification.stories.storyshot
  stories/notification/notification.stories.js
Labels: Doc website

#2143 fix: fix Grid List styles
  src/list-grid.scss
  stories/list-grid/__snapshots__/list-grid.stories.storyshot
  stories/list-grid/list-grid.stories.js
Labels: Bug, Defect Hunting

#2137 docs: import link on message page
  stories/message-page/message-page.stories.js
Labels: Doc website

#2141 docs: tristate checkboxes indeterminate on load
  .storybook/static/preview-head.js
  stories/checkbox/checkbox.stories.js
Labels: Doc website

#2130 feat: add modifier class for List being used in a dialog in mobile mode
  src/_listDropdown.scss
  stories/combobox-input/__snapshots__/combobox-input.stories.storyshot
  stories/combobox-input/combobox-input.stories.js
  stories/multi-combo-box/__snapshots__/multi-combo-box.stories.storyshot
  stories/multi-combo-box/multi-combo-box.stories.js
  stories/multi-input/__snapshots__/multi-input.stories.storyshot
  stories/multi-input/multi-input.stories.js
  stories/select/__snapshots__/select.stories.storyshot
  stories/select/select.stories.js
Labels: Defect Hunting, Enhancement

#2142 docs: add examples with light and bold 72 fonts
  README.md
Labels: Doc website

#2140 docs: remove radio readonly examples
  stories/radio/__snapshots__/radio.stories.storyshot
  stories/radio/radio.stories.js
Labels: Doc website

#2139 docs: add some variation to object list docs
  stories/object-list/__snapshots__/object-list.stories.storyshot
  stories/object-list/object-list.stories.js
Labels: Doc website

#2149 chore: update package-lock.json
  package-lock.json
Labels: Dependencies

#2147 chore: bump standard-version 9.1.0
  package-lock.json
  package.json
Labels: Dependencies

#2155 docs: update checkbox ids in multi combo docs
  .storybook/static/preview-head.js
  stories/multi-combo-box/__snapshots__/multi-combo-box.stories.storyshot
  stories/multi-combo-box/multi-combo-box.stories.js
Labels: Doc website

#2156 docs: revert notification group docs update
  stories/notification/__snapshots__/notification.stories.storyshot
  stories/notification/notification.stories.js
Labels: Bug, Doc website

#2144 fix: remove border-bottom radius from mult-input list items
  src/_listDropdown.scss
Labels: Bug

#2150 fix: add proper alignment for the text inside Split button
  src/button-split.scss
Labels: Defect Hunting

#2092 feat: Introduce resizable card layout
  .storybook/custom/custom.scss
  src/resizable-card-layout.scss
  stories/resizable-card-layout/__snapshots__/resizable-card-layout.stories.storyshot
  stories/resizable-card-layout/resizable-card-layout.stories.js
Labels: Enhancement, Fiori 3 New Component, core

#2154 fix: simplify dynamic page
  src/dynamic-page.scss
  stories/dynamic-page/__snapshots__/dynamic-page.stories.storyshot
  stories/dynamic-page/dynamic-page.stories.js
Labels: Fiori 3 refactoring

#2131 feat: introduce Margins and Paddings
  .storybook/custom/custom.scss
  src/fundamental-styles.scss
  src/margins.scss
  src/paddings.scss
  stories/margins/__snapshots__/margins.stories.storyshot
  stories/margins/margins.stories.js
  stories/paddings/__snapshots__/paddings.stories.storyshot
  stories/paddings/paddings.stories.js
Labels: Fiori 3 New Component

#2159 docs: update grid list images with a local one
  .storybook/custom/custom.scss
  .storybook/static/assets/images/backgrounds/leaves.jpg
Labels: Doc website

#2157 fix: update table navigation icons and states
  src/table.scss
  stories/table/__snapshots__/table.stories.storyshot
  stories/table/table.stories.js
Labels: Bug, Doc website, table

#2121 feat: Avatar Group overflow spacing and overflow button border color
  .storybook/custom/custom.scss
  src/avatar-group.scss
  stories/avatar-group/__snapshots__/avatar-group.stories.storyshot
  stories/avatar-group/avatar-group.stories.js
Labels: Enhancement

#2162 fix: Semantic tabs color
  src/tabs.scss
Labels: Defect Hunting

#2167 chore: update package.json and package-lock.json files
  package-lock.json
  package.json
Labels: Dependencies

#2168 fix: update object status large font-family [ci visual]
  src/object-status.scss
Labels: Fiori 3 refactoring, denoland

#2165 chore: bump theming-base-content to version 11.1.27
  package-lock.json
  package.json
Labels: Dependencies

#2166 chore: bump minor package lib version
  package-lock.json
  package.json
Labels: Dependencies
