Repository SAP/fundamental-styles, pull requests merged in 2021-06, with the labels that each got.

#2409 chore: bump node version to 14.17.0 for netlify
  .nvmrc
  netlify.toml
Labels: Dependencies

#2408 chore: update commitlint, changelog
  ci-scripts/publish-rc.sh
  ci-scripts/publish.sh
  commitlint.config.js
  package-lock.json
  package.json
Labels: Enhancement

#2384 fix: table fixed (freeze) column border fix
  src/table.scss
  stories/table/__snapshots__/table.stories.storyshot
  stories/table/table.stories.js
Labels: Bug, QA approved, table

#2414 chore: fix version release
  ci-scripts/publish.sh
  package.json
Labels: tooling

#2439 chore: update bump version
  ci-scripts/publish-rc.sh
  ci-scripts/publish.sh
  package-lock.json
  package.json
Labels: tooling

#2371 fix: form grid aligns items vertically to the top
  src/form-layout-grid.scss
  stories/form-grid/__snapshots__/form-grid.stories.storyshot
  stories/form-grid/form-grid.stories.js
Labels: Bug, QA approved

#2445 chore(deps-dev): add in-solidarity
  .github/in-solidarity.yml
Labels: tooling

#2454 fix: provide focus for avatar and icon components
  src/avatar.scss
  src/icon.scss
  src/mixins/_states.scss
  stories/avatar/__snapshots__/avatar.stories.storyshot
  stories/avatar/avatar.stories.js
  stories/icon/SAPIcons/__snapshots__/icon.stories.storyshot
  stories/icon/SAPIcons/icon.stories.js
Labels: A11y, Bug, QA approved, ready for merge

#2458 chore: remove old unused code
  src/_col.scss
  src/_mixins.scss
  src/mixins/_layouts.scss
  src/mixins/_mixins.scss
Labels: denoland

#2459 fix: bring charset at the beginning of the css files
  config/postcss.config.js
  package-lock.json
  package.json
Labels: tooling

#2463 chore: update to latest version of sap-theming
  .storybook/preview-head.html
  README.md
  package-lock.json
  package.json
Labels: Dependencies

#2455 feat: introduce new Icon Tab Bar component
  config/bundlesize.json
  src/_listNavigationItem.scss
  src/fundamental-styles.scss
  src/icon-tab-bar.scss
  src/mixins/_mixins.scss
  src/theming/sap_fiori_3.scss
  src/theming/sap_fiori_3_dark.scss
  src/theming/sap_fiori_3_hcb.scss
  src/theming/sap_fiori_3_hcw.scss
  src/theming/sap_fiori_3_light_dark.scss
  src/vertical-nav.scss
  stories/icon-tab-bar/__snapshots__/icon-tab-bar.stories.storyshot
  stories/icon-tab-bar/icon-tab-bar.stories.js
Labels: Fiori 3 New Component

#2464 chore: introduce stale workflow
  .github/workflows/stale.yml
Labels: tooling

#2474 chore: prepare the repo for theming-preview package [ci visual]
  .gitignore
  ci-scripts/publish-rc.sh
  ci-scripts/publish.sh
  ci-scripts/sync-version.sh
  package-lock.json
  package.json
  theming-preview/index.html
  theming-preview/package.json
  theming-preview/testsuite.json
Labels: Theming, tooling

#2475 chore: fix publish script
  ci-scripts/publish-rc.sh
  ci-scripts/publish.sh
Labels: Bug, tooling

#2431 fix: show navigation button on hover in carousel content area, carousel component css moved from ngx
  src/carousel.scss
  stories/carousel/__snapshots__/carousel.stories.storyshot
  stories/carousel/carousel.stories.js
Labels: Bug, stale

#2484 chore: fix the build command
  package.json
Labels: tooling

#2478 feat: create component to place an element off screen
  src/fundamental-styles.scss
  src/off-screen.scss
  stories/off-screen/__snapshots__/off-screen.stories.storyshot
  stories/off-screen/off-screen.stories.js
Labels: A11y

#2483 fix: add bottom border to panel content
  src/panel.scss
Labels: Bug

#2506 chore: import missing components in fundamental-styles.css
  src/fundamental-styles.scss
Labels: Bug

#2522 fix: update css selector for list item [ci visual]
  src/_listNavigationItem.scss
Labels: Bug

#2505 fix: rtl support for the grid list highlighter for status
  src/list-grid.scss
Labels: Bug, RTL, ariba

#2473 fix: change tabs styles for routerLink
  src/tabs.scss
Labels: Valor, ready for qa
