Repository SAP/fundamental-styles, pull requests merged in 2021-08, with the labels that each got.

#2614 feat: rating indicator non-interactive mode
  src/rating-indicator.scss
  stories/rating-indicator/__snapshots__/rating-indicator.stories.storyshot
  stories/rating-indicator/rating-indicator.stories.js
Labels: Enhancement, ariba

#2611 feat: implement upload collection
  src/fundamental-styles.scss
  src/upload-collection.scss
  stories/upload-collection/__snapshots__/upload-collection.stories.storyshot
  stories/upload-collection/upload-collection.stories.js
Labels: Enhancement, Fiori 3 New Component, Fiori 3 New Feature

#2636 chore: add style to theming preview files
  theming-preview/button.html
  theming-preview/calendar.html
  theming-preview/form.html
  theming-preview/header-footer.html
  theming-preview/icon.html
  theming-preview/indication-colors.html
  theming-preview/input.html
  theming-preview/object-header.html
  theming-preview/panel.html
  theming-preview/semantic-colors.html
  theming-preview/shell-tile-card.html
  theming-preview/table.html
  theming-preview/text.html
  theming-preview/toolbar.html
Labels: Theming

#2637 fix: update theming-preview package styling imports
  README.md
  package.json
  theming-preview/button.html
  theming-preview/calendar.html
  theming-preview/form.html
  theming-preview/header-footer.html
  theming-preview/icon.html
  theming-preview/indication-colors.html
  theming-preview/input.html
  theming-preview/object-header.html
  theming-preview/panel.html
  theming-preview/semantic-colors.html
  theming-preview/shell-tile-card.html
  theming-preview/table.html
  theming-preview/text.html
  theming-preview/toolbar.html
Labels: Theming

#2621 fix: introduce modifier class to fix nested-list-popover
  src/_nested-list.scss
  stories/side-navigation/__snapshots__/side-navigation.stories.storyshot
  stories/side-navigation/side-navigation.stories.js
Labels: ready for qa, ready for merge, Requested Changes 2

#2655 fix: add compact class
  src/form-layout-grid.scss
Labels: ready for merge

#2665 feat: table group rows, tree rows
  src/mixins/_mixins.scss
  src/table.scss
  stories/table/__snapshots__/table.stories.storyshot
  stories/table/table.stories.js
Labels: Enhancement, ariba

#2670 fix: add fonts dynamically for theming preview
  theming-preview/button.html
  theming-preview/calendar.html
  theming-preview/form.html
  theming-preview/header-footer.html
  theming-preview/icon.html
  theming-preview/indication-colors.html
  theming-preview/input.html
  theming-preview/object-header.html
  theming-preview/panel.html
  theming-preview/semantic-colors.html
  theming-preview/shell-tile-card.html
  theming-preview/table.html
  theming-preview/test-file.html
  theming-preview/text.html
  theming-preview/theme-manager.js
  theming-preview/toolbar.html
Labels: Theming

#2680 docs: update storybook version 6.3.7
  .github/dependabot.yml
  .storybook/custom/components/DocsPage.js
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  scripts/storybook-prep.js
  stories/action-bar/action-bar.stories.js
  stories/avatar-group/avatar-group.stories.js
  stories/avatar/avatar.stories.js
  stories/bar/bar.stories.js
  stories/breadcrumb/breadcrumb.stories.js
  stories/busy-indicator/busy-indicator.stories.js
  stories/button/button.stories.js
  stories/calendar/calendar.stories.js
  stories/card/card.stories.js
  stories/carousel/carousel.stories.js
  stories/checkbox/checkbox.stories.js
  stories/context-menu/context-menu.stories.js
  stories/counter/counter.stories.js
  stories/datepicker/datepicker.stories.js
  stories/dialog/dialog.stories.js
  stories/dynamic-page/dynamic-page.stories.js
  stories/facets/facets.stories.js
  stories/feed-list/feed-list.stories.js
  stories/flexible-column-layout/flexible-column-layout.stories.js
  stories/horizontal-navigation/__snapshots__/horizontal-navigation.stories.storyshot
  stories/horizontal-navigation/horizontal-navigation.stories.js
  stories/icon-tab-bar/icon-tab-bar.stories.js
  stories/icon/BusinessSuiteInAppSymbols/iconBusinessSuite.stories.js
  stories/icon/SAPIcons/icon.stories.js
  stories/icon/TNTIcons/iconTnt.stories.js
  stories/input-group/input-group.stories.js
  stories/layout-grid/layout-grid.stories.js
  stories/layout-panel/layout-panel.stories.js
  stories/link/link.stories.js
  stories/margins/margins.stories.js
  stories/menu/menu.stories.js
  stories/message-page/message-page.stories.js
  stories/message-strip/message-strip.stories.js
  stories/notification/notification.stories.js
  stories/object-list/object-list.stories.js
  stories/paddings/paddings.stories.js
  stories/page-footer/page-footer.stories.js
  stories/page/page.stories.js
  stories/rating-indicator/rating-indicator.stories.js
  stories/slider/slider.stories.js
  stories/status-indicator/status-indicator.stories.js
  stories/tabs/tabs.stories.js
  stories/text/text.stories.js
  stories/time/time.stories.js
  stories/tool-header/__snapshots__/tool-header.stories.storyshot
  stories/tool-header/tool-header.stories.js
  stories/upload-collection/__snapshots__/upload-collection.stories.storyshot
  stories/upload-collection/upload-collection.stories.js
  stories/wizard/wizard.stories.js
Labels: storybook

#2687 fix: update button theming parameters
  src/mixins/button/_attention.scss
  src/mixins/button/_emphasized.scss
  src/mixins/button/_negative.scss
  src/mixins/button/_positive.scss
Labels: design review changes

#2688 fix: update input theming
  config/bundlesize.json
  src/mixins/_forms.scss
  src/mixins/_mixins.scss
Labels: design review changes
