Repository SAP/fundamental-styles, pull requests merged in 2022-06, with the labels that each got.

#3504 feat(styles): added link content class
  src/styles/mixins/_mixins.scss
  stories/avatar-group/avatar-group.stories.js
  stories/card/card.stories.js
  stories/facets/facets.stories.js
  stories/feed-list/feed-list.stories.js
  stories/link/link.stories.js
  stories/list-grid-select/grid-list-select.stories.js
  stories/list-grid/grid-list.stories.js
  stories/list/byline/byline-list.stories.js
  stories/message-box/message-box.stories.js
  stories/message-page/message-page.stories.js
  stories/multi-input/multi-input.stories.js
  stories/object-identifier/object-identifier.stories.js
  stories/page-footer/page-footer.stories.js
  stories/quick-view/quick-view.stories.js
  stories/table/table.stories.js
  stories/text/text.stories.js
Labels: code refactoring, Horizon Delta

#3442 fix(styles): remove product switch control class [ci visual]
  src/styles/product-switch.scss
  stories/product-switch/product-switch.stories.js
  stories/shellbar/shellbar.stories.js
Labels: Bug

#3506 fix(styles): menu border radius in dialog and disabled outline
  src/styles/menu.scss
Labels: Bug, Theming

#3509 fix(styles): progress indicator progress element positions
  src/styles/progress-indicator.scss
Labels: Bug, Theming, Horizon Delta

#3508 fix(styles): focus outline of rating indicator
  src/styles/rating-indicator.scss
  src/styles/theming/common/rating-indicator/_sap_horizon.scss
  src/styles/theming/common/rating-indicator/_sap_horizon_hc.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming, Horizon Delta

#3510 fix(styles): focus border radius on list items in popovers [ci visual]
  src/styles/dialog.scss
  src/styles/popover.scss
  stories/menu/menu.stories.js
Labels: Theming, Horizon Delta

#3507 fix: micro process flow outline overflow and optimizations
  src/styles/micro-process-flow.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming, Horizon Delta

#3511 fix(styles): tree expander button focus outline
  src/styles/tree.scss
Labels: Bug

#3517 fix(styles): add fix for double focus in single click area for IconTabBar
  src/styles/icon-tab-bar.scss
Labels: Bug, Defect Hunting, stale

#3531 fix(deps): last known good configuration of sass version
  package.json
Labels: Bug, Dependencies

#3513 docs(styles): change carousel max-width
  stories/carousel/carousel.stories.js
Labels: stale

#3529 fix(styles): carousel outline
  src/styles/carousel.scss
Labels: Bug, Horizon Delta

#3530 fix(styles): list icon position
  src/styles/mixins/list/_list-base.scss
Labels: Horizon Delta

#3542 fix(styles): list in card focus outline
  src/styles/card.scss
Labels: Bug

#3544 fix(styles): safari border radius
  src/styles/dialog.scss
Labels: Bug

#3545 fix(styles): tabs padding
  src/styles/tabs.scss
Labels: Bug

#3512 fix(styles): removed fd-breadcrumb__link element
  src/styles/breadcrumb.scss
  stories/breadcrumb/breadcrumb.stories.js
  stories/dynamic-page/dynamic-page.stories.js
  stories/facets/facets.stories.js
Labels: Theming, Horizon Delta

#3515 fix(styles): remove overflow: hidden from tool header elements [ci visual]
  src/styles/tool-header.scss
Labels: Bug, stale

#3516 fix(styles): dialog mobile lists should be in --dialog class [ci visual]
  src/styles/dialog.scss
  src/styles/product-switch.scss
  stories/calendar/calendar.stories.js
  stories/combobox-input/combobox-input.stories.js
  stories/multi-combo-box/multi-combo-box.stories.js
  stories/multi-input/multi-input.stories.js
  stories/select/select.stories.js
  stories/table/table.stories.js
Labels: Bug, documentation

#3546 docs(styles): flexible column layout background
  stories/flexible-column-layout/flexible-column-layout.stories.js
Labels: Bug, Horizon Delta

#3561 chore(deps): update to storybook 6.5.8
  package.json
Labels: Dependencies, Doc website, tooling, stale, documentation

#3563 fix(styles): rating indicator for horizon fixes
  src/styles/rating-indicator.scss
Labels: Bug, Theming

#3586 chore(deps): upgrade to theming-base-content version 11.1.40 [ci visual]
  package.json
Labels: Dependencies, Theming

#3584 docs(styles): add links to older version to introduction page
  .storybook/custom/components/DocsPage.js
  .storybook/custom/components/Versions.js
  .storybook/custom/custom.scss
  stories/docs/introduction.page.js
Labels: Doc website

#3587 fix(styles): object marker focus state & styles refactoring
  src/styles/object-marker.scss
Labels: Bug, Horizon Delta

#3588 feat(docs): move deprecated components to the separate list
  stories/side-navigation/side-navigation.stories.js
  stories/tabs/tabs.stories.js
Labels: documentation

#3598 chore(styles): add template for opening issue for verssion 1.0.0
  .github/ISSUE_TEMPLATE/version_1_0_0.md
Labels: version 1.0

#3585 chore(deps): update storybook to version 6.5.9
  .storybook/main.js
  package.json
Labels: tooling, storybook, stale

#3698 feat(styles): introduce shellbar responsible padding modifier
  src/styles/shellbar.scss
  stories/shellbar/shellbar.stories.js
Labels: Fiori 3 New Feature
