Repository SAP/fundamental-styles, pull requests merged in 2022-07, with the labels that each got.

#3716 chore(docs): link it with the portal
  metadata.yaml
Labels: tooling

#3708 fix(styles): some fixes for fd-bar [ci visual]
  src/styles/bar.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_horizon.scss
  stories/bar/bar.stories.js
Labels: Bug, version 1.0

#3697 feat(fn): theming support intro [ci visual]
  package.json
  src/fn/_dialog-placeholders.scss
  src/fn/_fn-settings.scss
  src/fn/fn-card.scss
  src/fn/fn-dialog.scss
  src/fn/fn-page.scss
  src/fn/fn-title.scss
  src/fn/theming/_evening-mapping.scss
  src/fn/theming/_evening.scss
  src/fn/theming/_morning-mapping.scss
  src/fn/theming/_morning.scss
  src/fn/theming/_shared.scss
Labels: Theming, Fiori Next

#3721 fix(styles): message strip info border color and icons for fiori 3
  src/styles/message-strip.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
Labels: Fiori 3 refactoring, Theming

#3725 fix(styles): list dropdown min-width
  src/styles/mixins/list/_list-dropdown.scss
Labels: Bug

#3729 fix(styles): selected & readonly token
  src/styles/token.scss
Labels: Enhancement

#3739 fix(styles): compact state for form controls
  src/styles/input-group.scss
  src/styles/mixins/_forms.scss
  src/styles/select.scss
  src/styles/step-input.scss
Labels: Bug

#3727 fix(styles): fix vertical alignment of icon in alert
  src/styles/alert.scss
Labels: Bug

#3731 fix(styles): vertical align info label icon
  src/styles/info-label.scss
Labels: Bug, Defect Hunting

#3730 fix(styles): add shellbar logo focus
  src/styles/shellbar.scss
Labels: Bug, Defect Hunting

#3728 fix(styles): Version 1.0.0 Avatar and Avatar Group
  src/styles/_avatar-variables.scss
  src/styles/avatar-group.scss
  src/styles/avatar.scss
  src/styles/mixins/_mixins.scss
  src/styles/mixins/_states.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/avatar-group/__snapshots__/avatar-group.stories.storyshot
  stories/avatar-group/avatar-group.stories.js
  stories/avatar/__snapshots__/avatar.stories.storyshot
  stories/avatar/avatar.stories.js
Labels: version 1.0

#3745 fix(ci): fixed chromatic workflow
  .github/workflows/chromatic.yml
  package.json
Labels: Bug, tooling

#3744 fix(styles): padding issues and RTL placeholder issues
  src/styles/input-group.scss
  src/styles/mixins/_forms.scss
  stories/input-group/input-group.stories.js
Labels: Bug

#3747 test(styles): update snapshots
  stories/bar/__snapshots__/bar.stories.storyshot
  stories/breadcrumb/__snapshots__/breadcrumb.stories.storyshot
  stories/calendar/__snapshots__/calendar.stories.storyshot
  stories/card/__snapshots__/card.stories.storyshot
  stories/carousel/__snapshots__/carousel.stories.storyshot
  stories/combobox-input/__snapshots__/combobox-input.stories.storyshot
  stories/dynamic-page/__snapshots__/dynamic-page.stories.storyshot
  stories/facets/__snapshots__/facets.stories.storyshot
  stories/feed-list/__snapshots__/feed-list.stories.storyshot
  stories/flexible-column-layout/__snapshots__/flexible-column-layout.stories.storyshot
  stories/link/__snapshots__/link.stories.storyshot
  stories/list-grid-select/__snapshots__/grid-list-select.stories.storyshot
  stories/list-grid/__snapshots__/grid-list.stories.storyshot
  stories/list/byline/__snapshots__/byline-list.stories.storyshot
  stories/menu/__snapshots__/menu.stories.storyshot
  stories/message-box/__snapshots__/message-box.stories.storyshot
  stories/message-page/__snapshots__/message-page.stories.storyshot
  stories/multi-combo-box/__snapshots__/multi-combo-box.stories.storyshot
  stories/multi-input/__snapshots__/multi-input.stories.storyshot
  stories/object-identifier/__snapshots__/object-identifier.stories.storyshot
  stories/page-footer/__snapshots__/page-footer.stories.storyshot
  stories/product-switch/__snapshots__/product-switch.stories.storyshot
  stories/quick-view/__snapshots__/quick-view.stories.storyshot
  stories/select/__snapshots__/select.stories.storyshot
  stories/shellbar/__snapshots__/shellbar.stories.storyshot
  stories/side-navigation/__snapshots__/side-navigation.stories.storyshot
  stories/table/__snapshots__/table.stories.storyshot
  stories/tabs/__snapshots__/tabs.stories.storyshot
  stories/text/__snapshots__/text.stories.storyshot
  stories/vertical-navigation/__snapshots__/vertical-navigation.stories.storyshot
Labels: Visual Testing

#3758 fix(styles): fd-emty was used instead fd-only-child
  src/styles/object-status.scss
Labels: Bug, Defect Hunting
