Repository SAP/fundamental-styles, pull requests merged in 2022-03, with the labels that each got.

#3211 chore(styles): update theming-base-content version 11.1.35 [ci visual]
  config/postcss-add-fallback.js
  package.json
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming, Fiori Next

#3212 fix(fn): add split Tabs type [ci visual]
  src/fn/fn-tabs.scss
  stories/fn-tabs/__snapshots__/fn-tabs.stories.storyshot
  stories/fn-tabs/fn-tabs.stories.js
Labels: Fiori Next

#3217 feat(fn): introduce FN Busy Indicator [ci visual]
  src/fn/fn-busy-indicator.scss
  src/fn/fundamental-next.scss
  stories/fn-busy-indicator/__snapshots__/fn-busy-indicator.stories.storyshot
  stories/fn-busy-indicator/fn-busy-indicator.stories.js
Labels: Fiori Next

#3218 fix(styles): add cursor pointer to Avatar with zoom icon [ci visual]
  src/styles/avatar.scss
  stories/avatar/__snapshots__/avatar.stories.storyshot
  stories/avatar/avatar.stories.js
Labels: Bug

#3208 fix: fixed card layout refactoring
  src/styles/fixed-card-layout.scss
  stories/fixed-card-layout/__snapshots__/fixed-card-layout.stories.storyshot
  stories/fixed-card-layout/fixed-card-layout.stories.js
Labels: Enhancement, stale

#3225 fix(fn): update the width of the input messages [ci visual]
  src/fn/fn-input-message.scss
Labels: Fiori Next

#3230 feat(styles): add delta horizon theming for message strip
  src/styles/message-strip.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming

#3216 docs(styles): update the documentation for counter [ci visual]
  stories/counter/counter.stories.js
Labels: Doc website

#3229 fix(styles): layout grid gutters
  src/styles/layout-grid.scss
Labels: Bug, Defect Hunting

#3232 feat(styles): add delta horizon theming for Avatar
  src/styles/avatar.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming

#3233 feat(styles): add new color of enumeration for Icon [ci visual]
  src/icons/_mixins.scss
  src/styles/icons/_settings.scss
  stories/avatar-group/__snapshots__/avatar-group.stories.storyshot
  stories/icon/BusinessSuiteInAppSymbols/iconBusinessSuite.stories.js
  stories/icon/SAPIcons/icon.stories.js
  stories/icon/TNTIcons/iconTnt.stories.js
Labels: Theming

#3234 feat(styles): add delta horizon theming for Busy Indicator
  src/styles/busy-indicator.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming

#3215 fix: popover styles refactoring
  src/styles/popover.scss
Labels: Bug, Enhancement, code refactoring

#3241 fix(fn): update the position of the icon on multi line for Message Strip
  src/fn/fn-message-strip.scss
  stories/fn-message-strip/fn-message-strip.stories.js
Labels: Fiori Next

#3246 feat(styles): add delta horizon theming for Badge on Button
  src/styles/mixins/button/_badge.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming

#3235 fix: popover arrow in compact mode
  src/styles/popover.scss
Labels: Bug, Defect Hunting

#3250 fix(styles): bump theming-base-content version 11.1.36 [ci visual]
  package.json
Labels: Theming

#3255 fix(fn): update checkbox and radio labels for long text [ci visual]
  src/fn/fn-checkbox.scss
  src/fn/fn-radio.scss
  src/styles/button.scss
  stories/fn-toggles/fn-toggles.stories.js
Labels: Fiori Next

#3227 fix: upload collection overflow [ci visual]
  src/styles/upload-collection.scss
  stories/upload-collection/__snapshots__/upload-collection.stories.storyshot
  stories/upload-collection/upload-collection.stories.js
Labels: Bug, Defect Hunting

#3257 fix(styles): update Message Box icons per Fiori specs [ci visual]
  stories/message-box/message-box.stories.js
Labels: Theming

#3259 feat(styles): add delta horizon theming support for Popover [ci visual]
  src/styles/mixins/_popover.scss
  src/styles/popover.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming

#3251 chore(styles): message strip horizon parameters [ci visual]
  src/styles/message-strip.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming

#3252 feat(styles): checkbox horizon support
  src/styles/checkbox.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Enhancement

#3253 feat(styles): add delta horizon theming for Radio Button
  src/styles/radio.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming

#3256 fix(styles): form mis-alignments
  src/styles/form-header.scss
  src/styles/form-layout-grid.scss
  src/styles/input.scss
Labels: Bug

#3260 feat(styles): horizon theming for Text
  src/styles/text.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming

#3254 feat(styles): shellbar horizon support
  src/styles/shellbar.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/shellbar/shellbar.stories.js
Labels: Bug, Enhancement

#3270 chore(deps): theming-base-content 11.1.37
  package.json
Labels: Dependencies, Theming

#3269 feat(styles): add delta horizon theming for Toolbar [ci visual]
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  src/styles/toolbar.scss
  stories/toolbar/__snapshots__/toolbar.stories.storyshot
  stories/toolbar/toolbar.stories.js
Labels: Theming
