Repository SAP/fundamental-styles, pull requests merged in 2022-04, with the labels that each got.

#3267 feat(styles): add delta horizon theming support for Token [ci visual]
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  src/styles/token.scss
Labels: Theming

#3263 feat(styles): horizon theming for Switch component
  src/styles/switch.scss
  src/styles/theming/common/switch/_sap_fiori.scss
  src/styles/theming/common/switch/_sap_horizon.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/switch/switch.stories.js
Labels: Theming, Fiori Next

#3284 feat(common-css): introduce common-css package
  .gitignore
  ci-scripts/publish-rc.sh
  ci-scripts/publish.sh
  ci-scripts/sync-version.sh
  commitlint.config.js
  config/common-css/README.md
  config/common-css/package.json
  package.json
  scripts/copy-common-css-readme-and-package.js
  src/common-css/_common-mixins.scss
  src/common-css/_common-settings.scss
  src/common-css/_common-variables.scss
  src/common-css/common-css.scss
Labels: tooling, common-css

#3286 chore(common-css): fix the package name and versions
  config/common-css/package.json
  scripts/sync-version.js
Labels: tooling

#3271 feat(styles): add delta theming for Bar [ci visual]
  src/styles/bar.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/bar/__snapshots__/bar.stories.storyshot
  stories/bar/bar.stories.js
Labels: Theming, stale

#3289 chore(styles): update addon versions [ci visual]
  package.json
Labels: Dependencies

#3296 chore(deps): update theming-base-content version 11.1.38
  package.json
Labels: Dependencies, Theming

#3306 feat(common-css): publish padding and margin classes
  src/common-css/_common-mixins.scss
  src/common-css/common-css.scss
Labels: common-css

#3319 chore(deps): update storybook version 6.4.21
  package.json
Labels: Dependencies, storybook

#3308 fix(styles): fixed flickering when theme switches
  .storybook/custom/decorators/componentStylesProvider.js
  .storybook/custom/decorators/themeProvider.js
  .storybook/custom/styleChangers/dev/componentStylesManager.js
  .storybook/custom/styleChangers/dev/themeVariablesManager.js
  .storybook/custom/styleChangers/prod/componentStylesManager.js
  .storybook/custom/styleChangers/prod/themeVariablesManager.js
Labels: Bug, storybook

#3298 feat(styles): add Horizon theming for Page[ci visual]
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming, stale

#3262 feat(styles): add delta horizon theming for Card
  package.json
  src/styles/card.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/card/card.stories.js
Labels: Theming

#3295 fix: select min-width fix, overflow fix
  src/styles/popover.scss
  src/styles/select.scss
  stories/pagination/pagination.stories.js
Labels: Bug

#3299 fix: table text shadow removal
  src/styles/table.scss
  stories/table/table.stories.js
Labels: Bug

#3264 feat(styles): add delta horizon theming support for Button
  .storybook/custom/custom.scss
  src/styles/button-split.scss
  src/styles/button.scss
  src/styles/carousel.scss
  src/styles/input-group.scss
  src/styles/mixins/button/_attention.scss
  src/styles/mixins/button/_badge.scss
  src/styles/mixins/button/_button-helper.scss
  src/styles/mixins/button/_button-transparent.scss
  src/styles/mixins/button/_emphasized.scss
  src/styles/mixins/button/_ghost.scss
  src/styles/mixins/button/_negative.scss
  src/styles/mixins/button/_positive.scss
  src/styles/mixins/button/_standard.scss
  src/styles/mixins/button/_transparent.scss
  src/styles/product-switch.scss
  src/styles/segmented-button.scss
  src/styles/tabs.scss
  src/styles/theming/common/button/_sap_fiori.scss
  src/styles/theming/common/button/_sap_horizon.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  src/styles/tile.scss
  src/styles/tool-header.scss
  stories/button/button.stories.js
Labels: Theming

#3325 fix(styles,fn,deps,ci): removed third party postcss-clean and updated cssnano
  config/postcss.config.js
  package.json
  scripts/postcss-cleaner.js
  src/icons/_mixins.scss
  src/styles/action-sheet.scss
  src/styles/icons/_settings.scss
  src/styles/pagination.scss
Labels: tooling

#3305 fix(styles): layout grid nested rows
  src/styles/layout-grid.scss
Labels: Bug

#3301 feat(styles): icon tabs header horizon delta theming
  src/styles/icon-tab-bar.scss
  src/styles/mixins/_mixins.scss
  src/styles/theming/common/icon-tab-bar/_sap_fiori.scss
  src/styles/theming/common/icon-tab-bar/_sap_fiori_hc.scss
  src/styles/theming/common/icon-tab-bar/_sap_horizon.scss
  src/styles/theming/common/icon-tab-bar/_sap_horizon_hc.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/icon-tab-bar/icon-tab-bar.stories.js
Labels: Theming

#3331 chore(ci): optimize rc release script
  .github/workflows/on-push-or-pull.yml
  ci-scripts/hotfix-publish.sh
  ci-scripts/publish-rc.sh
  scripts/hotfix-publish-release.sh
Labels: tooling

#3332 chore(ci): fix rc script
  ci-scripts/publish-rc.sh
Labels: tooling

#3347 chore(ci): fix rc publishing script
  ci-scripts/publish-rc.sh
Labels: tooling

#3348 chore(deps): upgrade storybook version 6.4.22
  package.json
Labels: tooling, storybook

#3297 feat(styles): add delta theming for Dynamic Page [ci visual]
  src/styles/dynamic-page.scss
  src/styles/theming/common/dynamic-page-layout/_sap_fiori.scss
  src/styles/theming/common/dynamic-page-layout/_sap_horizon.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming, stale

#3349 chore(ci): optimize release and hotfix scripts
  ci-scripts/hotfix-publish.sh
  ci-scripts/publish.sh
Labels: tooling

#3351 feat(styles): implement delta horizon theming for table [ci-visual]
  src/styles/table.scss
  src/styles/theming/common/table/_sap_fiori.scss
  src/styles/theming/common/table/_sap_horizon.scss
  src/styles/theming/common/table/_sap_horizon_hc.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Enhancement

#3352 fix(styles): horizon menu border radius bug [ci-visual]
  src/styles/menu.scss
  src/styles/theming/common/button/_sap_fiori.scss
  src/styles/theming/common/button/_sap_horizon.scss
Labels: Bug

#3359 fix(styles): remove search button in inputs in webkit browsers
  src/styles/input.scss
  src/styles/mixins/_mixins.scss
Labels: Bug

#3360 fix(styles): shellbar logo, product and subtitle display
  src/styles/shellbar.scss
Labels: Horizon Delta

#3330 feat(styles): add delta horizon theming for Grid List
  .storybook/custom/custom.scss
  scripts/build-accessibility-tests.js
  src/styles/fundamental-styles.scss
  src/styles/grid-list.scss
  src/styles/list-grid.scss
  src/styles/theming/common/grid-list/_sap_fiori.scss
  src/styles/theming/common/grid-list/_sap_horizon.scss
  src/styles/theming/common/grid-list/_sap_horizon_hc.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/list-grid-select/__snapshots__/grid-list-select.stories.storyshot
  stories/list-grid-select/__snapshots__/list-grid.stories.storyshot
  stories/list-grid-select/grid-list-select.stories.js
  stories/list-grid/__snapshots__/grid-list.stories.storyshot
  stories/list-grid/grid-list.stories.js
Labels: Theming, Horizon Delta

#3363 fix: checkbox, radio borders in horizon
  src/styles/checkbox.scss
  src/styles/radio.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Bug, Defect Hunting, Horizon Delta

#3364 feat(styles): introduce BTP variables for Horizon Themes
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Horizon Delta

#3366 feat(styles): add info label horizon delta theming
  src/styles/info-label.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming, Horizon Delta

#3357 fix(styles): calendar year/month buttons
  src/styles/calendar.scss
  stories/calendar/calendar.stories.js
Labels: code refactoring, Horizon Delta

#3367 feat: horizon theme scrollbar
  src/styles/scrollbar.scss
  src/styles/theming/common/scrollbar/_sap_fiori.scss
  src/styles/theming/common/scrollbar/_sap_horizon.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming, Horizon Delta

#3358 feat(styles): popover body compact, arrow position fix
  src/styles/popover.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/action-bar/action-bar.stories.js
  stories/action-sheet/action-sheet.stories.js
  stories/feed-list/feed-list.stories.js
  stories/popover/popover.stories.js
Labels: Bug
