Repository SAP/fundamental-styles, pull requests merged in 2022-02, with the labels that each got.

#3135 feat(docs): added fiori version switch
  .gitignore
  .storybook/custom/DocsPage.scss
  .storybook/custom/IntroductionPage.scss
  .storybook/custom/addons/FioriVersion/constants.js
  .storybook/custom/addons/FioriVersion/register.js
  .storybook/custom/components/DirectionalitySelect.js
  .storybook/custom/components/DocsPage.js
  .storybook/custom/components/Header.js
  .storybook/custom/components/InfoLabels.js
  .storybook/custom/components/SAPContainer.js
  .storybook/custom/components/Toc.js
  .storybook/custom/components/VersionSelect.js
  .storybook/custom/constants/fioriVersions.js
  .storybook/custom/custom.scss
  .storybook/custom/decorators/themeProvider.js
  .storybook/custom/hooks/initToc.js
  .storybook/custom/hooks/useStyles.js
  .storybook/custom/hooks/useThemedStoryContainers.js
  .storybook/main.js
  .storybook/preview.js
  package.json
  scripts/build-visual-stories.js
  scripts/storybook-prep.js
  stories/docs/introduction.page.js
  stories/docs/introduction.stories.js
Labels: storybook, Fiori Next

#3137 fix(styles): add overflow modifier classes for Menu and VertNav
  src/styles/menu.scss
  src/styles/vertical-nav.scss
  stories/menu/__snapshots__/menu.stories.storyshot
  stories/menu/menu.stories.js
  stories/vertical-navigation/__snapshots__/vertical-navigation.stories.storyshot
  stories/vertical-navigation/vertical-navigation.stories.js
Labels: Bug, Enhancement

#3141 feat(fn): introduce Message Toast in Fiori Next
  src/fn/fn-message-toast.scss
  src/fn/fundamental-next.scss
  stories/fn-message-toast/__snapshots__/fn-message-toast.stories.storyshot
  stories/fn-message-toast/fn-message-toast.stories.js
  stories/menu/__snapshots__/menu.stories.storyshot
  stories/vertical-navigation/__snapshots__/vertical-navigation.stories.storyshot
Labels: Fiori Next

#3128 feat(fn): implement fn-list
  src/fn/fn-list.scss
  src/fn/fn-object-status.scss
  stories/fn-list/__snapshots__/fn-list.stories.storyshot
  stories/fn-list/fn-list.stories.js
Labels: Fiori Next

#3144 feat(fn): introduce Dropdown in Fiori Next
  src/fn/fn-dropdown.scss
  src/fn/fundamental-next.scss
  stories/fn-dropdown/__snapshots__/fn-dropdown.stories.storyshot
  stories/fn-dropdown/fn-dropdown.stories.js
  stories/fn-select/fn-select.stories.js
Labels: Fiori Next

#3145 docs(fn): replace experimental with FN
  .storybook/custom/addons/FioriVersion/constants.js
  config/jest.config.js
  stories/docs/__snapshots__/introduction.stories.storyshot
  stories/docs/introduction.stories.js
  stories/fn-avatar/__snapshots__/fn-avatar.stories.storyshot
  stories/fn-avatar/fn-avatar.stories.js
  stories/fn-button/__snapshots__/fn-button.stories.storyshot
  stories/fn-button/fn-button.stories.js
  stories/fn-card/__snapshots__/fn-card.stories.storyshot
  stories/fn-card/fn-card.stories.js
  stories/fn-combobox/__snapshots__/fn-combobox.stories.storyshot
  stories/fn-combobox/fn-combobox.stories.js
  stories/fn-dialog/__snapshots__/fn-dialog.stories.storyshot
  stories/fn-dialog/fn-dialog.stories.js
  stories/fn-form/__snapshots__/fn-form.stories.storyshot
  stories/fn-form/fn-form.stories.js
  stories/fn-generic-tag/__snapshots__/fn-generic-tag.stories.storyshot
  stories/fn-generic-tag/fn-generic-tag.stories.js
  stories/fn-info-label/__snapshots__/fn-info-label.stories.storyshot
  stories/fn-info-label/fn-info-label.stories.js
  stories/fn-input/__snapshots__/fn-input.stories.storyshot
  stories/fn-input/fn-input.stories.js
  stories/fn-link/__snapshots__/fn-link.stories.storyshot
  stories/fn-link/fn-link.stories.js
  stories/fn-list/__snapshots__/fn-list.stories.storyshot
  stories/fn-list/fn-list.stories.js
  stories/fn-message-box/__snapshots__/fn-message-box.stories.storyshot
  stories/fn-message-box/fn-message-box.stories.js
  stories/fn-message-strip/__snapshots__/fn-message-strip.stories.storyshot
  stories/fn-message-strip/fn-message-strip.stories.js
  stories/fn-message-toast/__snapshots__/fn-message-toast.stories.storyshot
  stories/fn-message-toast/fn-message-toast.stories.js
  stories/fn-multi-input/__snapshots__/fn-multi-input.stories.storyshot
  stories/fn-multi-input/fn-multi-input.stories.js
  stories/fn-object-status/__snapshots__/fn-object-status.stories.storyshot
  stories/fn-object-status/fn-object-status.stories.js
  stories/fn-progress-bar/__snapshots__/fn-progress-bar.stories.storyshot
  stories/fn-progress-bar/fn-progress-bar.stories.js
  stories/fn-rating-indicator/__snapshots__/fn-rating-indicator.stories.storyshot
  stories/fn-rating-indicator/fn-rating-indicator.stories.js
  stories/fn-search/__snapshots__/fn-search.stories.storyshot
  stories/fn-search/fn-search.stories.js
  stories/fn-select/__snapshots__/fn-select.stories.storyshot
  stories/fn-select/fn-select.stories.js
  stories/fn-shell/__snapshots__/fn-shell.stories.storyshot
  stories/fn-shell/fn-shell.stories.js
  stories/fn-slider/__snapshots__/fn-slider.stories.storyshot
  stories/fn-slider/fn-slider.stories.js
  stories/fn-step-input/__snapshots__/fn-step-input.stories.storyshot
  stories/fn-step-input/fn-step-input.stories.js
  stories/fn-tabs/__snapshots__/fn-tabs.stories.storyshot
  stories/fn-tabs/fn-tabs.stories.js
  stories/fn-textarea/__snapshots__/fn-textarea.stories.storyshot
  stories/fn-textarea/fn-textarea.stories.js
  stories/fn-title/__snapshots__/title.stories.storyshot
  stories/fn-title/title.stories.js
  stories/fn-toggles/__snapshots__/fn-toggles.stories.storyshot
  stories/fn-toggles/fn-toggles.stories.js
  stories/fn-token/__snapshots__/fn-token.stories.storyshot
  stories/fn-token/fn-token.stories.js
Labels: storybook, Fiori Next

#3142 feat(fn): implement notification component [ci visual]
  src/fn/fn-notification.scss
  stories/fn-dropdown/__snapshots__/fn-dropdown.stories.storyshot
  stories/fn-dropdown/fn-dropdown.stories.js
  stories/fn-notification/__snapshots__/fn-notification.stories.storyshot
  stories/fn-notification/fn-notification.stories.js
Labels: Fiori Next

#3146 fix(fn): add additional modifier classes to Dropdown
  src/fn/fn-dropdown.scss
  stories/fn-dropdown/__snapshots__/fn-dropdown.stories.storyshot
  stories/fn-dropdown/fn-dropdown.stories.js
Labels: Fiori Next

#3157 chore(deps): update storybook version 6.4.18
  package.json
Labels: storybook

#3160 docs(styles,fn): update wrong link to icons
  README.md
Labels: documentation

#3159 fix(fn): adjust slider handle position [ci visual]
  src/fn/fn-slider.scss
  stories/fn-slider/__snapshots__/fn-slider.stories.storyshot
  stories/fn-slider/fn-slider.stories.js
Labels: Fiori Next

#3161 docs(styles): updated the documentation of code
  stories/code/code.stories.js
  stories/docs/introduction.stories.mdx
Labels: documentation

#3163 feat(fn): introduce Page components [ci visual]
  src/fn/_fn-new-variables.scss
  src/fn/fn-page.scss
  src/fn/fundamental-next.scss
  stories/fn-page/__snapshots__/fn-page.stories.storyshot
  stories/fn-page/fn-page.stories.js
Labels: Fiori Next

#3170 fix(styles): fix nested list button bgd issue and popover radius
  src/styles/nested-list.scss
Labels: Bug

#3165 feat(fn): introduce fn-table [ci visual]
  src/fn/_fn-variables.scss
  src/fn/fn-list.scss
  src/fn/fn-table.scss
  stories/fn-list/__snapshots__/fn-list.stories.storyshot
  stories/fn-list/fn-list.stories.js
  stories/fn-table/__snapshots__/fn-table.stories.storyshot
  stories/fn-table/fn-table.stories.js
Labels: Fiori Next

#3171 fix: card header non-interactive outline
  src/styles/card.scss
Labels: Bug

#3172 fix(fn): update colors API, avatar and info label [ci visual]
  src/fn/_dialog-placeholders.scss
  src/fn/_fn-mixins.scss
  src/fn/_fn-new-variables.scss
  src/fn/fn-avatar.scss
  src/fn/fn-button.scss
  src/fn/fn-card.scss
  src/fn/fn-checkbox.scss
  src/fn/fn-generic-tag.scss
  src/fn/fn-info-label.scss
  src/fn/fn-input.scss
  src/fn/fn-label.scss
  src/fn/fn-link.scss
  src/fn/fn-list.scss
  src/fn/fn-message-box.scss
  src/fn/fn-message-strip.scss
  src/fn/fn-message-toast.scss
  src/fn/fn-nested-button.scss
  src/fn/fn-notification.scss
  src/fn/fn-object-status.scss
  src/fn/fn-progress-bar.scss
  src/fn/fn-radio.scss
  src/fn/fn-rating-indicator.scss
  src/fn/fn-search.scss
  src/fn/fn-segmented-button.scss
  src/fn/fn-shell.scss
  src/fn/fn-slider.scss
  src/fn/fn-split-button.scss
  src/fn/fn-switch.scss
  src/fn/fn-tabs.scss
  src/fn/fn-textarea.scss
  src/fn/fn-title.scss
  src/fn/fn-token.scss
  stories/fn-avatar/__snapshots__/fn-avatar.stories.storyshot
  stories/fn-avatar/fn-avatar.stories.js
  stories/fn-info-label/__snapshots__/fn-info-label.stories.storyshot
  stories/fn-info-label/fn-info-label.stories.js
Labels: Fiori Next

#3169 docs(styles): updated the documentation of time picker component [ci …
  stories/time-picker/time-picker.stories.js
Labels: documentation

#3167 docs(styles): updated the documentation of user menu component [ci vi…
  stories/user-menu/user-menu.stories.js
Labels: documentation

#3177 fix(fn): update Card with some extra features [ci visual]
  src/fn/_fn-mixins.scss
  src/fn/fn-card.scss
  stories/fn-card/__snapshots__/fn-card.stories.storyshot
  stories/fn-card/fn-card.stories.js
Labels: Fiori Next

#3178 chore(deps): upgrade to storybook version 6.4.19 [ci visual]
  package.json
Labels: Dependencies, storybook

#3186 docs(ci): replace travis badge with gh actions one
  README.md
Labels: tooling

#3187 docs(ci): fix badge
  README.md
Labels: tooling

#3191 fix(fn): update Label and Shell to match the design [ci visual]
  src/fn/fn-label.scss
  src/fn/fn-shell.scss
  src/fn/fundamental-next.scss
  stories/fn-form/fn-form.stories.js
Labels: Fiori Next

#3192 fix(fn): update Message strip to latest design [ci visual]
  src/fn/fn-message-strip.scss
  stories/fn-message-strip/__snapshots__/fn-message-strip.stories.storyshot
  stories/fn-message-strip/fn-message-strip.stories.js
Labels: Fiori Next

#3193 fix(fn): update Progress Bar colors [ci visual]
  src/fn/fn-progress-bar.scss
Labels: Fiori Next

#3189 feat(styles): info label display mode, update design [ci visual]
  .storybook/custom/components/InfoLabel.js
  src/styles/info-label.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  stories/info-label/__snapshots__/info-label.stories.storyshot
  stories/info-label/info-label.stories.js
  stories/user-menu/__snapshots__/user-menu.stories.storyshot
Labels: Fiori 3 refactoring

#3200 docs(styles): add monthly npm download badge
  README.md
Labels: documentation

#3175 docs(styles): update the documentation for multi input [ci visual]
  stories/multi-input/multi-input.stories.js
Labels: documentation

#3205 fix(fn): update Slider to lates design [ci visual]
  src/fn/fn-slider.scss
Labels: Fiori Next

#3198 feat(fn): introduce fn-popover [ci visual]
  src/fn/fn-popover.scss
  stories/fn-popover/__snapshots__/fn-popover.stories.storyshot
  stories/fn-popover/fn-popover.stories.js
Labels: Fiori Next

#3204 feat(fn): introduce Input Messages [ci visual]
  src/fn/fn-form.scss
  src/fn/fn-input-message.scss
  src/fn/fn-input.scss
  src/fn/fundamental-next.scss
  stories/fn-form/__snapshots__/fn-form.stories.storyshot
  stories/fn-form/fn-form.stories.js
  stories/fn-input/__snapshots__/fn-input.stories.storyshot
  stories/fn-input/fn-input.stories.js
Labels: Fiori Next
