Repository SAP/fundamental-styles, pull requests merged in 2022-12, with the labels that each got.

#4058 fix(styles): tabs & dynamic page horizontal paddings
  packages/styles/src/dynamic-page.scss
Labels: Bug, dxp

#4057 fix(styles): popover arrow styles
  packages/styles/src/popover.scss
Labels: Bug

#4063 fix(styles): popover's visibility for vertical nav
  packages/styles/src/popover.scss
Labels: Bug

#4062 feat(styles): add notification to byline list [ci visual]
  packages/styles/src/mixins/list/_list-byline.scss
  packages/styles/stories/Components/List/list/byline/byline-list.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Enhancement, dxp

#4064 chore(deps): update theming-base-content v 11.1.47 [ci visual]
  package.json
  yarn.lock
Labels: Theming

#4068 fix(styles): add fix for Title font-family [ci visual]
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/title.scss
Labels: Bug

#4018 docs(fn): all readme
  README.md
  packages/common-css/README.md
  packages/cx/README.md
  packages/doc-ui/README.md
  packages/fn/README.md
  packages/styles/README.md
Labels: Doc website

#4066 fix(styles): minor changes to the notification in Byline list
  packages/styles/src/mixins/list/_list-byline.scss
Labels: Enhancement

#4067 docs(styles): add tabindex to menu button in shellbar [ci visual]
  packages/styles/stories/Components/shellbar/shellbar.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug

#4081 fix(styles): provide option for ShellBar logo to be used as a link
  packages/styles/src/shellbar.scss
  packages/styles/stories/Components/shellbar/shellbar.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug, dxp

#4080 fix(styles): add fix for no horizontal and vertical borders in Table
  packages/styles/src/table.scss
Labels: Bug

#4031 feat(styles): introduce variant management styling [ci visual]
  packages/styles/src/fundamental-styles.scss
  packages/styles/src/theming/common/variant-management/_sap_fiori.scss
  packages/styles/src/theming/common/variant-management/_sap_horizon.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/src/variant-management.scss
  packages/styles/stories/Components/variant-management/variant-management.stories.js
Labels: Fiori New Component

#4084 fix(styles): change the cursor from text to pointer in Select componеnt
  packages/styles/src/select.scss
Labels: Bug

#4085 docs(styles): add readonly state example in Input Group [ci visual]
  packages/styles/stories/Components/Forms/input-group/input-group.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: documentation

#4079 fix(styles): add fix for margin-bottom of Select [ci visual]
  packages/styles/src/select.scss
  packages/styles/stories/Components/select/select.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug

#4102 fix(styles): update values for Toolbar with Title [ci visual]
  packages/styles/src/toolbar.scss
  packages/styles/stories/Components/toolbar/toolbar.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug

#4104 fix(styles): fix for high-contrast under windows
  packages/styles/src/mixins/_mixins.scss
Labels: A11y, Theming

#4106 fix(docs): fixed gh deployment base url
  .github/workflows/create-release.yml
  .storybook/main.ts
  package.json
  packages/common-css/stories/colors/colors.stories.js
  vite.config.ts
  yarn.lock
Labels: Bug

#4107 fix: fixing asset urls
  iframe.html
Labels: Bug

#4121 fix(styles): quick view styles & examples
  packages/styles/src/quick-view.scss
  packages/styles/stories/Components/quick-view/quick-view.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug, Defect Hunting

#4120 fix(styles): link styles & breadcrumbs overflow item
  packages/styles/src/mixins/_mixins.scss
  packages/styles/stories/Components/breadcrumb/breadcrumb.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug, Defect Hunting

#4123 fix(styles): apply custom scrollbar to vertical nav
  packages/styles/src/vertical-nav.scss
Labels: Bug, Defect Hunting

#4119 fix(styles): textarea focus & scrollbar styles
  packages/styles/src/textarea.scss
Labels: Bug, Defect Hunting

#4124 fix(styles): object marker link & refactoring
  packages/styles/src/mixins/_mixins.scss
  packages/styles/src/object-marker.scss
Labels: Bug, Defect Hunting

#4122 fix(docs): broken examples, defect hunting 103
  packages/styles/stories/Components/object-status/object-status.stories.js
  packages/styles/stories/Components/table/table.stories.js
  packages/styles/stories/Layouts/dynamic-page/dynamic-page.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug, Defect Hunting

#4137 fix: fixed access type on releases
  .github/actions/npm-publish/index.js
Labels: Bug

#4136 feat(styles): popover wrapper with overflow visible
  packages/styles/src/popover.scss
Labels: Bug, Defect Hunting

#4138 fix(ci): fixed package.json paths in publish script
  .github/actions/npm-publish/index.js
Labels: Bug, high priority
