Repository SAP/fundamental-styles, pull requests merged in 2022-05, with the labels that each got.

#3365 feat(styles): card footer implementation
  src/styles/card.scss
  src/styles/theming/common/card/_sap_fiori.scss
  src/styles/theming/common/card/_sap_fiori_hc.scss
  src/styles/theming/common/card/_sap_horizon.scss
  src/styles/theming/common/card/_sap_horizon_hc.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/card/card.stories.js
Labels: stale

#3328 fix(style): button refactoring
  src/styles/button-split.scss
  src/styles/button.scss
  src/styles/mixins/button/_attention.scss
  src/styles/mixins/button/_button-badge.scss
  src/styles/mixins/button/_button-helper.scss
  src/styles/mixins/button/_button-types.scss
  src/styles/mixins/button/_emphasized.scss
  src/styles/mixins/button/_ghost.scss
  src/styles/mixins/button/_negative.scss
  src/styles/mixins/button/_positive.scss
  src/styles/mixins/button/_standard.scss
  src/styles/segmented-button.scss
  src/styles/theming/common/button/_sap_fiori.scss
  src/styles/theming/common/button/_sap_fiori_hc.scss
  src/styles/theming/common/button/_sap_horizon.scss
  src/styles/theming/common/button/_sap_horizon_hc.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/button/button.stories.js
  stories/counter/counter.stories.js
Labels: code refactoring

#3378 fix: split button separator in horizon
  src/styles/button-split.scss
Labels: Bug, Horizon Delta

#3379 fix(styles): added card container border radius and overflow
  src/styles/card.scss
  stories/card/card.stories.js
Labels: Bug, code refactoring

#3377 feat(styles): add delta horizon theming for Splitter
  src/styles/fundamental-styles.scss
  src/styles/splitter.scss
  src/styles/theming/common/splitter/_sap_fiori.scss
  src/styles/theming/common/splitter/_sap_fiori_hc.scss
  src/styles/theming/common/splitter/_sap_horizon.scss
  src/styles/theming/common/splitter/_sap_horizon_hc.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/splitter/__snapshots__/splitter.stories.storyshot
  stories/splitter/splitter.stories.js
Labels: Horizon Delta

#3375 feat(styles): horizon family delta for link
  src/styles/link.scss
  src/styles/mixins/_mixins.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming, Horizon Delta

#3386 feat(styles): migrate input controls to Horizon theme
  src/styles/file-uploader.scss
  src/styles/form-message.scss
  src/styles/input-group.scss
  src/styles/input.scss
  src/styles/mixins/_forms.scss
  src/styles/mixins/_states.scss
  src/styles/popover.scss
  src/styles/select.scss
  src/styles/shellbar.scss
  src/styles/step-input.scss
  src/styles/textarea.scss
  src/styles/theming/common/input-group/_sap_fiori.scss
  src/styles/theming/common/input-group/_sap_horizon.scss
  src/styles/theming/common/input/_sap_fiori.scss
  src/styles/theming/common/input/_sap_horizon.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  src/styles/tokenizer.scss
  stories/combobox-input/__snapshots__/combobox-input.stories.storyshot
  stories/combobox-input/combobox-input.stories.js
  stories/datepicker/__snapshots__/datepicker.stories.storyshot
  stories/datepicker/datepicker.stories.js
  stories/input-group/__snapshots__/input-group.stories.storyshot
  stories/input-group/input-group.stories.js
  stories/input/__snapshots__/input.stories.storyshot
  stories/input/input.stories.js
  stories/multi-combo-box/__snapshots__/multi-combo-box.stories.storyshot
  stories/multi-combo-box/multi-combo-box.stories.js
  stories/multi-input/__snapshots__/multi-input.stories.storyshot
  stories/multi-input/multi-input.stories.js
  stories/select/__snapshots__/select.stories.storyshot
  stories/select/select.stories.js
  stories/step-input/__snapshots__/step-input.stories.storyshot
  stories/step-input/step-input.stories.js
  stories/time-picker/__snapshots__/time-picker.stories.storyshot
  stories/time-picker/time-picker.stories.js
Labels: Theming

#3383 feat(styles): panel horizon updates [ci-visual]
  src/styles/panel.scss
  src/styles/theming/common/panel/_sap_fiori.scss
  src/styles/theming/common/panel/_sap_horizon.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Enhancement

#3376 fix(styles): minor nested list border bug [ci-visual]
  src/styles/nested-list.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_horizon.scss
Labels: Bug

#3391 feat(styles): tree refactor and horizon adaptation
  .storybook/static/preview-head.js
  src/styles/mixins/list/_list-definitions.scss
  src/styles/mixins/tree/_mixins.scss
  src/styles/mixins/tree/_modifiers.scss
  src/styles/tree.scss
  stories/tree/tree.stories.js
Labels: Theming, code refactoring

#3381 feat(styles): slider horizon theme
  src/styles/slider.scss
  src/styles/theming/common/slider/_sap_fiori.scss
  src/styles/theming/common/slider/_sap_fiori_hc.scss
  src/styles/theming/common/slider/_sap_horizon.scss
  src/styles/theming/common/slider/_sap_horizon_hc.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/slider/slider.stories.js
Labels: Theming, Horizon Delta

#3382 feat(styles): wizard horizon updates [ci-visual]
  src/styles/theming/common/wizard/_sap_fiori.scss
  src/styles/theming/common/wizard/_sap_fiori_hc.scss
  src/styles/theming/common/wizard/_sap_horizon.scss
  src/styles/theming/common/wizard/_sap_horizon_hc.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  src/styles/wizard.scss
  stories/wizard/__snapshots__/wizard.stories.storyshot
  stories/wizard/wizard.stories.js
Labels: Enhancement

#3396 fix: remove outdated slider variables [ci visual]
  src/styles/slider.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Bug

#3400 fix(styles): fixed card HC theme borders
  src/styles/theming/common/card/_sap_fiori_hc.scss
  src/styles/theming/common/card/_sap_horizon_hc.scss
Labels: Bug, Theming, Defect Hunting

#3374 feat: grid list partial items, auto-height, selection labels position fix
  src/styles/grid-list.scss
  stories/list-grid/grid-list.stories.js
Labels: Bug, Horizon Delta

#3380 feat(styles): add delta horizon theming for Carousel
  src/styles/carousel.scss
  src/styles/message-page.scss
  src/styles/theming/common/carousel/_sap_fiori.scss
  src/styles/theming/common/carousel/_sap_fiori_hc.scss
  src/styles/theming/common/carousel/_sap_horizon.scss
  src/styles/theming/common/carousel/_sap_horizon_hc.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/carousel/carousel.stories.js
Labels: Horizon Delta

#3392 fix(styles): calendar horizon issues
  src/styles/calendar.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/calendar/calendar.stories.js
Labels: Bug, Theming, Horizon Delta

#3395 fix(styles): safari switch outline visibility
  src/styles/switch.scss
  src/styles/theming/common/switch/_sap_fiori.scss
  src/styles/theming/common/switch/_sap_horizon.scss
Labels: Theming, Horizon Delta

#3397 fix(styles): dynamic page subtitle color
  src/styles/dynamic-page.scss
Labels: Bug, Theming, Horizon Delta

#3403 fix(styles): add fix for User Menu search field
  stories/user-menu/__snapshots__/user-menu.stories.storyshot
  stories/user-menu/user-menu.stories.js
Labels: Bug, Defect Hunting

#3398 fix(styles): avatar and group issues fixes
  .storybook/custom/custom.scss
  src/styles/avatar-group.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Bug, Defect Hunting, Horizon Delta

#3407 fix(styles): popover arrow styles
  src/styles/popover.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Bug, Defect Hunting

#3406 fix(styles): shellbar various issues
  src/styles/shellbar.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/shellbar/shellbar.stories.js
Labels: Bug, Defect Hunting

#3399 fix(styles): fixed checkbox spacing when label is empty
  src/styles/checkbox.scss
Labels: Bug, Defect Hunting

#3404 fix(styles): micro process flow icon overlay
  src/styles/micro-process-flow.scss
Labels: Bug, Theming, Horizon Delta

#3402 fix(styles): add fix for focus in active state
  src/styles/product-switch.scss
Labels: Bug, Defect Hunting

#3411 fix(styles): add fix for focus color on active state for Horizon
  src/styles/menu.scss
  src/styles/theming/common/menu/_sap_fiori.scss
  src/styles/theming/common/menu/_sap_horizon.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Horizon Delta

#3417 fix(styles): shellbar css specificity & styles from ngx
  src/styles/shellbar.scss
Labels: Theming, Horizon Delta

#3418 fix(styles): add fix for control button states in Input Groups
  src/styles/mixins/_forms.scss
  src/styles/mixins/_mixins.scss
  src/styles/theming/common/input-group/_sap_horizon_hc.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Defect Hunting, Horizon Delta

#3421 fix(styles): fixed focus outlines and examples for Grid List
  src/styles/grid-list.scss
  src/styles/theming/common/grid-list/_sap_fiori.scss
  src/styles/theming/common/grid-list/_sap_horizon.scss
  src/styles/theming/common/grid-list/_sap_horizon_hc.scss
  src/styles/theming/sap_horizon_hcb.scss
Labels: Theming, Defect Hunting

#3433 fix(fn): fix missing box-shadow for macOS inputs [ci visual]
  src/fn/fn-input.scss
Labels: Bug

#3432 fix(styles): overflow menu radius
  src/styles/menu.scss
Labels: Bug, Horizon Delta

#3423 fix(styles): checkbox and radio border radius
  src/styles/checkbox.scss
  src/styles/micro-process-flow.scss
  src/styles/mixins/_forms.scss
  src/styles/mixins/_mixins.scss
  src/styles/radio.scss
  src/styles/theming/common/button/_sap_fiori_hc.scss
  src/styles/theming/common/button/_sap_horizon_hc.scss
  src/styles/theming/common/card/_sap_fiori_hc.scss
  src/styles/theming/common/card/_sap_horizon_hc.scss
  src/styles/theming/common/carousel/_sap_fiori_hc.scss
  src/styles/theming/common/carousel/_sap_horizon_hc.scss
  src/styles/theming/common/checkbox/_common.scss
  src/styles/theming/common/checkbox/_sap_fiori_hc.scss
  src/styles/theming/common/checkbox/_sap_foiri.scss
  src/styles/theming/common/checkbox/_sap_horizon.scss
  src/styles/theming/common/checkbox/_sap_horizon_hc.scss
  src/styles/theming/common/grid-list/_sap_horizon_hc.scss
  src/styles/theming/common/icon-tab-bar/_sap_fiori_hc.scss
  src/styles/theming/common/icon-tab-bar/_sap_horizon_hc.scss
  src/styles/theming/common/radio/_common.scss
  src/styles/theming/common/radio/_sap_fiori.scss
  src/styles/theming/common/radio/_sap_fiori_hc.scss
  src/styles/theming/common/radio/_sap_horizon.scss
  src/styles/theming/common/radio/_sap_horizon_hc.scss
  src/styles/theming/common/slider/_sap_fiori_hc.scss
  src/styles/theming/common/slider/_sap_horizon_hc.scss
  src/styles/theming/common/splitter/_sap_fiori_hc.scss
  src/styles/theming/common/splitter/_sap_horizon_hc.scss
  src/styles/theming/common/table/_sap_horizon_hc.scss
  src/styles/theming/common/wizard/_sap_fiori_hc.scss
  src/styles/theming/common/wizard/_sap_horizon_hc.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming, Horizon Delta

#3444 fix(styles): dialog body corner radius in mobile mode
  src/styles/dialog.scss
Labels: Bug

#3445 fix(styles): micro process flow horizon hc
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Bug, Horizon Delta

#3443 fix(styles): quick view background [ci visual]
  src/styles/quick-view.scss
Labels: Bug

#3409 fix(styles): fixed link underline in HCB
  src/styles/link.scss
  src/styles/mixins/_mixins.scss
  src/styles/theming/common/link/_sap_fiori.scss
  src/styles/theming/common/link/_sap_fiori_hc.scss
  src/styles/theming/common/link/_sap_horizon.scss
  src/styles/theming/common/link/_sap_horizon_hc.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Theming

#3448 fix(styles): layout grid nested rows
  src/styles/layout-grid.scss
Labels: Bug

#3441 fix(styles): remove pop-in border right [ci visual]
  src/styles/table.scss
Labels: Bug

#3425 fix(chore): wizard various fixes
  src/styles/theming/common/wizard/_sap_fiori.scss
  src/styles/theming/common/wizard/_sap_fiori_hc.scss
  src/styles/theming/common/wizard/_sap_horizon.scss
  src/styles/theming/common/wizard/_sap_horizon_hc.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  src/styles/wizard.scss
Labels: Bug, Horizon Delta

#3435 fix(styles): tabs hc themes various fixes
  src/styles/tabs.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/tabs/tabs.stories.js
Labels: Bug, Horizon Delta

#3451 fix(styles): vertical navigation focus outlines for horizon [ci visual]
  src/styles/mixins/vertical-nav/_vertical-nav-navigation.scss
  src/styles/theming/common/vertical-nav/_sap_fiori.scss
  src/styles/theming/common/vertical-nav/_sap_horizon.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Bug, stale

#3447 fix(styles): rating indicator horizon
  src/styles/rating-indicator.scss
  src/styles/theming/common/rating-indicator/_sap_fiori.scss
  src/styles/theming/common/rating-indicator/_sap_fiori_hc.scss
  src/styles/theming/common/rating-indicator/_sap_horizon.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: stale, Horizon Delta

#3438 fix(styles): fix the button states in expanded Select [ci visual]
  src/styles/mixins/_forms.scss
  src/styles/select.scss
  src/styles/theming/common/select/_sap_fiori.scss
  src/styles/theming/common/select/_sap_horizon.scss
  src/styles/theming/common/select/_sap_horizon_hc.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
Labels: Bug, Horizon Delta

#3478 chore(deps-dev): update storybook addons [ci visual]
  package.json
Labels: Dependencies

#3483 chore(deps-dev): bump @sap-theming/theming-base-content from 11.1.38 to 11.1.39 [ci visual]
  package.json
Labels: Dependencies

#3430 fix(styles): toolbar info mode styling, grid list toolbar
  src/styles/grid-list.scss
  src/styles/theming/common/grid-list/_sap_fiori.scss
  src/styles/theming/common/grid-list/_sap_horizon.scss
  src/styles/theming/common/grid-list/_sap_horizon_hc.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  src/styles/toolbar.scss
  stories/list-grid/grid-list.stories.js
Labels: Bug, Horizon Delta

#3477 fix(styles): menu focus outline [ci visual]
  src/styles/menu.scss
Labels: Bug, Defect Hunting, Horizon Delta

#3494 fix: add missing switch variables
  src/styles/switch.scss
  src/styles/theming/common/switch/_sap_fiori.scss
  src/styles/theming/common/switch/_sap_fiori_hc.scss
  src/styles/theming/common/switch/_sap_horizon.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
Labels: Bug, Enhancement, Theming, Horizon Delta

#3465 fix(styles): input field readonly state fixes and adaptations
  src/styles/mixins/_forms.scss
  src/styles/theming/common/input/_sap_fiori.scss
  src/styles/theming/common/input/_sap_horizon.scss
Labels: Theming, Defect Hunting, Horizon Delta

#3474 fix(styles): tile horizon adaptation fixes
  src/styles/theming/common/tile/_sap_fiori.scss
  src/styles/theming/common/tile/_sap_fiori_hc.scss
  src/styles/theming/common/tile/_sap_horizon.scss
  src/styles/theming/common/tile/_sap_horizon_hc.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  src/styles/tile.scss
  stories/generic-tile/generic-tile.stories.js
Labels: Theming, Defect Hunting, Horizon Delta

#3493 fix(styles): border radius should not come from quick view first child
  src/styles/quick-view.scss
Labels: Bug

#3498 fix(ci): fixed sync-components script compatibility with windows
  scripts/sync-components.js
Labels: tooling

#3429 fix(styles): horizon progress indicator
  src/styles/progress-indicator.scss
  src/styles/theming/common/progress-indicator/sap_fiori.scss
  src/styles/theming/common/progress-indicator/sap_fiori_hc.scss
  src/styles/theming/common/progress-indicator/sap_horizon.scss
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_fiori_3_dark.scss
  src/styles/theming/sap_fiori_3_hcb.scss
  src/styles/theming/sap_fiori_3_hcw.scss
  src/styles/theming/sap_fiori_3_light_dark.scss
  src/styles/theming/sap_horizon.scss
  src/styles/theming/sap_horizon_dark.scss
  src/styles/theming/sap_horizon_hcb.scss
  src/styles/theming/sap_horizon_hcw.scss
  stories/progress-indicator/progress-indicator.stories.js
Labels: Theming, stale, Horizon Delta

#3502 docs(styles): fix icon button docs
  stories/button/button.stories.js
Labels: storybook

#3503 test(styles): update forgotten storyshots
  stories/action-bar/__snapshots__/action-bar.stories.storyshot
  stories/action-sheet/__snapshots__/action-sheet.stories.storyshot
  stories/busy-indicator/__snapshots__/busy-indicator.stories.storyshot
  stories/calendar/__snapshots__/calendar.stories.storyshot
  stories/card/__snapshots__/card.stories.storyshot
  stories/carousel/__snapshots__/carousel.stories.storyshot
  stories/feed-list/__snapshots__/feed-list.stories.storyshot
  stories/list-grid-select/__snapshots__/grid-list-select.stories.storyshot
  stories/list-grid/__snapshots__/grid-list.stories.storyshot
  stories/list/standard/__snapshots__/standard-list.stories.storyshot
  stories/menu/__snapshots__/menu.stories.storyshot
  stories/popover/__snapshots__/popover.stories.storyshot
  stories/progress-indicator/__snapshots__/progress-indicator.stories.storyshot
  stories/shellbar/__snapshots__/shellbar.stories.storyshot
  stories/slider/__snapshots__/slider.stories.storyshot
  stories/splitter/__snapshots__/splitter.stories.storyshot
  stories/tree/__snapshots__/tree.stories.storyshot
Labels: storybook
