Repository SAP/fundamental-styles, pull requests merged in 2022-08, with the labels that each got.

#3759 fix(styles): add cursor pointer to links
  src/styles/mixins/_mixins.scss
Labels: stale

#3764 feat(styles): sap font stylesheets
  package.json
  src/fonts/sap_fiori_3_fonts.scss
  src/fonts/sap_fonts.scss
  src/fonts/sap_horizon_fonts.scss
Labels: Enhancement

#3765 fix(styles): byline list thumbnail issue in safari
  src/styles/mixins/list/_list-byline.scss
Labels: Bug

#3783 fix(styles): notification mobile
  src/styles/notification.scss
Labels: Bug

#3784 docs(styles): fix icon broken link
  stories/icon/SAPIcons/icon.stories.js
Labels: documentation

#3796 chore(deps): update storybook version 6.5.10
  package.json
  yarn.lock
Labels: Dependencies, storybook

#3767 fix(styles): form grid margins & paddings issues
  src/styles/form-group.scss
  src/styles/form-item.scss
  src/styles/form-layout-grid.scss
  stories/checkbox/__snapshots__/checkbox.stories.storyshot
  stories/checkbox/checkbox.stories.js
  stories/dialog/__snapshots__/dialog.stories.storyshot
  stories/dialog/dialog.stories.js
  stories/form-fieldset/__snapshots__/form-fieldset.stories.storyshot
  stories/form-fieldset/form-fieldset.stories.js
  stories/form-grid/__snapshots__/form-grid.stories.storyshot
  stories/form-grid/form-grid.stories.js
  stories/form-group/__snapshots__/form-group.stories.storyshot
  stories/form-group/form-group.stories.js
  stories/input-group/__snapshots__/input-group.stories.storyshot
  stories/radio/__snapshots__/radio.stories.storyshot
  stories/radio/radio.stories.js
Labels: Bug

#3812 chore(ci): remove stale workflow
  .github/workflows/stale.yml
Labels: Dependencies

#3813 fix(styles): update InfoLabel design [ci visual]
  src/styles/info-label.scss
Labels: design review changes

#3817 feat(styles): bring SAP-icons version 4.14 [ci visual]
  package.json
  src/styles/icons/_settings.scss
  stories/icon/SAPIcons/__snapshots__/icon.stories.storyshot
  stories/icon/SAPIcons/data.json
  yarn.lock
Labels: Dependencies, design review changes

#3822 feat(styles): add display and sr-only to helpers [ci visual]
  .storybook/custom/styleChangers/dev/componentStylesManager.js
  .storybook/custom/styleChangers/prod/componentStylesManager.js
  src/common-css/_common-settings.scss
  src/common-css/common-css.scss
  src/common-css/sap-display.scss
  src/common-css/sap-sr-only.scss
  src/styles/helpers.scss
  src/styles/helpers/_display.scss
  stories/Helpers/display/__snapshots__/display.stories.storyshot
  stories/Helpers/display/display.stories.js
Labels: common-css
