Repository SAP/fundamental-styles, pull requests merged in 2022-11, with the labels that each got.

#3989 feat(styles): adopt Fiori Scrollbar for all components with scrollable area
  packages/styles/src/menu.scss
  packages/styles/src/mixins/_mixins.scss
  packages/styles/src/panel.scss
  packages/styles/src/popover.scss
  packages/styles/src/product-switch.scss
  packages/styles/src/scrollbar.scss
  packages/styles/src/table.scss
  packages/styles/src/textarea.scss
  packages/styles/src/theming/common/scrollbar/_sap_fiori.scss
  packages/styles/src/theming/common/scrollbar/_sap_horizon.scss
Labels: Enhancement, dxp

#3992 fix(e2e): storybook tests issue fix
  packages/doc-ui/src/components/Community.tsx
  packages/styles/tests/__snapshots__/styles.test.ts.snap
  packages/styles/tests/styles.test.ts
Labels: tooling

#3994 fix(styles): update radio label color [ci visual]
  packages/styles/src/radio.scss
Labels: Horizon Delta

#3991 fix(styles): button horizon and v1 preparations
  packages/styles/src/button-split.scss
  packages/styles/src/button.scss
  packages/styles/src/mixins/_states.scss
  packages/styles/src/mixins/button/_button-badge.scss
  packages/styles/src/mixins/button/_button-helper.scss
  packages/styles/src/mixins/button/_button-types.scss
  packages/styles/src/mixins/button/_transparent.scss
  packages/styles/src/segmented-button.scss
  packages/styles/stories/Components/bar/bar.stories.js
  packages/styles/stories/Components/button/button.stories.js
  packages/styles/stories/Components/calendar/calendar.stories.js
  packages/styles/stories/Components/message-popover/message-popover.stories.js
  packages/styles/stories/Components/panel/panel.stories.js
  packages/styles/stories/Components/popover/popover.stories.js
  packages/styles/stories/Patterns/datepicker/datepicker.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug, code refactoring, version 1.0

#4008 chore(deps): updated SAP theming package and adopted changes
  package.json
  packages/styles/src/icons/_settingsBusiness.scss
  packages/styles/stories/Components/Icons/icon/BusinessSuiteInAppSymbols/dataBusinessSuite.json
  yarn.lock
Labels: Dependencies, documentation

#4009 fix: incorrect output path of build
  packages/workspace-plugins/src/executors/build/executor.ts
Labels: Bug, tooling, high priority

#4010 chore(deps-dev): removed postcss-custom-properties
  package.json
  packages/workspace-plugins/src/executors/shared/postcss.plugins.ts
  yarn.lock
Labels: tooling

#4007 fix(styles): last item in menu list border radius issue
  packages/styles/src/menu.scss
Labels: Bug

#3913 feat(cx): introduce Side Nav
  .storybook/static/preview-head.js
  packages/cx/project.json
  packages/cx/src/_nested-list.scss
  packages/cx/src/fundamental-cx.scss
  packages/cx/src/side-nav.scss
  packages/cx/stories/Components/cx-side-navigation/cx-side-navigation.stories.js
  packages/styles/stories/Deprecated/Components/side-navigation/side-navigation.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Enhancement

#3922 feat(styles): add text color and background color to common css
  packages/common-css/src/_common-mixins.scss
  packages/common-css/src/common-css.scss
  packages/common-css/src/sap-colors.scss
  packages/common-css/stories/colors/colors.stories.js
Labels: common-css

#4014 chore(styles): moved away btp variables into separate files
  packages/styles/src/theming/btp-colors/_sap_horizon.scss
  packages/styles/src/theming/btp-colors/_sap_horizon_dark.scss
  packages/styles/src/theming/btp-colors/_sap_horizon_hcb.scss
  packages/styles/src/theming/btp-colors/_sap_horizon_hcw.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
Labels: Theming, code refactoring

#4012 feat(styles): add styles to combobox in shellbar
  packages/styles/src/shellbar.scss
Labels: Enhancement, styling

#4016 feat(styles): added interactive upload collection item
  packages/styles/src/mixins/list/_list-base.scss
  packages/styles/src/upload-collection.scss
  packages/styles/stories/Components/upload-collection/upload-collection.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Theming

#4015 fix(styles): fix shellbar styles for input-group and addon
  packages/styles/src/shellbar.scss
Labels: Bug, styling

#4013 test(styles,cx): switch to 2 horizon themes in chromatic [ci visual]
  packages/cx/project.json
  packages/styles/project.json
Labels: tooling, Visual Testing

#4021 fix(cx): add cx namespace for side nav
  packages/common-css/stories/elevation/elevation.stories.js
  packages/common-css/stories/overflow/overflow.stories.js
  packages/cx/src/_nested-list.scss
  packages/cx/src/_settings.scss
  packages/cx/src/side-nav.scss
  packages/cx/stories/Components/cx-side-navigation/cx-side-navigation.stories.js
Labels: CX

#4024 fix(docs): moved jsdoc story descriptions to parameters
  packages/styles/stories/Components/Forms/input/input.stories.js
  packages/styles/stories/Components/Icons/icon/BusinessSuiteInAppSymbols/iconBusinessSuite.stories.js
  packages/styles/stories/Components/Icons/icon/SAPIcons/icon.stories.js
  packages/styles/stories/Components/Icons/icon/TNTIcons/iconTnt.stories.js
  packages/styles/stories/Components/info-label/info-label.stories.js
  packages/styles/stories/Components/object-marker/object-marker.stories.js
  packages/styles/stories/Components/object-number/object-number.stories.js
  packages/styles/stories/Components/object-status/object-status.stories.js
Labels: storybook, documentation, code refactoring

#4025 fix(cx): add fixes after design review [ci visual]
  packages/cx/src/_nested-list.scss
  packages/cx/src/side-nav.scss
  packages/cx/stories/Components/cx-side-navigation/cx-side-navigation.stories.js
Labels: CX

#4020 feat(common-css): add initial normalize styles to commonCSS package
  packages/common-css/src/sap-normalize.scss
Labels: common-css

#4026 fix(styles): popover horizon and v1 refactoring
  packages/styles/src/mixins/_mixins.scss
  packages/styles/src/mixins/_popover.scss
  packages/styles/src/popover.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/stories/Components/Forms/form-message/form-message.stories.js
  packages/styles/stories/Components/Forms/input/input.stories.js
  packages/styles/stories/Components/Forms/textarea/textarea.stories.js
  packages/styles/stories/Components/popover/popover.stories.js
  packages/styles/stories/Deprecated/Components/side-navigation/side-navigation.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon Delta

#4044 fix(styles): add minor changes after design review [ci visual]
  packages/styles/src/timepicker.scss
  packages/styles/stories/Components/timepicker/timepicker.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: CX

#4043 feat(styles): add Uploaded Files section to File Uploader [ci visual]
  packages/styles/src/file-uploader.scss
  packages/styles/src/object-list.scss
  packages/styles/src/object-status.scss
  packages/styles/src/theming/common/file-uploader/_sap_fiori.scss
  packages/styles/src/theming/common/file-uploader/_sap_fiori_hc.scss
  packages/styles/src/theming/common/file-uploader/_sap_horizon.scss
  packages/styles/src/theming/common/file-uploader/_sap_horizon_hc.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/src/upload-collection.scss
  packages/styles/stories/Components/file-uploader/file-uploader.stories.js
  packages/styles/stories/Components/object-list/object-list.stories.js
  packages/styles/stories/Components/object-status/object-status.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: version 1.0, CX

#3974 docs(common-css): common css readme
  .gitignore
  packages/common-css/README.md
Labels: documentation

#4055 fix(styles): dynamic page buttons styling
  packages/styles/src/dynamic-page.scss
  packages/styles/src/theming/common/dynamic-page-layout/_sap_fiori.scss
  packages/styles/src/theming/common/dynamic-page-layout/_sap_horizon.scss
Labels: dxp
