Repository SAP/fundamental-styles, pull requests merged in 2022-09, with the labels that each got.

#3816 feat(styles): add flex to common css (helpers)
  .storybook/main.js
  src/common-css/common-css.scss
  src/common-css/sap-flex.scss
  src/styles/helpers.scss
  src/styles/helpers/_flex.scss
  stories/Helpers/flex/__snapshots__/flex.stories.storyshot
  stories/Helpers/flex/flex.stories.js
Labels: common-css

#3836 fix(styles): add fix for Table footer background [ci visual]
  src/styles/table.scss
Labels: Bug

#3857 fix(styles): feed-list-item horizon & fixes
  src/styles/feed-list.scss
  src/styles/theming/common/feed-list-item/_sap_fiori.scss
  src/styles/theming/common/feed-list-item/_sap_horizon.scss
  stories/feed-list/__snapshots__/feed-list.stories.storyshot
  stories/feed-list/feed-list.stories.js
Labels: Bug

#3856 fix(styles): card title, subtitle font-size
  src/styles/card.scss
  src/styles/theming/common/card/_sap_fiori.scss
  src/styles/theming/common/card/_sap_horizon.scss
Labels: Bug

#3840 fix(styles): combobox row height
  src/styles/mixins/list/_list-dropdown.scss
Labels: Bug

#3855 fix(styles): button fonts
  src/fonts/sap_fonts.scss
  src/styles/button.scss
  src/styles/theming/common/button/_sap_fiori.scss
  src/styles/theming/common/button/_sap_horizon.scss
  src/styles/theming/common/button/_sap_horizon_hc.scss
Labels: Bug

#3853 fix(docs): icon fonts switching, unloading theme variables bug
  .storybook/custom/custom.scss
  .storybook/custom/loaders/load-styles.js
  .storybook/custom/styleChangers/dev/themeVariablesManager.js
  .storybook/custom/styleChangers/prod/themeVariablesManager.js
  .storybook/custom/styleChangers/utils/inlineStyleLazyLoader.js
  .storybook/main.js
  .storybook/preview-head.html
Labels: Bug

#3859 feat(styles): add many elements to common css
  .storybook/preview-head.html
  src/common-css/_common-mixins.scss
  src/common-css/common-css.scss
  src/common-css/sap-content-paddings.scss
  src/common-css/sap-margin.scss
  src/common-css/sap-media-queries.scss
  src/common-css/sap-shadow.scss
  src/common-css/sap-typography.scss
  stories/Helpers/content-paddings/__snapshots__/content-paddings.stories.storyshot
  stories/Helpers/content-paddings/__snapshots__/display.stories.storyshot
  stories/Helpers/content-paddings/content-paddings.stories.js
  stories/Helpers/margin/__snapshots__/display.stories.storyshot
  stories/Helpers/margin/__snapshots__/margin.stories.storyshot
  stories/Helpers/margin/margin.stories.js
  stories/Helpers/media-queries/__snapshots__/display.stories.storyshot
  stories/Helpers/media-queries/__snapshots__/media-queries.stories.storyshot
  stories/Helpers/media-queries/media-queries.stories.js
  stories/Helpers/shadow/__snapshots__/display.stories.storyshot
  stories/Helpers/shadow/__snapshots__/shadow.stories.storyshot
  stories/Helpers/shadow/shadow.stories.js
  stories/Helpers/typography/__snapshots__/display.stories.storyshot
  stories/Helpers/typography/__snapshots__/typography.stories.storyshot
  stories/Helpers/typography/typography.stories.js
Labels: common-css

#3861 feat(styles): add Border-radius to common css
  src/common-css/common-css.scss
  src/common-css/sap-border-radius.scss
  stories/Helpers/border-radius/__snapshots__/border-radius.stories.storyshot
  stories/Helpers/border-radius/border-radius.stories.js
Labels: common-css

#3843 fix(styles): full height to shellbar select
  src/styles/shellbar.scss
Labels: styling

#3842 fix(styles): there should be no compact object list
  src/styles/mixins/list/_list-base.scss
  src/styles/mixins/list/_list-definitions.scss
Labels: Bug

#3838 fix(styles): form layout grid
  src/styles/form-layout-grid.scss
  stories/form-grid/__snapshots__/form-grid.stories.storyshot
  stories/form-grid/form-grid.stories.js
Labels: Bug

#3869 fix(docs): docs container width
  .storybook/custom/DocsPage.scss
Labels: Bug, Doc website

#3839 fix(docs): stories order
  babel.config.js
  package.json
  yarn.lock
Labels: Enhancement, blocked

#3867 fix(styles): form message in popover
  src/styles/popover.scss
Labels: Bug

#3880 fix(docs): chromatic build issue
  scripts/build-visual-stories.js
Labels: Bug, Doc website, storybook

#3881 fix(common-css): move all mixins in 1 file and publish them
  scripts/copy-common-css-readme-and-package.js
  src/common-css/_common-mixins.scss
  src/common-css/common-css.scss
  src/common-css/sap-border-radius.scss
  src/common-css/sap-content-paddings.scss
  src/common-css/sap-display.scss
  src/common-css/sap-flex.scss
  src/common-css/sap-margin.scss
  src/common-css/sap-media-queries.scss
  src/common-css/sap-padding.scss
  src/common-css/sap-shadow.scss
  src/common-css/sap-sr-only.scss
  src/common-css/sap-typography.scss
  stories/Helpers/padding/padding.stories.js
Labels: common-css

#3893 fix(common-css): add flex direction as input to all flex mixins
  src/common-css/_common-mixins.scss
Labels: common-css

#3882 fix(docs): examples container width
  .storybook/custom/custom.scss
Labels: Bug, Doc website

#3818 feat(styles): notification in dialog
  src/styles/notification.scss
  stories/notification/__snapshots__/notification.stories.storyshot
  stories/notification/notification.stories.js
Labels: Enhancement
