Repository SAP/fundamental-styles, pull requests merged in 2022-10, with the labels that each got.

#3908 fix(styles): reset input-field hover style in input-group
  src/styles/input-group.scss
Labels: Defect Hunting

#3898 fix(styles): tokenizer not rendering as compact
  src/styles/tokenizer.scss
Labels: Bug

#3896 fix(styles): link in quick view width bug
  src/styles/quick-view.scss
Labels: Bug

#3909 fix(styles): fix padding of nested list in rtl
  src/styles/nested-list.scss
Labels: Bug, Defect Hunting

#3907 docs(styles): align theme names with the other technologies
  .storybook/custom/components/Header.js
  .storybook/custom/constants/availableThemes.js
  .storybook/custom/decorators/themeProvider.js
  .storybook/preview.js
  README.md
  config/constants.js
  scripts/build-visual-stories.js
  stories/BTP Experimental Design/fn-icons/IconsDocsPage.js
  theming-preview/testsuite.json
  theming-preview/theme-manager.js
Labels: Theming, documentation

#3912 fix(styles): more tokenizer fixes
  src/styles/tokenizer.scss
Labels: Bug

#3899 fix(styles): add full width to grid-list-item content
  src/styles/grid-list.scss
Labels: Defect Hunting

#3921 chore(styles): unify mixing names by adding fd prefix to all of them
  src/styles/card.scss
  src/styles/carousel.scss
  src/styles/checkbox.scss
  src/styles/flexible-column-layout.scss
  src/styles/menu.scss
  src/styles/mixins/_breakpoints.scss
  src/styles/mixins/_forms.scss
  src/styles/mixins/_mixins.scss
  src/styles/nested-list.scss
  src/styles/notification.scss
  src/styles/numeric-content.scss
  src/styles/object-attribute.scss
  src/styles/object-list.scss
  src/styles/popover.scss
  src/styles/product-switch.scss
  src/styles/radio.scss
  src/styles/rating-indicator.scss
  src/styles/tabs.scss
  src/styles/tile.scss
  src/styles/tokenizer.scss
  src/styles/wizard.scss
Labels: code refactoring

#3915 feat(styles): add focus styles to scrollbar
  src/styles/scrollbar.scss
Labels: Defect Hunting, styling

#3940 test(styles): update storyshots for form grid and notification
  stories/form-grid/__snapshots__/form-grid.stories.storyshot
  stories/notification/__snapshots__/notification.stories.storyshot
Labels: storybook

#3938 fix(styles): update font-family for Dialog Header for Horizon
  src/styles/theming/sap_fiori_3.scss
  src/styles/theming/sap_horizon.scss
  src/styles/title.scss
Labels: Horizon Delta

#3926 feat(styles): add border mixin to common-css
  src/common-css/_common-mixins.scss
  stories/Helpers/border/border.stories.js
Labels: common-css

#3942 fix(styles): update Object Status radius
  src/styles/object-status.scss
Labels: Theming, Horizon Delta

#3914 fix(styles): add vertical nav on hover icon color
  src/styles/mixins/vertical-nav/_vertical-nav-navigation.scss
Labels: Defect Hunting, styling

#3957 fix(styles): dialog no horizontal paddings, mobile mode issues
  src/styles/dialog.scss
  stories/dialog/dialog.stories.js
Labels: code refactoring

#3925 feat(styles): add focus to common css
  src/common-css/_common-mixins.scss
  stories/Helpers/focus/focus.stories.js
Labels: common-css

#3964 chore: added nx cloud token
  .github/workflows/chromatic.yml
  .github/workflows/create-hotfix.yml
  .github/workflows/create-release.yml
  .github/workflows/on-pull.yml
  nx.json
Labels: tooling

#3936 fix(styles): notification text containers should use margin, not padding, for spacing [ci visual]
  packages/styles/src/notification.scss
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug

#3963 chore: added common-css as separate package entry
  packages/common-css/index.ts
  packages/common-css/package-config.ts
  packages/common-css/stories/border-radius/border-radius.stories.js
  packages/common-css/stories/border/border.stories.js
  packages/common-css/stories/content-paddings/content-paddings.stories.js
  packages/common-css/stories/display/display.stories.js
  packages/common-css/stories/display/display.story.description.html
  packages/common-css/stories/flex/flex.stories.js
  packages/common-css/stories/focus/focus.stories.js
  packages/common-css/stories/margin/margin.stories.js
  packages/common-css/stories/margin/margin.story.description.html
  packages/common-css/stories/media-queries/media-queries.stories.js
  packages/common-css/stories/media-queries/meta-queries.story.description.html
  packages/common-css/stories/padding/padding.stories.js
  packages/common-css/stories/padding/padding.story.description.html
  packages/common-css/stories/shadow/shadow.stories.js
  packages/common-css/stories/typography/typography.stories.js
  packages/configuration/src/lib/packages.ts
  packages/styles/stories/Helpers/display/display.stories.js
  projects.js
Labels: common-css

#3956 fix(styles): add flex-center to list-title-text
  packages/styles/src/mixins/list/_list-base.scss
Labels: Bug, styling

#3972 chore: fixed order of the packages
  .storybook/preview.ts
Labels: documentation, CX

#3975 docs(common-css): added theming support to the common-css package
  .storybook/preview.ts
  packages/common-css/package-config.ts
  packages/storybook/src/lib/decorators/themeProvider.ts
  projects.js
Labels: Doc website, Theming, documentation, common-css

#3970 feat(common-css): add overflow and elevation to common css
  packages/common-css/src/_common-mixins.scss
  packages/common-css/src/common-css.scss
  packages/common-css/src/sap-elevation.scss
  packages/common-css/src/sap-overflow.scss
  packages/common-css/stories/elevation/elevation.stories.js
  packages/common-css/stories/overflow/overflow.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: common-css

#3987 feat(styles): add border to the Card Footer in Quartz [ci visual]
  packages/styles/src/card.scss
  packages/styles/src/theming/common/card/_sap_fiori.scss
  packages/styles/src/theming/common/card/_sap_horizon.scss
  packages/styles/stories/Components/card/card.stories.js
Labels: Theming
