Repository SAP/fundamental-styles, pull requests merged in 2023-07, with the labels that each got.

#4659 chore(deps): update to storybook version 7.0.25
  package.json
  yarn.lock
Labels: Dependencies, storybook

#4660 chore(deps): update theming-base-content version 11.5.0 [ci visual]
  package.json
  packages/styles/src/icons/_settings.scss
  packages/styles/stories/Components/Icons/icon/SAPIcons/data.json
  packages/styles/tests/__snapshots__/styles.test.ts.snap
  yarn.lock
Labels: Dependencies, Theming

#4664 chore(deps): update storybook, comments cleanup, remove rxcj as dep
  metadata.yaml
  package.json
  packages/styles/src/alert.scss
  packages/styles/src/breadcrumb.scss
  packages/styles/src/button-split.scss
  packages/styles/src/calendar.scss
  packages/styles/src/checkbox.scss
  packages/styles/src/code.scss
  packages/styles/src/counter.scss
  packages/styles/src/dialog.scss
  packages/styles/src/fieldset.scss
  packages/styles/src/form-group.scss
  packages/styles/src/form-header.scss
  packages/styles/src/form-item.scss
  packages/styles/src/form-label.scss
  packages/styles/src/form-message.scss
  packages/styles/src/grid-list.scss
  packages/styles/src/input-group.scss
  packages/styles/src/link.scss
  packages/styles/src/object-marker.scss
  packages/styles/src/object-number.scss
  packages/styles/src/object-status.scss
  packages/styles/src/off-screen.scss
  packages/styles/src/pagination.scss
  packages/styles/src/product-switch.scss
  packages/styles/src/radio.scss
  packages/styles/src/section.scss
  packages/styles/src/segmented-button.scss
  packages/styles/src/switch.scss
  packages/styles/src/table.scss
  packages/styles/src/tabs.scss
  packages/styles/src/textarea.scss
  yarn.lock
Labels: Dependencies, tooling

#4661 fix(styles): update theming-preview examples' markup
  packages/theming-preview/src/button.html
  packages/theming-preview/src/calendar.html
  packages/theming-preview/src/form.html
  packages/theming-preview/src/header-footer.html
  packages/theming-preview/src/icon.html
  packages/theming-preview/src/input.html
  packages/theming-preview/src/object-header.html
  packages/theming-preview/src/panel.html
  packages/theming-preview/src/semantic-colors.html
  packages/theming-preview/src/shell-tile-card.html
  packages/theming-preview/src/table.html
  packages/theming-preview/src/text.html
  packages/theming-preview/src/toolbar.html
Labels: Theming

#4662 fix(styles): update Object Status to latest Horizon 2023 [ci visual]
  config/bundlesize.json
  packages/styles/src/mixins/_states.scss
  packages/styles/src/object-status.scss
  packages/styles/src/theming/common/object-status/_sap_fiori.scss
  packages/styles/src/theming/common/object-status/_sap_fiori_hc.scss
  packages/styles/src/theming/common/object-status/_sap_horizon.scss
  packages/styles/src/theming/common/object-status/_sap_horizon_hc.scss
  packages/styles/src/theming/common/rating-indicator/_sap_horizon_hc.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/stories/Components/object-status/clickable-object-status.example.html
  packages/styles/stories/Components/object-status/inverted-indication.example.html
  packages/styles/stories/Components/object-status/inverted-states.example.html
  packages/styles/stories/Components/object-status/inverted.example.html
  packages/styles/stories/Components/object-status/object-status.stories.js
Labels: Horizon 2023

#4677 fix(styles): update Object Status to the latest design changes
  packages/styles/src/object-status.scss
  packages/styles/src/theming/common/object-status/_sap_fiori.scss
  packages/styles/src/theming/common/object-status/_sap_fiori_hc.scss
  packages/styles/src/theming/common/object-status/_sap_horizon.scss
  packages/styles/src/theming/common/object-status/_sap_horizon_hc.scss
  packages/styles/stories/Components/object-status/inverted-indication-secondary.example.html
  packages/styles/stories/Components/object-status/inverted-indication.example.html
  packages/styles/stories/Components/object-status/inverted-states.example.html
  packages/styles/stories/Components/object-status/object-status.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2023

#4676 chore(styles): update to theming-base-content v.11.6.1 [ci visual]
  package.json
  packages/styles/src/icons/_settingsTNT.scss
  packages/styles/stories/Components/Icons/icon/TNTIcons/dataTNT.json
  packages/styles/tests/__snapshots__/styles.test.ts.snap
  yarn.lock
Labels: Theming

#4679 feat(styles): bring belize
  packages/styles/package-config.ts
  packages/styles/theming/sap_belize.scss
  packages/styles/theming/sap_belize_hcb.scss
  packages/styles/theming/sap_belize_hcw.scss
  packages/styles/theming/sap_belize_plus.scss
  projects.js
Labels: Theming

#4685 docs(styles): quick view styles & examples [ci visual]
  packages/styles/stories/Components/quick-view/no-header.example.html
  packages/styles/stories/Components/quick-view/popover.example.html
Labels: Doc website

#4691 fix(styles): bring Horizon updates for Tokenizer [ci visual]
  packages/styles/src/theming/common/tokenizer/_sap_fiori.scss
  packages/styles/src/theming/common/tokenizer/_sap_horizon.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/src/tokenizer.scss
Labels: Horizon 2023

#4690 fix(styles): add the proper box-shadow for Card in Quartz Theme
  packages/styles/src/card.scss
  packages/styles/src/theming/common/card/_sap_fiori.scss
  packages/styles/src/theming/common/card/_sap_horizon.scss
Labels: Bug

#4686 fix(styles): design review fixes for Icon Tab Bar [ci visual]
  packages/styles/src/icon-tab-bar.scss
  packages/styles/stories/Components/icon-tab-bar/icon-tab-bar.stories.js
  packages/styles/stories/Components/icon-tab-bar/single-click.example.html
  packages/styles/stories/Components/icon-tab-bar/text-only-closable.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2023

#4682 docs(styles): increased bottom margin between interactive elements [ci visual]
  packages/styles/stories/Components/avatar/avatar.stories.js
Labels: Doc website

#4684 docs(styles): fixed typo in horizontal navigation [ci visual]
  packages/styles/stories/Patterns/horizontal-navigation/horizontal-navigation.stories.js
Labels: documentation

#4683 docs(styles): added interactivity to vertical components [ci visual]
  packages/styles/stories/Components/avatar-group/group-type-vertical.example.html
  packages/styles/stories/Components/avatar-group/individual-type-vertical.example.html
Labels: documentation

#4687 fix(styles): update Byline List after design review [ci visual]
  packages/styles/src/mixins/list/_list-base.scss
  packages/styles/src/mixins/list/_list-byline.scss
  packages/styles/src/mixins/list/_list-definitions.scss
  packages/styles/src/mixins/list/_list-navigation.scss
  packages/styles/stories/Components/List/list/byline/long-text.example.html
  packages/styles/stories/Components/List/list/byline/unread-notification.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2023

#4693 test(styles): update storyshots
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: storybook

#4692 chore(deps): upgrade to storybook v. 7.0.27
  package.json
  yarn.lock
Labels: tooling, storybook

#4707 fix(styles): update Info Label to latest Horizon design [ci visual]
  packages/styles/src/info-label.scss
  packages/styles/src/mixins/_mixins.scss
  packages/styles/src/theming/common/info-label/_sap_fiori.scss
  packages/styles/src/theming/common/info-label/_sap_fiori_hc.scss
  packages/styles/src/theming/common/info-label/_sap_horizon.scss
  packages/styles/src/theming/common/info-label/_sap_horizon_hc.scss
  packages/styles/stories/Components/info-label/display-only-info-label.example.html
  packages/styles/stories/Components/info-label/info-label-with-icon.example.html
  packages/styles/stories/Components/info-label/info-label.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: BTP

#4710 feat(styles): add BTP Tool Header and Nested Buttons to Button component
  packages/styles/src/button.scss
  packages/styles/src/theming/common/button/_sap_fiori.scss
  packages/styles/src/theming/common/button/_sap_fiori_hc.scss
  packages/styles/src/theming/common/button/_sap_horizon.scss
  packages/styles/src/theming/common/button/_sap_horizon_hc.scss
  packages/styles/stories/Components/button/button.stories.js
  packages/styles/stories/Components/button/nested.example.html
  packages/styles/stories/Components/button/tool-header.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: BTP

#4722 docs(styles): split button stories [ci visual]
  packages/styles/stories/Components/button-split/button.stories.js
  packages/styles/stories/Components/button-split/split-menu-button.example.html
  packages/styles/stories/Components/button/button.stories.js
  packages/styles/stories/Components/button/icon-and-text.example.html
  packages/styles/stories/Components/button/styles.example.html
  packages/styles/stories/Components/segmented-button/button.stories.js
  packages/styles/stories/Components/segmented-button/segmented-button.example.html
Labels: storybook, documentation

#4726 fix(styles): added missing line
  packages/icons/src/_icon-names.scss
  packages/icons/src/icons.json
Labels: Bug

#4728 docs(cx): migrate storybook [ci visual]
  packages/cx/stories/Components/cx-side-navigation/compact-narrow-overflow.example.html
  packages/cx/stories/Components/cx-side-navigation/compact-narrow-popover.example.html
  packages/cx/stories/Components/cx-side-navigation/compact-narrow.example.html
  packages/cx/stories/Components/cx-side-navigation/compact-wide-icons-nav-collapse.example.html
  packages/cx/stories/Components/cx-side-navigation/compact-wide-icons.example.html
  packages/cx/stories/Components/cx-side-navigation/cosy-narrow-overflow.example.html
  packages/cx/stories/Components/cx-side-navigation/cosy-narrow-popover-dynamic-width.example.html
  packages/cx/stories/Components/cx-side-navigation/cosy-narrow-popover.example.html
  packages/cx/stories/Components/cx-side-navigation/cosy-narrow.example.html
  packages/cx/stories/Components/cx-side-navigation/cosy-wide-icons-levels-multi-click.example.html
  packages/cx/stories/Components/cx-side-navigation/cosy-wide-icons-levels.example.html
  packages/cx/stories/Components/cx-side-navigation/cosy-wide-text-only-levels.example.html
  packages/cx/stories/Components/cx-side-navigation/cozy-wide-icons-search.example.html
  packages/cx/stories/Components/cx-side-navigation/cozy-wide-icons.example.html
  packages/cx/stories/Components/cx-side-navigation/cozy-wide-text-only.example.html
  packages/cx/stories/Components/cx-side-navigation/cx-side-navigation.stories.js
  packages/cx/stories/Components/cx-side-navigation/dynamic-width.example.html
Labels: storybook
