Repository SAP/fundamental-styles, pull requests merged in 2023-09, with the labels that each got.

#4811 chore(deps): upgrade to storybook 7.4.0 [ci visual]
  package.json
  yarn.lock
Labels: tooling, storybook

#4800 fix(styles): link with icon needs inline-flex
  packages/styles/src/link.scss
Labels: Bug

#4825 chore(ci): bump versions
  package.json
Labels: tooling

#4826 chore(ci): fix nx caches
  nx.json
  package.json
Labels: tooling

#4841 fix(styles): icon tab bar nested paddings fix
  packages/styles/src/icon-tab-bar.scss
  packages/styles/stories/Components/icon-tab-bar/text-only-closable.example.html
Labels: Bug

#4840 feat(styles): new BTP Vertical Navigation
  .storybook/static/preview-head.js
  packages/styles/src/fundamental-styles.scss
  packages/styles/src/navigation.scss
  packages/styles/src/theming/common/navigation/_sap_fiori.scss
  packages/styles/src/theming/common/navigation/_sap_fiori_hc.scss
  packages/styles/src/theming/common/navigation/_sap_horizon.scss
  packages/styles/src/theming/common/navigation/_sap_horizon_hc.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/stories/BTP/navigation/navigation-legacy.example.html
  packages/styles/stories/BTP/navigation/navigation-popup-phone.example.html
  packages/styles/stories/BTP/navigation/navigation-popup-tablet.example.html
  packages/styles/stories/BTP/navigation/navigation-popup.example.html
  packages/styles/stories/BTP/navigation/navigation-snapped-tablet.example.html
  packages/styles/stories/BTP/navigation/navigation-snapped.example.html
  packages/styles/stories/BTP/navigation/navigation.example.html
  packages/styles/stories/BTP/navigation/navigation.stories.js
Labels: BTP
