Repository SAP/fundamental-styles, pull requests merged in 2023-11, with the labels that each got.

#4949 docs(styles): make panel button work, rename function [ci visual]
  .storybook/static/preview-head.js
  packages/styles/stories/Components/panel/borderless.example.html
  packages/styles/stories/Components/panel/expandable.example.html
  packages/styles/stories/Components/panel/fixed-height-content.example.html
  packages/styles/stories/Components/panel/transparent.example.html
  packages/styles/stories/Deprecated/Components/side-navigation/complex-cozy-side-nav.example.html
  packages/styles/stories/Deprecated/Components/side-navigation/cozy-grouping.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2023

#4953 feat(styles): add square Nested Button to BTP [ci visual]
  packages/styles/src/button.scss
  packages/styles/stories/BTP/button/button.stories.js
  packages/styles/stories/BTP/button/nested-square.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: BTP

#4951 fix(styles): message popover adjustments
  packages/styles/src/mixins/list/_list-message-view.scss
  packages/styles/src/mixins/list/_list-navigation-indication.scss
Labels: Bug

#4937 docs(styles): dialog updates
  packages/styles/stories/Components/dialog/default-dialog.example.html
  packages/styles/stories/Components/dialog/dialog.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2023

#4966 chore(deps): update storybook v. 7.5.2
  .storybook/main.ts
  package.json
  packages/common-css/stories/introduction.stories.ts
  packages/cx/stories/introduction.stories.ts
  packages/styles/stories/introduction.stories.ts
  stories/docs/compact-docs.stories.ts
  stories/docs/introduction.stories.ts
  yarn.lock
Labels: Dependencies, storybook

#4968 fix(styles): design review finding fixes for generic tag and object status
  package.json
  packages/styles/src/generic-tag.scss
  packages/styles/stories/Components/object-list/object-list.stories.js
  packages/styles/stories/Components/object-list/standart.example.html
  packages/styles/stories/Components/object-status/clickable-object-status.example.html
  packages/styles/stories/Components/object-status/icon-and-text.example.html
  packages/styles/stories/Components/object-status/icon.example.html
  packages/styles/stories/Components/object-status/inverted-states.example.html
  packages/styles/stories/Components/object-status/inverted.example.html
  packages/styles/stories/Components/object-status/large-object-status.example.html
  packages/styles/stories/Components/object-status/primary.example.html
  packages/styles/stories/Components/object-status/truncate-example.example.html
Labels: Horizon 2023

#4967 fix(styles): update Switch to latest design [ci visual]
  package.json
  packages/storybook/src/lib/visual-stories.ts
  packages/styles/src/switch.scss
  packages/styles/src/theming/common/switch/_sap_fiori.scss
  packages/styles/src/theming/common/switch/_sap_horizon.scss
  packages/styles/stories/Components/switch/basic.example.html
  packages/styles/stories/Components/switch/switch.stories.js
  packages/styles/stories/Components/switch/with-text.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2023

#4969 fix(styles): update Title Bar to latest design [ci visual]
  packages/styles/src/title-bar.scss
  packages/styles/stories/BTP/title-bar/desktop.example.html
  packages/styles/stories/BTP/title-bar/mobile.example.html
  packages/styles/stories/BTP/title-bar/tablet.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: BTP

#4982 fix: fixed font path to the sap-theming [ci visual]
  packages/styles/src/fonts/sap_horizon_fonts.scss
Labels: Bug, high priority, high impact

#4984 chore(deps): update to theming-base-content 11.9.0
  package.json
  packages/styles/src/icons/_settingsTNT.scss
  packages/styles/stories/Components/Icons/icon/TNTIcons/dataTNT.json
  yarn.lock
Labels: Dependencies, Theming

#5003 fix(styles): add fix for correct height for Title Bar ToolBar in compact state
  packages/styles/src/toolbar.scss
Labels: Bug

#4997 feat(styles): btp horizontal nav update
  nx.json
  package.json
  packages/styles/src/navigation.scss
  packages/styles/stories/BTP/Navigation/horizontal/navigation-horizontal-expander.example.html
  packages/styles/stories/BTP/Navigation/horizontal/navigation-horizontal.stories.js
Labels: BTP

#5001 fix(styles): update icon font size, line-height [ci visual]
  packages/styles/src/icon-tab-bar.scss
  packages/styles/src/icon.scss
  packages/styles/src/mixins/list/_list-navigation.scss
  packages/styles/src/mixins/vertical-nav/_vertical-nav-navigation.scss
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug

#5017 fix(styles): update Variant Management [ci visual]
  packages/styles/src/title.scss
  packages/styles/src/variant-management.scss
  packages/styles/stories/Components/variant-management/dirty-label.example.html
  packages/styles/stories/Components/variant-management/sizes.example.html
  packages/styles/stories/Components/variant-management/variant-management.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: code refactoring

#5018 fix(common-css): add CSS vars to Common CSS lib for the most used parameters
  packages/common-css/src/_common-mixins.scss
  packages/common-css/src/_common-variables.scss
Labels: common-css
