Repository SAP/fundamental-styles, pull requests merged in 2023-12, with the labels that each got.

#5020 fix(styles): change body border to allow optional footer [ci visual]
  packages/styles/src/layout-panel.scss
Labels: Bug

#5031 chore(deps): bump node version
  .github/actions/bump-version/action.yml
  .github/actions/generate-conventional-release-notes/action.yml
  .github/actions/npm-publish/action.yml
  .nvmrc
  netlify.toml
  package.json
  yarn.lock
Labels: tooling

#5032 chore: fix node18 with node20
  .github/actions/bump-version/action.yml
  .github/actions/generate-conventional-release-notes/action.yml
  .github/actions/npm-publish/action.yml
Labels: tooling

#4906 feat(common-css): copy tool-layout
  package.json
  packages/common-css/src/_common-mixins.scss
  packages/common-css/src/_common-variables.scss
  packages/common-css/src/common-css.scss
  packages/common-css/src/sap-busy-indicator.scss
  packages/common-css/src/sap-heading.scss
  packages/common-css/src/sap-label.scss
  packages/common-css/src/sap-text.scss
  packages/common-css/src/sap-tool-layout.scss
  packages/common-css/stories/busy-indicator/busy-indicator.stories.js
  packages/common-css/stories/busy-indicator/contrast-mode.example.html
  packages/common-css/stories/busy-indicator/desktop.example.html
  packages/common-css/stories/busy-indicator/extended-busy-indicator-inside-message-toast.example.html
  packages/common-css/stories/busy-indicator/extended-busy-indicator.example.html
  packages/common-css/stories/busy-indicator/standard.example.html
  packages/common-css/stories/heading/heading.stories.js
  packages/common-css/stories/heading/levels.example.html
  packages/common-css/stories/label/default-example.example.html
  packages/common-css/stories/label/label.stories.js
  packages/common-css/stories/text/default-example.example.html
  packages/common-css/stories/text/hyphenation.example.html
  packages/common-css/stories/text/max-lines.example.html
  packages/common-css/stories/text/text.stories.js
  packages/common-css/stories/text/whitespace.example.html
  packages/common-css/stories/tool-layout/desktop.example.html
  packages/common-css/stories/tool-layout/mobile.example.html
  packages/common-css/stories/tool-layout/sticky.example.html
  packages/common-css/stories/tool-layout/tablet.example.html
  packages/common-css/stories/tool-layout/tool-layout.stories.js
Labels: common-css

#5043 chore(deps): migrate to storybook v.7.6.4
  package.json
  yarn.lock
Labels: tooling, storybook

#5044 chore(common-css): fix typo in content-paddings storybook
  packages/common-css/stories/content-paddings/content-paddings.stories.js
Labels: common-css

#5046 feat(common-css): add CSS container quesries to common-css [ci visual]
  .stylelintrc.json
  packages/common-css/src/_common-mixins.scss
  packages/common-css/src/sap-container-type.scss
  packages/common-css/src/sap-padding.scss
  packages/common-css/stories/container-queries/container-queries.stories.js
  packages/common-css/stories/container-queries/container-queries.story.description.html
  packages/common-css/stories/content-paddings/content-paddings.stories.js
  packages/common-css/stories/media-queries/meta-queries.story.description.html
  packages/common-css/stories/padding/padding.stories.js
Labels: common-css

#5047 chore: updated nx to latest
  .gitignore
  nx.json
  package.json
  packages/common-css/project.json
  packages/configuration/project.json
  packages/cx/project.json
  packages/doc-ui/project.json
  packages/storybook/project.json
  packages/styles/project.json
  packages/utils/project.json
  packages/workspace-plugins/project.json
  packages/workspace-plugins/src/generators/create-package/files/package/__fileName__/project.json.template
  yarn.lock
Labels: Dependencies

#5050 feat(styles): horizontal nav update
  package.json
  packages/styles/src/navigation.scss
  packages/styles/stories/BTP/Navigation/horizontal/navigation-horizontal-expander.example.html
  packages/styles/stories/BTP/Navigation/horizontal/navigation-horizontal-tablet.example.html
  packages/styles/stories/BTP/Navigation/horizontal/navigation-horizontal.example.html
Labels: BTP

#5049 fix(common-css): missing scss files in distribution
  packages/common-css/project.json
Labels: Bug, high priority, common-css, high impact

#5061 fix(styles): btp nav expander spanned state [ci visual]
  packages/styles/src/navigation.scss
Labels: Bug, BTP

#5062 chore(deps): update storybook version 7.6.5
  package.json
  yarn.lock
Labels: Dependencies, tooling, storybook
