Repository SAP/fundamental-styles, pull requests merged in 2023-10, with the labels that each got.

#4866 feat(styles): add BTP Tool Layout component [ci visual]
  packages/styles/src/fundamental-styles.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/src/tool-layout.scss
  packages/styles/stories/BTP/tool-layout/desktop.example.html
  packages/styles/stories/BTP/tool-layout/mobile.example.html
  packages/styles/stories/BTP/tool-layout/tablet.example.html
  packages/styles/stories/BTP/tool-layout/tool-layout.stories.js
Labels: BTP

#4855 feat(styles): add new BTP Horizontal Navigation [ci visual]
  packages/styles/src/mixins/_states.scss
  packages/styles/src/navigation.scss
  packages/styles/stories/BTP/Navigation/horizontal/navigation-horizontal-tablet.example.html
  packages/styles/stories/BTP/Navigation/horizontal/navigation-horizontal.example.html
  packages/styles/stories/BTP/Navigation/horizontal/navigation-horizontal.stories.js
  packages/styles/stories/BTP/Navigation/vertical/navigation-legacy.example.html
  packages/styles/stories/BTP/Navigation/vertical/navigation-popup-phone.example.html
  packages/styles/stories/BTP/Navigation/vertical/navigation-popup-tablet.example.html
  packages/styles/stories/BTP/Navigation/vertical/navigation-popup.example.html
  packages/styles/stories/BTP/Navigation/vertical/navigation-snapped-tablet.example.html
  packages/styles/stories/BTP/Navigation/vertical/navigation-snapped.example.html
  packages/styles/stories/BTP/Navigation/vertical/navigation.example.html
  packages/styles/stories/BTP/Navigation/vertical/navigation.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: BTP

#4890 fix(styles): add some CSS changes and fix docs bugs [ci visual]
  packages/styles/src/tool-layout.scss
  packages/styles/stories/BTP/tool-layout/desktop.example.html
  packages/styles/stories/BTP/tool-layout/mobile.example.html
  packages/styles/stories/BTP/tool-layout/tablet.example.html
  packages/styles/stories/BTP/tool-layout/tool-layout.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug, BTP

#4874 feat(styles): introduce new Title Bar BTP component [ci visual]
  packages/styles/src/fundamental-styles.scss
  packages/styles/src/title-bar.scss
  packages/styles/src/toolbar.scss
  packages/styles/stories/BTP/Navigation/horizontal/navigation-horizontal.stories.js
  packages/styles/stories/BTP/Navigation/vertical/navigation.stories.js
  packages/styles/stories/BTP/title-bar/desktop.example.html
  packages/styles/stories/BTP/title-bar/mobile.example.html
  packages/styles/stories/BTP/title-bar/tablet.example.html
  packages/styles/stories/BTP/title-bar/title-bar.stories.js
  packages/styles/stories/BTP/tool-header/tool-header.stories.js
  packages/styles/stories/BTP/tool-layout/tool-layout.stories.js
Labels: BTP

#4867 feat(styles): add BTP variant for User Menu [ci visual]
  packages/styles/src/btp/avatar.scss
  packages/styles/src/navigation.scss
  packages/styles/src/user-menu.scss
  packages/styles/stories/BTP/user-menu/user-menu-phone.example.html
  packages/styles/stories/BTP/user-menu/user-menu-tablet.example.html
  packages/styles/stories/BTP/user-menu/user-menu.example.html
  packages/styles/stories/BTP/user-menu/user-menu.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: BTP

#4891 chore: update package.json
  package.json
Labels: tooling

#4892 test: swap checkboxes examples [ci visual]
  packages/styles/stories/Components/Forms/checkbox/inline.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Visual Testing

#4893 chore(deps): migrate to storybook v 7.4.6
  package.json
  yarn.lock
Labels: tooling, storybook, documentation

#4907 fix: shellbar category dropdown box-shadow invisibility
  packages/styles/src/shellbar.scss
Labels: Defect Hunting

#4909 feat(deps): bring theming-base-content version 11.7.0 da and ai icons
  package.json
  packages/styles/src/icons/_settings.scss
  packages/styles/src/icons/_settingsTNT.scss
  packages/styles/stories/Components/Icons/icon/SAPIcons/data.json
  packages/styles/stories/Components/Icons/icon/TNTIcons/dataTNT.json
  packages/styles/tests/__snapshots__/styles.test.ts.snap
  yarn.lock
Labels: Theming

#4913 fix: link focus icon color
  package.json
  packages/styles/src/link.scss
Labels: Bug, Defect Hunting

#4924 fix(styles): rating indicator half star display modes [ci visual]
  package.json
  packages/styles/src/rating-indicator.scss
  packages/styles/stories/Components/rating-indicator/display-mode.example.html
  packages/styles/stories/Components/rating-indicator/non-interactive.example.html
  packages/styles/stories/Components/rating-indicator/rating-indicator.stories.js
Labels: Bug

#4926 fix(styles): half star unification and doc update [ci visual]
  packages/styles/src/rating-indicator.scss
  packages/styles/stories/Components/rating-indicator/disabled.example.html
Labels: Bug

#4928 fix(common-css): change the common-css package
  package.json
  packages/common-css/README.md
  packages/common-css/package.json
  packages/styles/package.json
Labels: tooling

#4929 chore(common-css): update the Common CSS doc
  packages/common-css/README.md
  packages/common-css/package.json
Labels: tooling

#4930 fix(styles): calendar updates [ci visual]
  packages/styles/src/calendar.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/stories/Components/calendar/cal.html
  packages/styles/stories/Components/calendar/days.example.html
  packages/styles/stories/Patterns/datepicker/mobile-landscape.example.html
  packages/styles/stories/Patterns/datepicker/mobile-portrait.example.html
  packages/styles/stories/Patterns/datepicker/today-navigation-button.example.html
  packages/styles/stories/Patterns/datepicker/today-selection-button.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
  packages/theming-preview/src/calendar.html
Labels: Horizon 2023

#4931 fix(styles): visible overflow when more dropdown is available
  packages/doc-ui/src/components/DocsPage/custom.scss
  packages/styles/src/icon-tab-bar.scss
Labels: Bug

#4925 chore: moved btp button examples into the BTP subfolder
  packages/styles/src/button.scss
  packages/styles/stories/BTP/button/button.md
  packages/styles/stories/BTP/button/button.stories.js
  packages/styles/stories/BTP/button/nested.example.html
  packages/styles/stories/BTP/button/tool-header.example.html
  packages/styles/stories/BTP/tool-header/desktop.example.html
  packages/styles/stories/BTP/tool-header/mobile.example.html
  packages/styles/stories/BTP/tool-header/tablet.example.html
  packages/styles/stories/Components/button/button.stories.js
Labels: BTP

#4932 fix(styles): input and select disabled placeholder
  config/bundlesize.json
  packages/styles/src/mixins/_forms.scss
  packages/styles/src/select.scss
  packages/styles/stories/Components/Forms/input/primary.example.html
  packages/styles/stories/Components/select/cozy.example.html
Labels: Bug

#4934 fix(styles): include the tnt font icons for fiori 3
  packages/styles/src/fonts/sap_fiori_3_fonts.scss
Labels: Horizon 2023

#4936 chore(deps): update theming-base-content version 11.8.0 [ci visual]
  package.json
  packages/styles/src/icons/_settings.scss
  packages/styles/stories/Components/Icons/icon/SAPIcons/data.json
  yarn.lock
Labels: Dependencies, Theming
