Repository SAP/fundamental-styles, pull requests merged in 2023-02, with the labels that each got.

#4237 feat: added js to publish
  packages/styles/src/horizontal-navigation.scss
  packages/styles/src/icon-tab-bar.scss
  packages/styles/src/illustrated-message.scss
  packages/styles/src/scrollbar.scss
  packages/styles/src/splitter.scss
  packages/styles/src/theming/common/progress-indicator/_sap_fiori.scss
  packages/styles/src/theming/common/progress-indicator/_sap_fiori_hc.scss
  packages/styles/src/theming/common/progress-indicator/_sap_horizon.scss
  packages/workspace-plugins/src/executors/build/executor.ts
Labels: tooling

#4253 fix(styles): update cx side nav button type
  packages/cx/stories/Components/cx-side-navigation/cx-side-navigation.stories.js
Labels: Bug, Doc website

#4254 chore(styles): fix shellbar storyname
  packages/styles/stories/Components/shellbar/shellbar.stories.js
Labels: storybook

#4257 chore(deps): bump to theming-base-content version 11.1.49 [ci visual]
  package.json
  packages/styles/src/icons/_settings.scss
  packages/styles/stories/Components/Icons/icon/SAPIcons/data.json
  yarn.lock
Labels: Theming

#4271 fix(styles): refactor object status component [ci visual]
  packages/styles/src/object-status.scss
  packages/styles/stories/Components/object-status/object-status.stories.js
Labels: Bug, Defect Hunting

#4272 fix(styles): form input correct margins [ci visual]
  packages/styles/src/input-group.scss
  packages/styles/src/select.scss
  packages/styles/stories/Components/Forms/input-group/input-group.stories.js
  packages/styles/stories/Components/select/select.stories.js
  packages/styles/stories/Patterns/combobox-input/combobox-input.stories.js
  packages/styles/stories/Patterns/datepicker/datepicker.stories.js
  packages/styles/stories/Patterns/multi-combo-box/multi-combo-box.stories.js
  packages/styles/stories/Patterns/multi-input/multi-input.stories.js
Labels: Bug, Defect Hunting

#4280 fix: fixed package.json exports
  packages/workspace-plugins/src/executors/build/executor.ts
Labels: Bug, tooling, high priority

#4281 fix: fixed package.json exports default condition order
  packages/workspace-plugins/src/executors/build/executor.ts
Labels: Bug, high priority

#4154 fix(styles): form message with icon layout, styles & docs refactoring
  packages/styles/src/form-message.scss
  packages/styles/src/input.scss
  packages/styles/src/popover.scss
  packages/styles/stories/Components/Forms/form-message/form-message.stories.js
  packages/styles/stories/Components/Forms/input/input.stories.js
  packages/styles/stories/Components/Forms/textarea/textarea.stories.js
  packages/styles/stories/Components/select/select.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug

#4214 feat(styles): table fixed end columns, fixed footer and refactoring
  packages/styles/src/card.scss
  packages/styles/src/mixins/_mixins.scss
  packages/styles/src/mixins/table/_table-fixed.scss
  packages/styles/src/mixins/table/_table-group-and-tree.scss
  packages/styles/src/mixins/table/_table-no-borders.scss
  packages/styles/src/mixins/table/_table-pop-in.scss
  packages/styles/src/mixins/table/_table-states.scss
  packages/styles/src/table.scss
  packages/styles/src/theming/common/table/_sap_fiori.scss
  packages/styles/src/theming/common/table/_sap_horizon.scss
  packages/styles/stories/Components/card/card.stories.js
  packages/styles/stories/Components/table/table.stories.js
  packages/styles/stories/Layouts/fixed-card-layout/fixed-card-layout.stories.js
  packages/styles/stories/Layouts/resizable-card-layout/resizable-card-layout.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug, code refactoring

#4282 fix: popover wrapper styles overriding custom body class styles
  packages/styles/src/popover.scss
Labels: Bug

#4284 feat(styles): update Panel Layout, add new modifier classes [ci visual]
  packages/styles/src/layout-panel.scss
  packages/styles/stories/Layouts/layout-panel/layout-panel.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Enhancement

#4275 fix(styles): avatar group control height bug
  packages/styles/src/avatar-group.scss
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug

#4285 fix(styles): update Illustrated Messages to latest design [ci visual]
  packages/styles/src/illustrated-message.scss
  packages/styles/stories/Components/illustrated-message/illustrated-message.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: code refactoring

#4296 fix(styles): fix for the font-size of Layout Panel [ci visual]
  packages/styles/src/layout-panel.scss
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: CX

#4298 chore: removed fn from documentation and publish
  .github/workflows/create-hotfix.yml
  .github/workflows/create-release.yml
  .storybook/main.ts
  package.json
  packages/configuration/src/lib/packages.ts
  packages/fn/project.json
  projects.js
  scripts/sync-components.js
Labels: documentation, fn components
