Repository SAP/fundamental-styles, pull requests merged in 2023-05, with the labels that each got.

#4488 feat(styles): splitter with horizon 2023 [ci visual]
  packages/styles/src/splitter.scss
  packages/styles/src/theming/common/splitter/_sap_horizon.scss
  packages/styles/src/theming/common/splitter/_sap_horizon_hc.scss
Labels: Horizon 2023

#4501 fix(styles): add option to wrap long label for checkbox and radio button
  packages/styles/src/checkbox.scss
  packages/styles/src/radio.scss
  packages/styles/stories/Components/Forms/checkbox/checkbox.stories.js
  packages/styles/stories/Components/Forms/form-fieldset/form-fieldset.stories.js
  packages/styles/stories/Components/Forms/radio/radio.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug

#4515 chore(deps): upgrade to storybook v. 7.0.9
  package.json
  yarn.lock
Labels: Dependencies, storybook

#4500 feat(styles): add Horizon 2023 update for Avatar and Avatar Group[ci visual]
  packages/styles/src/_avatar-variables.scss
  packages/styles/src/avatar-group.scss
  packages/styles/src/avatar.scss
  packages/styles/src/mixins/_states.scss
  packages/styles/src/theming/common/avatar-group/_common.scss
  packages/styles/src/theming/common/avatar-group/_sap_fiori.scss
  packages/styles/src/theming/common/avatar-group/_sap_horizon.scss
  packages/styles/src/theming/common/avatar/_common.scss
  packages/styles/src/theming/common/avatar/_sap_fiori.scss
  packages/styles/src/theming/common/avatar/_sap_fiori_hc.scss
  packages/styles/src/theming/common/avatar/_sap_horizon.scss
  packages/styles/src/theming/common/avatar/_sap_horizon_hc.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/stories/Components/avatar-group/avatar-group.stories.js
  packages/styles/stories/Components/avatar/avatar.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2023

#4516 fix(styles): update tile title font size [ci visual]
  packages/styles/src/theming/common/tile/_sap_fiori.scss
  packages/styles/src/theming/common/tile/_sap_horizon.scss
  packages/styles/src/tile.scss
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug

#4518 fix(styles): screenreaders attempting to read icons from content [ci visual]
  packages/cx/src/side-nav.scss
  packages/fn/src/fn-checkbox.scss
  packages/fn/src/fn-switch.scss
  packages/styles/src/checkbox.scss
  packages/styles/src/icons/_settings.scss
  packages/styles/src/icons/_settingsBusiness.scss
  packages/styles/src/icons/_settingsTNT.scss
Labels: Bug

#4533 fix(styles): update List component to latest Horizon [ci visual]
  packages/styles/src/mixins/list/_list-base.scss
  packages/styles/src/mixins/list/_list-definitions.scss
  packages/styles/src/mixins/list/_list-navigation-indication.scss
  packages/styles/src/mixins/list/_list-selection.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/src/tree.scss
  packages/styles/stories/Components/List/list/byline/interractive.example.html
  packages/styles/stories/Components/List/list/standard/action-list.example.html
  packages/styles/stories/Components/List/list/standard/icons.example.html
  packages/styles/stories/Components/List/list/standard/interactive.example.html
  packages/styles/stories/Components/List/list/standard/navigation-indicator.example.html
  packages/styles/stories/Components/List/list/standard/secondary-data.example.html
  packages/styles/stories/Components/List/list/standard/standard-list.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2023

#4535 feat(styles): update Menu to Horizon 2023 [ci visual]
  packages/styles/src/menu.scss
  packages/styles/src/theming/common/menu/_sap_fiori.scss
  packages/styles/src/theming/common/menu/_sap_horizon.scss
  packages/styles/stories/Components/menu/buttons.example.html
  packages/styles/stories/Components/menu/desktop-and-tablet-overflow.example.html
  packages/styles/stories/Components/menu/desktop-and-tablet.example.html
  packages/styles/stories/Components/menu/different-states.example.html
  packages/styles/stories/Components/menu/input.example.html
  packages/styles/stories/Components/menu/menu-icon.example.html
  packages/styles/stories/Components/menu/menu.stories.js
  packages/styles/stories/Components/menu/mobile-cozy-mode.example.html
  packages/styles/stories/Components/menu/segmented-button.example.html
  packages/styles/stories/Components/menu/seperated-items.example.html
  packages/styles/stories/Components/menu/toggle-button.example.html
  packages/styles/stories/Components/menu/with-submenu.example.html
  packages/styles/stories/Patterns/context-menu/with-icon-and-button.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2023

#4554 fix(styles): fix the issue with border bottom of Panel header
  packages/styles/src/panel.scss
Labels: Horizon 2023

#4555 fix(styles): update Message Value State Button of Message Popover to latest Horizon 2023
  packages/styles/src/message-popover.scss
  packages/styles/src/theming/common/message-popover/_sap_fiori.scss
  packages/styles/src/theming/common/message-popover/_sap_horizon.scss
  packages/styles/src/theming/common/message-popover/_sap_horizon_hc.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/stories/Components/message-popover/details-view.example.html
  packages/styles/stories/Components/message-popover/message-popover.stories.js
  packages/styles/stories/Components/message-popover/message-trigger.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2023

#4569 fix(styles): fixed semantics of the popover vertical arrow positioning
  packages/styles/src/popover.scss
  packages/styles/stories/Components/popover/placement.example.html
  packages/styles/stories/Components/popover/popover.stories.js
  packages/styles/stories/Components/popover/resizable.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug
