Repository SAP/fundamental-styles, pull requests merged in 2023-08, with the labels that each got.

#4725 fix(styles): update Pagination with latest BTP Horizon [ci visual]
  packages/styles/src/pagination.scss
  packages/styles/src/theming/common/pagination/_sap_fiori.scss
  packages/styles/src/theming/common/pagination/_sap_horizon.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/stories/Components/pagination/cozy.example.html
  packages/styles/stories/Components/pagination/mobile.example.html
  packages/styles/stories/Components/pagination/pagination.stories.js
  packages/styles/stories/Components/pagination/per-page.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: BTP

#4729 feat(styles): introduce BTP Search field component [ci visual]
  packages/styles/src/button.scss
  packages/styles/src/fundamental-styles.scss
  packages/styles/src/search-field.scss
  packages/styles/src/theming/common/button/_sap_fiori.scss
  packages/styles/src/theming/common/button/_sap_horizon.scss
  packages/styles/src/theming/common/search-field/_sap_fiori.scss
  packages/styles/src/theming/common/search-field/_sap_fiori_hc.scss
  packages/styles/src/theming/common/search-field/_sap_horizon.scss
  packages/styles/src/theming/common/search-field/_sap_horizon_hc.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3/_css_variables.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_dark/_css_variables.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcb/_css_variables.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_hcw/_css_variables.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_fiori_3_light_dark/_css_variables.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon/_css_variables.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_dark/_css_variables.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcb/_css_variables.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/src/theming/sap_horizon_hcw/_css_variables.scss
  packages/styles/stories/Components/search-field/default.example.html
  packages/styles/stories/Components/search-field/search-field.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: BTP

#4741 chore(deps): update theming-base-content v. 11.6.4
  package.json
  yarn.lock
Labels: Theming

#4744 chore(styles): update target horizon colors [ci visual]
  packages/styles/src/theming/sap_horizon/_css_variables.scss
  packages/styles/src/theming/sap_horizon_dark/_css_variables.scss
  packages/styles/src/theming/sap_horizon_hcb/_css_variables.scss
  packages/styles/src/theming/sap_horizon_hcw/_css_variables.scss
Labels: Theming, Horizon 2023

#4743 feat(styles): add BTP nav items
  packages/styles/src/fundamental-styles.scss
  packages/styles/src/navigation-menu.scss
  packages/styles/src/theming/common/navigation-menu/_sap_fiori.scss
  packages/styles/src/theming/common/navigation-menu/_sap_fiori_hc.scss
  packages/styles/src/theming/common/navigation-menu/_sap_horizon.scss
  packages/styles/src/theming/common/navigation-menu/_sap_horizon_hc.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3/_css_variables.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_dark/_css_variables.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcb/_css_variables.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_hcw/_css_variables.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_fiori_3_light_dark/_css_variables.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon/_css_variables.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_dark/_css_variables.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcb/_css_variables.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/src/theming/sap_horizon_hcw/_css_variables.scss
  packages/styles/stories/BTP/navigation-menu/navigation-menu-item-child.example.html
  packages/styles/stories/BTP/navigation-menu/navigation-menu-item-group.example.html
  packages/styles/stories/BTP/navigation-menu/navigation-menu-item.example.html
  packages/styles/stories/BTP/navigation-menu/navigation-menu.stories.js
Labels: BTP

#4758 chore(ci): not needed workflow
  .github/workflows/rebase.yml
Labels: tooling

#4757 chore(ci): add names to the jobs in chromatic.yml [ci visual]
  .github/workflows/chromatic.yml
Labels: tooling

#4756 fix(styles): fix calendar visual issues
  packages/styles/src/calendar.scss
Labels: Bug

#4760 fix(styles): toolbar ejected popover scope [ci visual]
  packages/styles/src/toolbar.scss
Labels: Bug

#4773 fix: removed fn-icons from publish
  .github/workflows/create-release.yml
Labels: tooling

#4783 chore(deps): update to storybook 7.3.2
  package.json
  yarn.lock
Labels: tooling, storybook

#4784 chore(deps): update nx
  .eslintrc.json
  nx.json
  package.json
  packages/common-css/package.json
  packages/common-css/project.json
  packages/configuration/.babelrc
  packages/configuration/project.json
  packages/cx/project.json
  packages/cx/tsconfig.json
  packages/doc-ui/.babelrc
  packages/doc-ui/.eslintrc.json
  packages/doc-ui/project.json
  packages/doc-ui/tsconfig.json
  packages/storybook/.babelrc
  packages/storybook/project.json
  packages/styles/project.json
  packages/theming-preview/project.json
  packages/utils/.babelrc
  packages/utils/project.json
  packages/workspace-plugins/.eslintrc.json
  packages/workspace-plugins/project.json
  packages/workspace-plugins/src/executors/build-theming-preview/executor.ts
  packages/workspace-plugins/src/executors/build-theming-preview/schema.json
  packages/workspace-plugins/src/executors/build/executor.ts
  packages/workspace-plugins/src/executors/build/schema.json
  packages/workspace-plugins/src/executors/shared/postcss.ts
  packages/workspace-plugins/src/executors/visual-stories/index.ts
  packages/workspace-plugins/src/executors/visual-stories/schema.json
  packages/workspace-plugins/src/generators/create-package/files/package/__fileName__/project.json.template
  packages/workspace-plugins/src/generators/create-package/files/package/__fileName__/tsconfig.json.template
  packages/workspace-plugins/src/generators/create-package/generator.ts
  packages/workspace-plugins/src/generators/create-package/schema.json
  packages/workspace-plugins/src/generators/extract-html-sections/index.ts
  packages/workspace-plugins/src/generators/extract-html-sections/schema.json
  yarn.lock
Labels: tooling

#4786 chore: fixed documentation sidebar grouping
  .storybook/main.ts
Labels: Doc website

#4787 chore: removed unnecessary package switcher addon
  .storybook/custom/addons/package-switch/preset.js
  .storybook/custom/addons/package-switch/register.js
  .storybook/custom/addons/package-switch/src/constants.js
  .storybook/custom/addons/package-switch/src/register.jsx
  .storybook/main.ts
  .storybook/preview.ts
  packages/doc-ui/src/components/DocsPage/custom.scss
  packages/doc-ui/src/components/Header.tsx
  packages/doc-ui/src/components/PackageSelect.tsx
  packages/doc-ui/src/components/SAPContainer.tsx
  packages/doc-ui/src/contexts/SAPContext.ts
Labels: Doc website, storybook

#4799 fix(styles): move popover body variables
  package.json
  packages/styles/src/popover.scss
Labels: Bug
