Repository SAP/fundamental-styles, pull requests merged in 2023-03, with the labels that each got.

#4299 fix(styles): fixed table styles should only exist under --fixed [ci visual]
  packages/styles/src/mixins/table/_table-fixed.scss
Labels: Bug

#4300 chore(ci): remove ql check
  .github/workflows/codeql-analysis.yml
Labels: tooling

#4337 feat(styles): add position to common CSS
  packages/common-css/src/_common-mixins.scss
  packages/common-css/src/common-css.scss
  packages/common-css/src/sap-position.scss
  packages/common-css/stories/position/position.stories.js
  packages/common-css/stories/position/position.story.description.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: common-css

#4339 chore(deps): upgrade to theming-base-content version 11.2.1
  .storybook/preview-head.html
  README.md
  package.json
  packages/styles/README.md
  packages/styles/src/fonts/sap_horizon_fonts.scss
  packages/styles/src/icons/_settingsBusiness.scss
  packages/styles/stories/Components/Icons/icon/BusinessSuiteInAppSymbols/dataBusinessSuite.json
  packages/styles/tests/__snapshots__/styles.test.ts.snap
  yarn.lock
Labels: Dependencies, Theming

#4341 fix(styles): add fix for button outline in Safari [ci visual]
  packages/styles/src/button-split.scss
  packages/styles/src/button.scss
  packages/styles/src/mixins/button/_button-helper.scss
  packages/styles/src/mixins/button/_button-types.scss
  packages/styles/src/theming/common/button/_sap_fiori.scss
  packages/styles/src/theming/common/button/_sap_fiori_hc.scss
  packages/styles/src/theming/common/button/_sap_horizon.scss
  packages/styles/src/theming/common/button/_sap_horizon_hc.scss
Labels: Bug

#4352 fix(styles): add fix for multi click Icon Tab Bar [ci visual]
  packages/styles/src/icon-tab-bar.scss
  packages/styles/stories/Components/icon-tab-bar/icon-tab-bar.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug

#4353 fix(styles): remove max height and truncation from texts in Illustrated Messages
  packages/styles/src/illustrated-message.scss
Labels: Bug

#4355 feat(styles): add BTP avatar extension [ci visual]
  packages/styles/src/btp/avatar.scss
  packages/styles/src/fundamental-styles.scss
  packages/styles/stories/BTP/avatar/avatar.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: BTP

#4354 fix(styles): add --mobile class to CX side nav [ci visual]
  packages/cx/src/side-nav.scss
Labels: Enhancement

#4404 fix(styles): simplify compact selector [ci visual]
  packages/styles/src/mixins/_mixins.scss
  packages/styles/src/pagination.scss
Labels: Enhancement

#4405 fix(common-css): remove explicit flex-direction from flex-gap
  packages/common-css/src/sap-flex.scss
Labels: Bug, common-css
