Repository SAP/fundamental-styles, pull requests merged in 2023-01, with the labels that each got.

#4141 fix(styles): pagination button focus styles
  packages/styles/src/pagination.scss
Labels: Bug, Defect Hunting

#4140 fix(styles): input group btn in HC themes
  packages/styles/src/mixins/_forms.scss
  packages/styles/src/theming/common/input-group/_sap_horizon_hc.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
Labels: Bug, Defect Hunting

#4139 fix(styles): input readonly state
  packages/styles/src/mixins/_forms.scss
Labels: Bug

#4155 feat(styles): introduced Dot type in illustrated-message
  packages/styles/src/illustrated-message.scss
  packages/styles/stories/Components/illustrated-message/illustrated-message.stories.js
Labels: Enhancement

#4167 docs(styles): removed the repetitive link to Fundamental Library Styl…
  README.md
Labels: Doc website

#4171 fix(styles): outline-offset of dynamic page header not visible when page is fullscreen
  packages/styles/src/dynamic-page.scss
Labels: Bug, A11y

#4174 docs(styles): update Table to use Toolbar Title [ci visual]
  packages/styles/stories/Components/table/table.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug

#4198 fix(styles): select's, step-input's button border styles in hc [ci visual]
  packages/styles/src/mixins/_forms.scss
  packages/styles/src/select.scss
Labels: Defect Hunting

#4168 fix(styles): add Horizon delta for User Menu [ci visual]
  packages/styles/src/theming/common/user-menu/_sap_fiori.scss
  packages/styles/src/theming/common/user-menu/_sap_horizon.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/src/user-menu.scss
  packages/styles/stories/Components/user-menu/user-menu.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon Delta

#4215 fix(styles): action bar version 1 update [ci visual]
  packages/styles/src/action-bar.scss
  packages/styles/src/mixins/_states.scss
Labels: version 1.0
