Repository SAP/fundamental-styles, pull requests merged in 2023-06, with the labels that each got.

#4571 feat(styles): bring indication colors set to Message Strip [ci visual]
  packages/styles/src/message-strip.scss
  packages/styles/stories/Components/message-strip/message-strip-with-accent-colors.example.html
  packages/styles/stories/Components/message-strip/message-strip.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2023

#4572 chore(deps): theming-base-content version 11.4.2 [ci visual]
  package.json
  yarn.lock
Labels: Dependencies, Theming

#4558 fix(styles): address design review comments regarding Horizon 2023
  .storybook/static/preview-head.js
  packages/styles/src/checkbox.scss
  packages/styles/src/message-popover.scss
  packages/styles/src/mixins/_forms.scss
  packages/styles/src/radio.scss
  packages/styles/src/slider.scss
  packages/styles/src/textarea.scss
  packages/styles/src/theming/common/slider/_sap_fiori.scss
  packages/styles/src/theming/common/slider/_sap_horizon.scss
  packages/styles/src/theming/sap_horizon/_css_variables.scss
  packages/styles/stories/Components/Forms/checkbox/checkbox.stories.js
  packages/styles/stories/Components/Forms/input/primary.example.html
  packages/styles/stories/Components/Forms/radio/interaction-states.example.html
  packages/styles/stories/Components/Forms/radio/radio.stories.js
  packages/styles/stories/Components/Forms/radio/text-truncation.example.html
  packages/styles/stories/Components/Forms/textarea/disabled-and-read-only.example.html
  packages/styles/stories/Components/slider/range.example.html
  packages/styles/stories/Components/slider/standard.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2023

#4573 chore(deps): upgrade storybook 7.0.18
  package.json
  yarn.lock
Labels: Dependencies, storybook

#4603 fix(styles): update and refactor Toolbar [ci visual]
  packages/styles/src/grid-list.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/src/toolbar.scss
  packages/styles/stories/Components/toolbar/alignment.example.html
  packages/styles/stories/Components/toolbar/overflow.example.html
  packages/styles/stories/Components/toolbar/primary.example.html
  packages/styles/stories/Components/toolbar/separator.example.html
  packages/styles/stories/Components/toolbar/toolbar.stories.js
  packages/styles/stories/Components/toolbar/types.example.html
Labels: Horizon 2023

#4621 docs(styles): update page docs
  packages/styles/src/page.scss
  packages/styles/stories/Layouts/page/page.stories.js
Labels: Horizon 2023

#4622 test(styles): update test snapshots
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Visual Testing

#4602 feat(styles): add Horizon 2023 updates for Icon tab Bar [ci visual]
  packages/styles/src/icon-tab-bar.scss
  packages/styles/src/theming/common/icon-tab-bar/_common.scss
  packages/styles/src/theming/common/icon-tab-bar/_sap_fiori.scss
  packages/styles/src/theming/common/icon-tab-bar/_sap_fiori_hc.scss
  packages/styles/src/theming/common/icon-tab-bar/_sap_horizon.scss
  packages/styles/src/theming/common/icon-tab-bar/_sap_horizon_hc.scss
  packages/styles/stories/Components/icon-tab-bar/badge.example.html
  packages/styles/stories/Components/icon-tab-bar/icon-tab-bar.stories.js
  packages/styles/stories/Components/icon-tab-bar/multi-click.example.html
  packages/styles/stories/Components/icon-tab-bar/navigation.example.html
  packages/styles/stories/Components/icon-tab-bar/overflow.example.html
  packages/styles/stories/Components/icon-tab-bar/single-click.example.html
  packages/styles/stories/Components/icon-tab-bar/text-only-closable.example.html
Labels: Horizon 2023

#4608 fix(styles): checkbox refactor and fix the problem with icons in FF
  packages/cx/src/side-nav.scss
  packages/fn/src/fn-checkbox.scss
  packages/fn/src/fn-switch.scss
  packages/styles/src/checkbox.scss
  packages/styles/src/icons/_settings.scss
  packages/styles/src/icons/_settingsBusiness.scss
  packages/styles/src/icons/_settingsTNT.scss
  packages/styles/stories/Components/Forms/checkbox/checkbox.stories.js
  packages/styles/stories/Components/Forms/checkbox/inline.example.html
  packages/styles/stories/Components/Forms/checkbox/required.example.html
  packages/styles/stories/Components/Forms/form-fieldset/checkbox-groups.example.html
  packages/styles/stories/Components/Grid List/list-grid-select/multi-select-mode.example.html
  packages/styles/stories/Components/List/list/byline/selection-and-navigation.example.html
  packages/styles/stories/Components/List/list/byline/selection.example.html
  packages/styles/stories/Components/List/list/standard/selection.example.html
  packages/styles/stories/Components/dialog/selectable.example.html
  packages/styles/stories/Components/tree/selection.example.html
  packages/styles/stories/Patterns/multi-combo-box/as-form-item.example.html
  packages/styles/stories/Patterns/multi-combo-box/filtering.example.html
  packages/styles/stories/Patterns/multi-combo-box/grouping.example.html
  packages/styles/stories/Patterns/multi-combo-box/match-popover-body-size.example.html
  packages/styles/stories/Patterns/multi-combo-box/mobile-mode.example.html
  packages/styles/stories/Patterns/multi-combo-box/semantic.example.html
  packages/styles/stories/Patterns/multi-combo-box/two-column-combo-box.example.html
  packages/styles/stories/Patterns/multi-input/as-form-item.example.html
  packages/styles/stories/Patterns/multi-input/filtering.example.html
  packages/styles/stories/Patterns/multi-input/grouping.example.html
  packages/styles/stories/Patterns/multi-input/match-popover-body-size.example.html
  packages/styles/stories/Patterns/multi-input/mobile-mode.example.html
  packages/styles/stories/Patterns/multi-input/semantic.example.html
  packages/theming-preview/src/input.html
Labels: Bug

#4623 chore(deps): opt out from storybook telemetry
  .storybook/main.ts
Labels: storybook

#4586 feat(styles): update token with the latest Horizon design
  packages/styles/src/theming/common/token/_sap_fiori.scss
  packages/styles/src/theming/common/token/_sap_fiori_hc.scss
  packages/styles/src/theming/common/token/_sap_horizon.scss
  packages/styles/src/theming/common/token/_sap_horizon_hc.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/src/token.scss
  packages/styles/stories/Components/token/primary.example.html
  packages/styles/stories/Components/token/read-only-token.example.html
  packages/styles/stories/Components/token/selected.example.html
  packages/styles/stories/Components/token/token.stories.js
  packages/styles/stories/Components/tokenizer/cozy-tokenizer.example.html
  packages/styles/stories/Components/tokenizer/scrollable-tokenizer.example.html
  packages/styles/stories/Components/tokenizer/tokenizer.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2023

#4514 feat(styles): update Calendar component - Horizon 2023
  packages/styles/src/calendar.scss
  packages/styles/src/theming/common/calendar/_sap_fiori.scss
  packages/styles/src/theming/common/calendar/_sap_horizon.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/stories/Components/calendar/cal.html
  packages/styles/stories/Components/calendar/calendar.stories.js
  packages/styles/stories/Components/calendar/days.example.html
  packages/styles/stories/Components/calendar/landscape-mobile.example.html
  packages/styles/stories/Components/calendar/months.example.html
  packages/styles/stories/Components/calendar/portrait-mobile.example.html
  packages/styles/stories/Components/calendar/years.example.html
  packages/styles/stories/Patterns/datepicker/mobile-landscape.example.html
  packages/styles/stories/Patterns/datepicker/mobile-portrait.example.html
  packages/styles/stories/Patterns/datepicker/today-navigation-button.example.html
  packages/styles/stories/Patterns/datepicker/today-selection-button.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
  packages/theming-preview/src/calendar.html
Labels: Horizon 2023

#4629 fix(styles): add fix for Object List height [ci visual]
  packages/styles/src/object-list.scss
  packages/styles/stories/Components/object-list/standart.example.html
Labels: Bug

#4632 fix(styles): menu full width
  packages/styles/src/menu.scss
Labels: Bug

#4631 fix(styles): add fix for Label truncation in Progress Indicator
  packages/styles/src/progress-indicator.scss
  packages/styles/stories/Components/progress-indicator/truncation.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug, Horizon 2023

#4634 feat(styles): add skeleton examples and styling [ci visual]
  packages/styles/src/fundamental-styles.scss
  packages/styles/src/skeleton.scss
  packages/styles/stories/Components/skeleton/circle.example.html
  packages/styles/stories/Components/skeleton/complex.example.html
  packages/styles/stories/Components/skeleton/lines.example.html
  packages/styles/stories/Components/skeleton/skeleton.example.html
  packages/styles/stories/Components/skeleton/skeleton.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Fiori New Component

#4645 test(styles): update snapshots
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Testing Framework

#4646 fix(styles): fixed for Input Group, Select and Step Input after design review
  packages/styles/src/mixins/_forms.scss
  packages/styles/src/select.scss
  packages/styles/src/step-input.scss
  packages/styles/src/theming/common/input-group/_sap_fiori.scss
  packages/styles/src/theming/common/input-group/_sap_horizon.scss
  packages/styles/src/theming/common/input/_sap_horizon.scss
  packages/styles/src/theming/common/step-input/_sap_fiori.scss
  packages/styles/src/theming/common/step-input/_sap_horizon.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon/_css_variables.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_dark/_css_variables.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/stories/Components/Forms/input-group/states.example.html
  packages/styles/stories/Components/select/cozy.example.html
  packages/styles/stories/Components/select/mobile-mode.example.html
  packages/styles/stories/Components/select/select.stories.js
  packages/styles/stories/Components/select/semantic-states.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
  packages/theming-preview/src/toolbar.html
Labels: Bug, design review changes
