Repository SAP/fundamental-styles, pull requests merged in 2024-07, with the labels that each got.

#5477 fix(styles): add status color only to the status icon of Message Box
  packages/styles/src/message-box.scss
Labels: Bug

#5455 feat(common-css): add Titles to Common CSS package [ci visual]
  packages/common-css/src/common-css.scss
  packages/common-css/src/sap-title.scss
  packages/common-css/stories/page-title/no-inline-padding.example.html
  packages/common-css/stories/page-title/no-page-title.example.html
  packages/common-css/stories/page-title/title.stories.js
  packages/common-css/stories/page-title/with-page-title.example.html
Labels: common-css

#5478 feat(common-css): add data attribute to common css Text [ci visual]
  packages/common-css/src/_common-mixins.scss
  packages/common-css/stories/text/hyphenation.example.html
  packages/common-css/stories/text/max-lines.example.html
  packages/common-css/stories/text/text.stories.js
  packages/common-css/stories/text/whitespace.example.html
Labels: common-css

#5492 fix: add belize preview
  packages/styles/src/theming/sap_belize.scss
Labels: Theming

#5490 fix(common-css): optimize paddings and margins usage [ci visual]
  packages/common-css/src/_common-mixins.scss
  packages/common-css/src/common-css.scss
  packages/common-css/src/sap-busy-indicator.scss
  packages/common-css/src/sap-margin.scss
Labels: code refactoring, common-css

#5493 chore(ci): migrate nx 19.4.2
  .gitignore
  package.json
  yarn.lock
Labels: tooling

#5506 fix(styles): fix belize theming
  packages/styles/src/theming/sap_belize.scss
Labels: Theming

#5495 chore(ci): update node 20.x [ci visual]
  .nvmrc
  netlify.toml
  package.json
  yarn.lock
Labels: tooling

#5507 chore(deps): theming-base-content 11.17.1 [ci visual]
  package.json
  yarn.lock
Labels: Theming, tooling

#5508 chore(ci): fix the workflow for publishing the docs
  .github/actions/bump-version/action.yml
  .github/workflows/create-release.yml
Labels: tooling

#5509 docs: add link to version 0.37 documentation
  packages/configuration/src/lib/previous-versions.ts
Labels: documentation

#5510 chore(deps): storybook version 8.2.4
  package.json
  yarn.lock
Labels: tooling, storybook, documentation

#5531 docs(styles): add AI button [ci visual]
  packages/doc-ui/src/components/DocsPage/custom.scss
  packages/styles/stories/Components/button/ai-button.example.html
  packages/styles/stories/Components/button/button.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: AI

#5532 feat(styles): introduce Prompt Input [ci visual]
  packages/configuration/src/lib/tags.ts
  packages/styles/src/fundamental-styles.scss
  packages/styles/src/prompt-input.scss
  packages/styles/stories/Components/Forms/prompt-input/basic.example.html
  packages/styles/stories/Components/Forms/prompt-input/prompt-input.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: AI
