Repository SAP/fundamental-styles, pull requests merged in 2024-09, with the labels that each got.

#5628 docs: update README.md
  README.md
Labels: documentation

#5616 fix(styles): refactor Notifications component [ci visual
  packages/styles/src/message-strip.scss
  packages/styles/src/notification.scss
  packages/styles/src/theming/common/notification/_sap_fiori.scss
  packages/styles/src/theming/common/notification/_sap_fiori_hc.scss
  packages/styles/src/theming/common/notification/_sap_horizon.scss
  packages/styles/src/theming/common/notification/_sap_horizon_hc.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/stories/Components/notification/banner.example.html
  packages/styles/stories/Components/notification/error.example.html
  packages/styles/stories/Components/notification/in-dialog.example.html
  packages/styles/stories/Components/notification/information.example.html
  packages/styles/stories/Components/notification/mobile.example.html
  packages/styles/stories/Components/notification/no-avatar.example.html
  packages/styles/stories/Components/notification/notification-group-btp.example.html
  packages/styles/stories/Components/notification/notification-group-header-btp.example.html
  packages/styles/stories/Components/notification/notification-group.example.html
  packages/styles/stories/Components/notification/notification-item-btp.example.html
  packages/styles/stories/Components/notification/notification.stories.js
  packages/styles/stories/Components/notification/primary.example.html
  packages/styles/stories/Components/notification/warning.example.html
  packages/styles/stories/Components/user-menu/third-party-content.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: code refactoring

#5630 fix(styles): refactor Illustrated Messages to latest design [ci visual]
  packages/styles/src/illustrated-message.scss
  packages/styles/stories/Components/illustrated-message/dialog.example.html
  packages/styles/stories/Components/illustrated-message/dot.example.html
  packages/styles/stories/Components/illustrated-message/illustrated-message.stories.js
  packages/styles/stories/Components/illustrated-message/spot.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: code refactoring

#5672 chore(deps): storybook 8.3.4
  package.json
  yarn.lock
Labels: Dependencies, storybook
