Repository SAP/fundamental-styles, pull requests merged in 2024-03, with the labels that each got.

#5181 chore(deps): migrate to storybook version 8.0.0 [ci visual]
  .storybook/custom/addons/theme-switcher/src/containers/Selector.jsx
  .storybook/custom/addons/theme-switcher/src/register.jsx
  .storybook/main.ts
  .storybook/manager.ts
  README.md
  package.json
  packages/doc-ui/src/components/ContentDensitySelect.tsx
  packages/doc-ui/src/components/DirectionalitySelect.tsx
  packages/doc-ui/src/components/DocsPage/custom.scss
  packages/doc-ui/src/components/GithubLink.tsx
  packages/doc-ui/src/components/SAPContainer.tsx
  packages/doc-ui/src/components/ThemeSelect.tsx
  packages/storybook/src/lib/decorators/contentDensity.ts
  packages/storybook/src/lib/decorators/directionalityProvider.ts
  packages/storybook/src/lib/decorators/themeProvider.ts
  packages/styles/README.md
  yarn.lock
Labels: tooling, storybook, documentation

#5231 docs: add link to 0.33 to the docs
  packages/configuration/src/lib/previous-versions.ts
Labels: documentation

#5233 fix(styles): add word break for text in Message Strip component
  packages/styles/src/message-strip.scss
Labels: Bug

#5235 chore(deps): theming-base-content v11.13.0 [ci visual]
  package.json
  packages/styles/src/icons/_settings.scss
  packages/styles/stories/Components/Icons/icon/SAPIcons/data.json
  yarn.lock
Labels: Dependencies, Theming, tooling

#5246 fix(styles): add fix for Product Switch items jumping on selection
  packages/styles/src/product-switch.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
Labels: Bug

#5249 fix(styles): add fix for the Tokens focus being cut in Tokenizer
  packages/styles/src/tokenizer.scss
Labels: Bug, Defect Hunting

#5262 docs: add doc 0.34
  packages/configuration/src/lib/previous-versions.ts
Labels: documentation

#5260 chore(deps): storybook v8.0.4
  package.json
  yarn.lock
Labels: Dependencies, storybook

#5261 feat(styles): update Card header per latest design
  packages/styles/src/card.scss
  packages/styles/src/theming/common/card/_sap_fiori.scss
  packages/styles/src/theming/common/card/_sap_horizon.scss
  packages/styles/stories/Components/card/analytical-card.example.html
  packages/styles/stories/Components/card/card-anatomy.example.html
  packages/styles/stories/Components/card/card.stories.js
  packages/styles/stories/Components/card/extended-header.example.html
  packages/styles/stories/Components/card/list-card.example.html
  packages/styles/stories/Components/card/numeric-header.example.html
  packages/styles/stories/Components/card/object-card.example.html
  packages/styles/stories/Components/card/table-card.example.html
  packages/styles/stories/Layouts/fixed-card-layout/fixed-card-layout.example.html
  packages/styles/stories/Layouts/resizable-card-layout/resize-card-horizontal-direction.example.html
  packages/styles/stories/Layouts/resizable-card-layout/resize-card-horizontal-vertical-direction.example.html
  packages/styles/stories/Layouts/resizable-card-layout/resize-card-layout.example.html
  packages/styles/stories/Layouts/resizable-card-layout/resize-card-vertical-direction.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2024

#5265 fix(styles): add focus and a11y changes for Card header [ci visual]
  packages/styles/src/card.scss
  packages/styles/stories/Components/card/analytical-card.example.html
  packages/styles/stories/Components/card/card-anatomy.example.html
  packages/styles/stories/Components/card/extended-header.example.html
  packages/styles/stories/Components/card/object-card.example.html
  packages/styles/stories/Components/card/table-card.example.html
  packages/styles/stories/Layouts/fixed-card-layout/fixed-card-layout.example.html
  packages/styles/stories/Layouts/resizable-card-layout/resize-card-layout.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11y
