Repository SAP/fundamental-styles, pull requests merged in 2024-10, with the labels that each got.

#5675 fix(styles): update Shell Bar to latest design [ci visual]
  packages/configuration/src/lib/tags.ts
  packages/styles/src/shellbar.scss
  packages/styles/src/theming/common/shellbar/_sap_fiori.scss
  packages/styles/src/theming/common/shellbar/_sap_horizon.scss
  packages/styles/stories/Components/product-switch/product-switch.stories.js
  packages/styles/stories/Components/shellbar/links-with-collapsible-menu-msize.example.html
  packages/styles/stories/Components/shellbar/links-with-collapsible-menu-ssize.example.html
  packages/styles/stories/Components/shellbar/links-with-collapsible-menu-xl-size.example.html
  packages/styles/stories/Components/shellbar/optional-items.example.html
  packages/styles/stories/Components/shellbar/overflow-toolbar.example.html
  packages/styles/stories/Components/shellbar/primary.example.html
  packages/styles/stories/Components/shellbar/product-menu-and-search.example.html
  packages/styles/stories/Components/shellbar/product-switch.example.html
  packages/styles/stories/Components/shellbar/responsive-paddings.example.html
  packages/styles/stories/Components/shellbar/responsiveness.example.html
  packages/styles/stories/Components/shellbar/shellbar.stories.js
  packages/styles/stories/Components/shellbar/without-center.example.html
  packages/styles/stories/Components/user-menu/shellbar.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2024

#5679 chore: fix lint error
  packages/styles/stories/Components/notification/notification.stories.js
Labels: tooling, storybook

#5690 fix(styles): remove redundant spacing between form items [ci visual]
  packages/styles/src/form-group.scss
  packages/styles/src/form-item.scss
  packages/styles/stories/AI/Patterns/ai-guided-prompt/ai-guided-prompt.example.html
  packages/styles/stories/Components/Forms/form-group/group-header-in-form-grid.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Bug

#5703 fix(styles): add option to make individual Table cells non-interactive
  packages/styles/src/table.scss
  packages/styles/stories/Components/table/primary.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Enhancement

#5705 chore(deps): theming-base-content version 11.19.0 [ci visual]
  package.json
  packages/styles/src/icon-tab-bar.scss
  packages/styles/src/mixins/button/_button-types.scss
  packages/styles/src/theming/common/button/_sap_fiori.scss
  packages/styles/src/theming/common/button/_sap_fiori_hc.scss
  packages/styles/src/theming/common/button/_sap_horizon.scss
  packages/styles/src/theming/common/button/_sap_horizon_hc.scss
  packages/styles/src/theming/common/checkbox/_common.scss
  packages/styles/src/theming/common/checkbox/_sap_fiori_hc.scss
  packages/styles/src/theming/common/checkbox/_sap_foiri.scss
  packages/styles/src/theming/common/checkbox/_sap_horizon.scss
  packages/styles/src/theming/common/checkbox/_sap_horizon_hc.scss
  packages/styles/src/theming/common/radio/_common.scss
  packages/styles/src/theming/common/radio/_sap_fiori.scss
  packages/styles/src/theming/common/radio/_sap_fiori_hc.scss
  packages/styles/src/theming/common/radio/_sap_horizon.scss
  packages/styles/src/theming/common/radio/_sap_horizon_hc.scss
  yarn.lock
Labels: Theming

#5742 fix(styles): minor CSS fixes for Shellbar [ci visual]
  packages/styles/src/shellbar.scss
  packages/styles/src/theming/common/shellbar/_sap_horizon.scss
  packages/styles/stories/Components/shellbar/shellbar.stories.js
Labels: UXC Updates

#5743 chore(deps): migration nx 20 and sb 8.3.6 [ci visual]
  nx.json
  package.json
  yarn.lock
Labels: tooling, storybook

#5745 docs(styles): deprecate btp tool header
  packages/styles/stories/BTP/tool-header/tool-header.stories.js
Labels: documentation, UXC Updates

#5746 fix(styles): updates for context area in ShellBar [ci visual]
  packages/styles/src/shellbar.scss
  packages/styles/stories/Components/shellbar/optional-items.example.html
  packages/styles/stories/Components/shellbar/overflow-toolbar.example.html
  packages/styles/stories/Components/shellbar/shellbar.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: UXC Updates
