Repository SAP/fundamental-styles, pull requests merged in 2024-05, with the labels that each got.

#5326 fix(styles): fix readonly textarea [ci visual]
  packages/styles/src/textarea.scss
Labels: Bug

#5354 feat(styles): add Media cards, design updates [ci visual]
  packages/styles/src/card.scss
  packages/styles/src/theming/common/card/_sap_fiori.scss
  packages/styles/src/theming/common/card/_sap_fiori_hc.scss
  packages/styles/src/theming/common/card/_sap_horizon.scss
  packages/styles/src/theming/common/card/_sap_horizon_hc.scss
  packages/styles/stories/Components/card-media/card-media-banner.example.html
  packages/styles/stories/Components/card-media/card-media-title.example.html
  packages/styles/stories/Components/card-media/card-media.example.html
  packages/styles/stories/Components/card-media/card-media.stories.js
  packages/styles/stories/Components/card/analytical-card.example.html
  packages/styles/stories/Components/card/card-anatomy.example.html
  packages/styles/stories/Components/card/card-button-interactive.example.html
  packages/styles/stories/Components/card/card-empty-state.example.html
  packages/styles/stories/Components/card/card-interaction-states.example.html
  packages/styles/stories/Components/card/card-listitem-interactive.example.html
  packages/styles/stories/Components/card/card-non-interactive-header.example.html
  packages/styles/stories/Components/card/card-non-interactive.example.html
  packages/styles/stories/Components/card/card.stories.js
  packages/styles/stories/Components/card/extended-header.example.html
  packages/styles/stories/Components/card/list-card.example.html
  packages/styles/stories/Components/card/numeric-header.example.html
  packages/styles/stories/Components/card/object-card.example.html
  packages/styles/stories/Components/card/table-card.example.html
  packages/styles/stories/Layouts/fixed-card-layout/fixed-card-layout.example.html
  packages/styles/stories/Layouts/resizable-card-layout/resize-card-horizontal-direction.example.html
  packages/styles/stories/Layouts/resizable-card-layout/resize-card-horizontal-vertical-direction.example.html
  packages/styles/stories/Layouts/resizable-card-layout/resize-card-layout.example.html
  packages/styles/stories/Layouts/resizable-card-layout/resize-card-vertical-direction.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2024

#5365 chore(deps): update storybook v.8.0.10 [ci visual]
  package.json
  yarn.lock
Labels: Dependencies, storybook

#5367 fix(styles): update textarea line-height [ci visual]
  packages/styles/src/textarea.scss
  packages/styles/src/theming/common/textarea/_sap_fiori.scss
  packages/styles/src/theming/common/textarea/_sap_horizon.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
Labels: Bug

#5389 chore(deps): theming-base-content v.11.15.0 [ci visual]
  package.json
  yarn.lock
Labels: Dependencies, Theming

#5390 chore(deps): storybook v.8.1.1 [ci visual]
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  yarn.lock
Labels: Dependencies, storybook, documentation

#5405 fix(styles): add fix for the Mega Manu button color [ci visual]
  packages/styles/src/shellbar.scss
Labels: Bug

#5407 fix(styles): fix the wrong min-width variable values for Input and Tokenizer
  packages/styles/src/mixins/_forms.scss
  packages/styles/src/tokenizer.scss
Labels: Bug

#5409 docs: update old version doc links
  packages/configuration/src/lib/previous-versions.ts
Labels: Doc website, documentation

#5410 chore(deps): storybook version 8.1.4
  package.json
  yarn.lock
Labels: Dependencies, storybook

#5411 fix(docs): publish github pages
  .github/actions/bump-version/index.js
  .github/actions/helpers/get-release-tag.js
Labels: tooling, documentation

#5413 fix(ci): fix ci
  .github/actions/bump-version/index.js
Labels: tooling

#5414 fix(ci): fix ci - try 2
  .github/actions/bump-version/index.js
Labels: tooling
