Repository SAP/fundamental-styles, pull requests merged in 2024-12, with the labels that each got.

#5820 fix(styles): update User Menu to latest design
  packages/styles/src/mixins/list/_list-base.scss
  packages/styles/src/mixins/list/_list-definitions.scss
  packages/styles/src/navigation-list.scss
  packages/styles/src/object-list.scss
  packages/styles/src/panel.scss
  packages/styles/src/popover.scss
  packages/styles/src/user-menu.scss
  packages/styles/stories/Components/user-menu/default.example.html
  packages/styles/stories/Components/user-menu/mobile.example.html
  packages/styles/stories/Components/user-menu/user-menu.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: UXC Updates

#5831 chore(deps): update theming-base-content v.11.23.0 [ci visual]
  package.json
  packages/styles/src/icons/_settingsBusiness.scss
  packages/styles/stories/Components/Icons/icon/BusinessSuiteInAppSymbols/dataBusinessSuite.json
  packages/styles/tests/__snapshots__/styles.test.ts.snap
  yarn.lock
Labels: Dependencies, Theming

#5843 chore(deps): theming-base-content v11.25.0 [ci visual]
  package.json
  yarn.lock
Labels: Dependencies, Theming

#5844 chore: cleanup avatar story
  packages/styles/stories/Components/avatar/avatar.stories.js
Labels: Doc website

#5845 chore(deps): storybook v.8.4.7
  package.json
  yarn.lock
Labels: Dependencies, storybook

#5846 chore(deps): nx 20.2.2
  package.json
  yarn.lock
Labels: Dependencies, tooling

#5847 chore(deps): chromatic v. 11.20.2 [ci visual]
  package.json
  yarn.lock
Labels: tooling, Visual Testing, storybook

#5848 chore(deps): yarn 4.5.1 [ci visual]
  netlify.toml
  package.json
Labels: Dependencies, tooling

#5849 chore(ci): bump action versions
  .github/actions/nodejs/action.yml
  .github/workflows/create-release.yml
  .github/workflows/on-pull.yml
Labels: tooling

#5860 chore(deps): nx v.20.3.0
  package.json
  yarn.lock
Labels: Dependencies, tooling
