Repository SAP/fundamental-styles, pull requests merged in 2024-01, with the labels that each got.

#5086 fix(styles): compact switch fiori
  packages/styles/src/theming/common/switch/_sap_fiori.scss
Labels: Bug

#5085 fix: splitter resizer overflow and positioning
  package.json
  packages/styles/src/splitter.scss
  packages/styles/stories/BTP/splitter/default.example.html
  packages/styles/stories/BTP/splitter/grip-anatomy.example.html
  packages/styles/stories/BTP/splitter/pagination.example.html
  packages/styles/stories/BTP/splitter/split-pane-anatomy.example.html
  packages/styles/stories/BTP/splitter/splitter.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
  yarn.lock
Labels: Bug, Dependencies, BTP, documentation, code refactoring

#5088 fix(styles): splitter horizontal scrolls on active handle
  package.json
  packages/styles/src/splitter.scss
Labels: Bug, BTP

#5089 fix(styles): add black font family [ci visual]
  packages/styles/src/fonts/sap_fonts.scss
Labels: Bug

#5105 chore(deps): update theming-base-content v. 11.10.0
  package.json
  yarn.lock
Labels: Dependencies, Theming

#5101 fix(styles): add a fix for hover state in Grid List [ci visual]
  packages/styles/src/grid-list.scss
Labels: Bug

#5116 feat(styles): add full width modifier to Step Input [ci visual]
  packages/styles/src/step-input.scss
  packages/styles/stories/Components/step-input/full-width.example.html
  packages/styles/stories/Components/step-input/step-input.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Enhancement

#5127 chore(deps): update conventional-changelog and commitlint
  package.json
  yarn.lock
Labels: Dependencies

#5128 chore(deps): fix usage of recommendedVersion from conventional-recomm…
  .github/actions/bump-version/index.js
Labels: tooling

#5132 fix(styles): input group height
  package.json
  packages/styles/src/input-group.scss
  packages/styles/src/mixins/_forms.scss
  packages/styles/src/tokenizer.scss
Labels: Bug

#5143 fix(styles): Avatar component v1.0.0 updates
  packages/styles/src/_avatar-variables.scss
  packages/styles/src/avatar.scss
  packages/styles/stories/Components/avatar/accent-colors-shell-header-context.example.html
  packages/styles/stories/Components/avatar/accent-colors.example.html
  packages/styles/stories/Components/avatar/avatar.stories.js
  packages/styles/stories/Components/avatar/background-image.example.html
  packages/styles/stories/Components/avatar/borders.example.html
  packages/styles/stories/Components/avatar/circle.example.html
  packages/styles/stories/Components/avatar/icon.example.html
  packages/styles/stories/Components/avatar/initials.example.html
  packages/styles/stories/Components/avatar/placeholder-background.example.html
  packages/styles/stories/Components/avatar/tile-icon-background.example.html
  packages/styles/stories/Components/avatar/transparent.example.html
  packages/styles/stories/Components/avatar/value-states.example.html
  packages/styles/stories/Components/avatar/zoom-icon.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: version 1.0
