Repository SAP/fundamental-styles, pull requests merged in 2024-04, with the labels that each got.

#5279 fix(styles): add a11y improvements for Dynamic Page header [ci visual]
  packages/styles/src/dynamic-page.scss
  packages/styles/src/mixins/_mixins.scss
  packages/styles/stories/Layouts/dynamic-page/collapsed-header.example.html
  packages/styles/stories/Layouts/dynamic-page/desktop.example.html
  packages/styles/stories/Layouts/dynamic-page/expandable.example.html
  packages/styles/stories/Layouts/dynamic-page/mobile-collapsed.example.html
  packages/styles/stories/Layouts/dynamic-page/mobile.example.html
  packages/styles/stories/Layouts/dynamic-page/only-collapse.example.html
  packages/styles/stories/Layouts/dynamic-page/summary-line.example.html
  packages/styles/stories/Layouts/dynamic-page/tablet.example.html
  packages/styles/stories/Layouts/dynamic-page/with-facets-mobile.example.html
  packages/styles/stories/Layouts/dynamic-page/with-facets.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11y

#5277 chore(deps): storybook 8.0.5
  package.json
  yarn.lock
Labels: tooling, storybook, documentation

#5295 chore(ci): update storybook 8.0.6
  package.json
  yarn.lock
Labels: Dependencies, storybook

#5296 chore(deps): revert vite-tsconfig-path
  package.json
  yarn.lock
Labels: Dependencies, tooling

#5310 fix(styles): add fix for buttons hover state in Shell Bar [ci visual]
  packages/styles/src/shellbar.scss
  packages/styles/src/theming/common/shellbar/_sap_horizon.scss
  packages/styles/stories/Components/shellbar/responsive-paddings.example.html
Labels: Horizon 2024

#5309 fix(styles): change the font-size of Side Nav icon [ci visual]
  packages/cx/src/_nested-list.scss
Labels: Horizon 2024

#5311 fix(styles): add an option to have an icon, text and input on same level in Menu item
  packages/styles/src/menu.scss
  packages/styles/stories/Components/menu/input.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Enhancement

#5312 fix(styles): update Inverted object status to latest design [ci visual]
  packages/styles/src/object-status.scss
  packages/styles/stories/Components/object-status/inverted.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Horizon 2024

#5323 chore(deps): theming-base-content v.11.14.0 [ci visual]
  package.json
  packages/styles/src/icons/_settingsTNT.scss
  packages/styles/stories/Components/Icons/icon/TNTIcons/dataTNT.json
  yarn.lock
Labels: Dependencies, Theming

#5324 chore(deps): storybook 8.0.9
  .storybook/main.ts
  package.json
  yarn.lock
Labels: Dependencies, storybook
