Repository SAP/fundamental-styles, pull requests merged in 2024-08, with the labels that each got.

#5543 feat(styles): add ai text highlight [ci visual]
  packages/styles/src/form-item.scss
  packages/styles/src/mixins/_mixins.scss
  packages/styles/src/text.scss
  packages/styles/src/textarea.scss
  packages/styles/stories/Components/Forms/textarea/ai.example.html
  packages/styles/stories/Components/Forms/textarea/textarea.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: AI

#5544 fix(styles): remove the default background for autofill input
  packages/styles/src/input-group.scss
Labels: Bug

#5555 feat(styles): add components extensions [ci visual]
  packages/styles/src/ai-busy-indicator.scss
  packages/styles/src/ai-loading-bar.scss
  packages/styles/src/ai-text.scss
  packages/styles/src/form-item.scss
  packages/styles/src/fundamental-styles.scss
  packages/styles/src/textarea.scss
  packages/styles/stories/AI/Components/ai-busy-indicator/ai-busy-indicator.example.html
  packages/styles/stories/AI/Components/ai-busy-indicator/ai-busy-indicator.stories.js
  packages/styles/stories/AI/Components/ai-button/ai-button.example.html
  packages/styles/stories/AI/Components/ai-button/ai-button.stories.js
  packages/styles/stories/AI/Components/ai-loading-bar/ai-loading-bar.example.html
  packages/styles/stories/AI/Components/ai-loading-bar/ai-loading-bar.stories.js
  packages/styles/stories/AI/Components/ai-prompt-input/ai-prompt-input.example.html
  packages/styles/stories/AI/Components/ai-prompt-input/ai-prompt-input.stories.js
  packages/styles/stories/AI/Patterns/ai-progress-indicator/ai-progress-indicator.example.html
  packages/styles/stories/AI/Patterns/ai-progress-indicator/ai-progress-indicator.stories.js
  packages/styles/stories/AI/Patterns/ai-text-highlight/ai-text-highlight.example.html
  packages/styles/stories/AI/Patterns/ai-text-highlight/ai-text-highlight.stories.js
  packages/styles/stories/Components/Forms/textarea/textarea.stories.js
  packages/styles/stories/Components/button/button.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: AI

#5556 fix(styles): align the notification indicator icon [ci visual]
  packages/styles/src/notification.scss
Labels: Bug

#5557 chore(deps): theming-base-content version 11.18.0 [ci visual]
  package.json
  yarn.lock
Labels: Dependencies, Theming

#5569 fix(styles): add Guided Prompt pattern [ci visual]
  packages/styles/src/form-item.scss
  packages/styles/src/segmented-button.scss
  packages/styles/stories/AI/Patterns/ai-guided-prompt/ai-guided-prompt.example.html
  packages/styles/stories/AI/Patterns/ai-guided-prompt/ai-guided-prompt.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: AI

#5571 chore(ci): update gh actions versions
  .github/actions/nodejs/action.yml
  .github/workflows/chromatic.yml
  .github/workflows/create-release.yml
  .github/workflows/on-pull.yml
Labels: Dependencies

#5572 docs(styles): add AI Quick Prompt pattern [ci visual]
  packages/styles/stories/AI/Components/ai-button/ai-button.example.html
  packages/styles/stories/AI/Patterns/ai-quick-prompt/ai-quick-prompt.example.html
  packages/styles/stories/AI/Patterns/ai-quick-prompt/ai-quick-prompt.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: AI

#5574 chore(ci): update yarn.lock
  yarn.lock
Labels: Dependencies

#5573 fix(styles): add AI Notice [ci visual]
  packages/styles/src/fundamental-styles.scss
  packages/styles/src/textarea.scss
  packages/styles/stories/AI/Patterns/ai-notice/ai-notice.example.html
  packages/styles/stories/AI/Patterns/ai-notice/ai-notice.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: AI

#5575 chore(ci): update the yarn install command
  .github/actions/nodejs/action.yml
  netlify.toml
Labels: Dependencies

#5577 test(ci): add verbose to yarn install
  .yarnrc.yml
Labels: tooling

#5581 chore(deps): update old deps
  .github/actions/nodejs/action.yml
  netlify.toml
  package.json
  packages/styles/src/_nested-list.scss
  packages/styles/src/button.scss
  packages/styles/src/dialog.scss
  packages/styles/src/form-layout-grid.scss
  packages/styles/src/layout-panel.scss
  packages/styles/src/mixins/table/_table-pop-in.scss
  packages/styles/src/numeric-content.scss
  packages/styles/src/quick-view.scss
  packages/styles/src/slider.scss
  yarn.lock
Labels: Dependencies, tooling

#5576 docs(styles): add AI Acknowledgment pattern [ci visual]
  packages/styles/stories/AI/Patterns/ai-acknowledgment/ai-acknowledgment.example.html
  packages/styles/stories/AI/Patterns/ai-acknowledgment/ai-acknowledgment.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: AI

#5578 feat(styles): introduce AI Writing Assistant
  packages/styles/src/ai-writing-assistant-versioning.scss
  packages/styles/src/ai-writing-assistant.scss
  packages/styles/src/form-label.scss
  packages/styles/src/fundamental-styles.scss
  packages/styles/src/textarea.scss
  packages/styles/src/toolbar.scss
  packages/styles/stories/AI/Patterns/ai-writing-assistant-toolbar/ai-writing-assistant-toolbar.example.html
  packages/styles/stories/AI/Patterns/ai-writing-assistant-toolbar/ai-writing-assistant-toolbar.stories.js
  packages/styles/stories/AI/Patterns/ai-writing-assistant/ai-writing-assistant-inputs.example.html
  packages/styles/stories/AI/Patterns/ai-writing-assistant/ai-writing-assistant.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: AI

#5580 fix(styles): an attempt to fix the padding issue in FNGX [ci visual]
  packages/styles/src/calendar.scss
Labels: Bug

#5582 chore(ci): yarn 4.4.1 migration
  .github/actions/nodejs/action.yml
  .yarnrc.yml
  netlify.toml
  package.json
  yarn.lock
Labels: tooling

#5594 fix(styles): paddings and margins specificity [ci visual]
  packages/common-css/src/sap-tool-layout.scss
  packages/cx/src/side-nav.scss
  packages/styles/src/_app.scss
  packages/styles/src/action-sheet.scss
  packages/styles/src/card.scss
  packages/styles/src/dynamic-page.scss
  packages/styles/src/form-layout-grid.scss
  packages/styles/src/icon-tab-bar.scss
  packages/styles/src/illustrated-message.scss
  packages/styles/src/info-label.scss
  packages/styles/src/input-group.scss
  packages/styles/src/menu.scss
  packages/styles/src/message-page.scss
  packages/styles/src/micro-process-flow.scss
  packages/styles/src/mixins/_forms.scss
  packages/styles/src/mixins/list/_list-base.scss
  packages/styles/src/mixins/list/_list-dropdown.scss
  packages/styles/src/notification.scss
  packages/styles/src/object-status.scss
  packages/styles/src/progress-indicator.scss
  packages/styles/src/resizable-card-layout.scss
  packages/styles/src/section.scss
  packages/styles/src/shellbar.scss
  packages/styles/src/slider.scss
  packages/styles/src/status-indicator.scss
  packages/styles/src/step-input.scss
  packages/styles/src/switch.scss
  packages/styles/src/theming/common/card/_sap_fiori.scss
  packages/styles/src/theming/common/card/_sap_horizon.scss
  packages/styles/src/theming/common/object-status/_sap_fiori.scss
  packages/styles/src/theming/common/object-status/_sap_horizon.scss
  packages/styles/src/theming/common/progress-indicator/_sap_fiori.scss
  packages/styles/src/theming/common/progress-indicator/_sap_horizon.scss
  packages/styles/src/theming/common/switch/_sap_fiori.scss
  packages/styles/src/theming/common/switch/_sap_horizon.scss
  packages/styles/src/theming/common/user-menu/_sap_fiori.scss
  packages/styles/src/theming/common/user-menu/_sap_horizon.scss
  packages/styles/src/tile.scss
  packages/styles/src/time.scss
  packages/styles/src/timepicker.scss
  packages/styles/src/token.scss
  packages/styles/src/tokenizer.scss
  packages/styles/src/tool-layout.scss
  packages/styles/src/toolbar.scss
  packages/styles/src/user-menu.scss
  packages/styles/src/wizard.scss
Labels: code refactoring

#5600 docs(styles): add the missing checkboxes in Table examples [ci visual]
  packages/styles/stories/Components/table/checkbox.example.html
  packages/styles/stories/Components/table/condensed-checkbox.example.html
  packages/styles/stories/Components/table/grid-table.example.html
  packages/styles/stories/Components/table/nav-indicators.example.html
  packages/styles/stories/Components/table/responsive-table.example.html
  packages/styles/stories/Components/table/semantic-rows.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: documentation

#5601 fix(styles): update the spacing for XS Avatar Group [ci visual]
  packages/styles/src/_avatar-variables.scss
  packages/styles/stories/Components/avatar-group/group-type-vertical.example.html
  packages/styles/stories/Components/avatar-group/group-type.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: design review changes

#5602 chore(deps): update cssnano v.7 [ci visual]
  package.json
  yarn.lock
Labels: Dependencies

#5603 docs: hide old versions links to small resolutions
  packages/doc-ui/src/components/DocsPage/custom.scss
Labels: documentation
