Repository SAP/fundamental-styles, pull requests merged in 2024-02, with the labels that each got.

#5144 fix(styles): updates related to v1 for Avatar Group [ci visual]
  packages/styles/src/_avatar-variables.scss
  packages/styles/src/avatar-group.scss
  packages/styles/stories/Components/avatar-group/avatar-group.stories.js
  packages/styles/stories/Components/avatar-group/group-type-interaction-states.example.html
  packages/styles/stories/Components/avatar-group/group-type-vertical.example.html
  packages/styles/stories/Components/avatar-group/group-type.example.html
  packages/styles/stories/Components/avatar-group/individual-type-vertical.example.html
  packages/styles/stories/Components/avatar-group/individual-type.example.html
  packages/styles/stories/Components/avatar-group/overflow.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: version 1.0

#5146 chore(deps): update theming-base-content v11.11.0
  package.json
  yarn.lock
Labels: Dependencies, Theming, tooling

#5159 chore: revert #5153
  yarn.lock
Labels: Dependencies, tooling

#5157 chore(deps): storybook version 7.6.12
  package.json
  yarn.lock
Labels: Dependencies, storybook

#5145 fix(styles): bar component v1 update [ci visual]
  packages/configuration/src/lib/tags.ts
  packages/styles/src/bar.scss
  packages/styles/stories/Components/avatar-group/avatar-group.stories.js
  packages/styles/stories/Components/avatar/avatar.stories.js
  packages/styles/stories/Components/bar/bar.stories.js
  packages/styles/stories/Components/bar/floating-footer.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: version 1.0

#5161 chore: migrate to nx version 18
  .env
  package.json
  yarn.lock
Labels: tooling

#5163 chore: empty commit push
  package.json
Labels: tooling

#5164 chore: removed unused package
  .storybook/preview.ts
  .storybook/static/theme-ugly.css
  .storybook/static/unnormalize.css
  .storybook/static/windows-hcm-1.css
  .storybook/static/windows-hcm-2.css
  .storybook/static/windows-hcm-dark.css
  .storybook/static/windows-hcm-light.css
  package.json
  yarn.lock
Labels: tooling

#5167 chore(ci): simplify on_pull workflow
  .github/workflows/chromatic.yml
  .github/workflows/on-pull.yml
Labels: tooling

#5169 chore(ci): simplify build
  .github/actions/build/action.yml
  .github/workflows/create-release.yml
  .husky/pre-commit
Labels: tooling

#4785 chore(docs,tooling): documented code and updated tooling
  .babelrc.json
  .storybook/MainDocPage.tsx
  .storybook/custom/addons/theme-switcher/preset.js
  .storybook/custom/addons/theme-switcher/register.js
  .storybook/custom/addons/theme-switcher/src/constants.js
  .storybook/custom/addons/theme-switcher/src/containers/IconButtonLabel.jsx
  .storybook/custom/addons/theme-switcher/src/containers/Selector.jsx
  .storybook/custom/addons/theme-switcher/src/register.jsx
  .storybook/custom/addons/utilities/get-owner.js
  .storybook/custom/addons/utilities/projects.js
  .storybook/custom/addons/utilities/use-memo-with-comparator.js
  .storybook/main.ts
  .storybook/preview.ts
  docs/ADDING_PACKAGE.md
  docs/CI.md
  docs/CONTRIBUTORS.md
  nx.json
  package.json
  packages/common-css/package-config.ts
  packages/configuration/.babelrc
  packages/configuration/README.md
  packages/configuration/src/lib/packages.ts
  packages/cx/package-config.ts
  packages/doc-ui/.babelrc
  packages/doc-ui/README.md
  packages/doc-ui/src/components/DocsPage/DocsPage.tsx
  packages/doc-ui/src/components/GithubLink.tsx
  packages/doc-ui/src/components/SAPContainer.tsx
  packages/doc-ui/src/components/ThemeSelect.tsx
  packages/doc-ui/src/contexts/SAPContext.ts
  packages/storybook/.babelrc
  packages/storybook/src/index.ts
  packages/storybook/src/lib/components/IntroductionPageWrapper.tsx
  packages/storybook/src/lib/interfaces/package.config.interface.ts
  packages/storybook/src/lib/storybook.ts
  packages/storybook/src/lib/visual-stories.ts
  packages/styles/package-config.ts
  packages/theming-preview/README.md
  packages/utils/.babelrc
  packages/workspace-plugins/generators.json
  packages/workspace-plugins/src/executors/visual-stories/README.md
  packages/workspace-plugins/src/executors/visual-stories/index.ts
  packages/workspace-plugins/src/executors/visual-stories/parse-stories-file.ts
  packages/workspace-plugins/src/generators/create-package/files/package-info/package-config.ts.template
  packages/workspace-plugins/src/generators/create-package/files/package-info/stories/introduction.stories.tsx.template
  packages/workspace-plugins/src/generators/create-package/files/package/__fileName__/project.json.template
  packages/workspace-plugins/src/generators/create-package/generator.ts
  packages/workspace-plugins/src/generators/create-package/update-package-configurations.ts
  packages/workspace-plugins/src/generators/create-package/update-projects-js.ts
  packages/workspace-plugins/src/generators/extract-html-sections/index.ts
  packages/workspace-plugins/src/generators/extract-html-sections/schema.json
  packages/workspace-plugins/src/generators/extract-html-sections/schema.ts
  projects.js
  stories-transformer.ts
  yarn.lock
Labels: documentation

#5184 chore(deps): update theming-base-content 11.12.0 [ci visual]
  package.json
  yarn.lock
Labels: Dependencies, Theming

#5185 chore(ci): bump ghaction cache version
  .github/workflows/on-pull.yml
Labels: tooling

#5183 fix(styles): add fix for information state hover and active [ci visual]
  packages/styles/src/micro-process-flow.scss
Labels: Bug
