Repository SAP/fundamental-styles, pull requests merged in 2025-05, with the labels that each got.

#6052 chore(styles): common css doc fixes
  packages/common-css/stories/heading/heading.stories.js
  packages/common-css/stories/heading/levels.example.html
  packages/common-css/stories/margin/margin.stories.js
  packages/common-css/stories/margin/margin.story.description.html
  packages/common-css/stories/padding/padding.story.description.html
Labels: Doc website

#6055 chore(deps): update yarn v 4.9
  netlify.toml
  package.json
Labels: tooling

#6058 docs: add doc version 0.40
  packages/configuration/src/lib/previous-versions.ts
Labels: documentation

#6060 fix(styles): a11y updates for Generic Tag [ci visual]
  packages/styles/src/generic-tag.scss
  packages/styles/stories/Components/generic-tag/primary.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11y

#6066 fix(styles): add a11y updates for Object Status [ci visual]
  packages/styles/src/object-status.scss
  packages/styles/stories/Components/object-status/clickable-object-status.example.html
  packages/styles/stories/Components/object-status/generic-indication-colors.example.html
  packages/styles/stories/Components/object-status/icon-and-text.example.html
  packages/styles/stories/Components/object-status/icon.example.html
  packages/styles/stories/Components/object-status/inverted-indication-secondary.example.html
  packages/styles/stories/Components/object-status/inverted-indication.example.html
  packages/styles/stories/Components/object-status/inverted-states.example.html
  packages/styles/stories/Components/object-status/inverted.example.html
  packages/styles/stories/Components/object-status/large-object-status.example.html
  packages/styles/stories/Components/object-status/object-status.stories.js
  packages/styles/stories/Components/object-status/primary.example.html
  packages/styles/stories/Components/object-status/text.example.html
  packages/styles/stories/Components/object-status/truncate-example.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11y

#6071 chore(deps): update nx v.21.1.2
  .gitignore
  package.json
  yarn.lock
Labels: Dependencies
