Repository SAP/fundamental-styles, pull requests merged in 2025-06, with the labels that each got.

#6065 fix(styles): a11y update for Message Strip [ci visual]
  packages/styles/src/message-strip.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/stories/Components/message-strip/default-strip.example.html
  packages/styles/stories/Components/message-strip/error.example.html
  packages/styles/stories/Components/message-strip/information.example.html
  packages/styles/stories/Components/message-strip/message-strip-with-accent-colors.example.html
  packages/styles/stories/Components/message-strip/message-strip-with-custom-icon.example.html
  packages/styles/stories/Components/message-strip/message-strip-with-link.example.html
  packages/styles/stories/Components/message-strip/message-strip.stories.js
  packages/styles/stories/Components/message-strip/no-icons-not-dismissible.example.html
  packages/styles/stories/Components/message-strip/no-icons.example.html
  packages/styles/stories/Components/message-strip/success.example.html
  packages/styles/stories/Components/message-strip/warning.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11y

#6084 chore: convert the issue templates to yml format
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/component-request.md
  .github/ISSUE_TEMPLATE/component-request.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue-template-for-version-1-0-0.md
  .github/ISSUE_TEMPLATE/version_1_0_0.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.yml
Labels: tooling

#6085 chore: revert PR template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.yml
Labels: tooling

#6086 fix(styles): a11y and focus improvements for Avatar Group [ci visual]
  packages/styles/src/avatar-group.scss
  packages/styles/stories/Components/avatar-group/avatar-group.stories.js
  packages/styles/stories/Components/avatar-group/group-type-interaction-states.example.html
  packages/styles/stories/Components/avatar-group/group-type-vertical.example.html
  packages/styles/stories/Components/avatar-group/group-type.example.html
  packages/styles/stories/Components/avatar-group/individual-type-vertical.example.html
  packages/styles/stories/Components/avatar-group/individual-type.example.html
  packages/styles/stories/Components/avatar-group/overflow.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11y

#6083 docs(styles): update Avatar examples with correct a11y roles [ci visual]
  packages/styles/stories/Components/avatar/accent-colors-shell-header-context.example.html
  packages/styles/stories/Components/avatar/accent-colors.example.html
  packages/styles/stories/Components/avatar/avatar.stories.js
  packages/styles/stories/Components/avatar/background-image.example.html
  packages/styles/stories/Components/avatar/borders.example.html
  packages/styles/stories/Components/avatar/circle.example.html
  packages/styles/stories/Components/avatar/initials.example.html
  packages/styles/stories/Components/avatar/interactive.example.html
  packages/styles/stories/Components/avatar/placeholder-background.example.html
  packages/styles/stories/Components/avatar/tile-icon-background.example.html
  packages/styles/stories/Components/avatar/transparent.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11y

#6092 fix(styles): add fix for missing btn focus in input group [ci visual]
  packages/styles/src/input-group.scss
Labels: Bug

#6091 chore(deps): update theming-base-content v.11.31.0
  package.json
  packages/styles/src/icons/_settings.scss
  packages/styles/stories/Components/Icons/icon/SAPIcons/data.json
  packages/styles/tests/__snapshots__/styles.test.ts.snap
  yarn.lock
Labels: Dependencies, Theming

#6097 docs(styles): improve Radio button examples for a11y [ci visual]
  packages/styles/stories/Components/Forms/radio/inline.example.html
  packages/styles/stories/Components/Forms/radio/interaction-states.example.html
  packages/styles/stories/Components/Forms/radio/primary.example.html
  packages/styles/stories/Components/Forms/radio/radio.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11Y

#6098 fix(styles): add improvements for Field Set, Form Grid, Group, Header, Item and Label
  packages/styles/src/form-group.scss
  packages/styles/src/form-header.scss
  packages/styles/src/form-label.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/stories/Components/Forms/checkbox/checkbox.stories.js
  packages/styles/stories/Components/Forms/form-fieldset/form-fieldset.stories.js
  packages/styles/stories/Components/Forms/form-grid/form-grid.stories.js
  packages/styles/stories/Components/Forms/form-group/form-group.stories.js
  packages/styles/stories/Components/Forms/form-group/group-header-in-form-grid.example.html
  packages/styles/stories/Components/Forms/form-group/group-header.example.html
  packages/styles/stories/Components/Forms/form-header/form-header.stories.js
  packages/styles/stories/Components/Forms/form-header/primary.example.html
  packages/styles/stories/Components/Forms/form-item/form-item.stories.js
  packages/styles/stories/Components/Forms/form-item/primary.example.html
  packages/styles/stories/Components/Forms/form-item/required.example.html
  packages/styles/stories/Components/Forms/form-label/colon.example.html
  packages/styles/stories/Components/Forms/form-label/disabled.example.html
  packages/styles/stories/Components/Forms/form-label/form-label.stories.js
  packages/styles/stories/Components/Forms/form-label/primary.example.html
  packages/styles/stories/Components/Forms/form-label/required.example.html
  packages/styles/stories/Components/avatar-group/individual-type-vertical.example.html
  packages/styles/stories/Components/quick-view/popover.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11Y

#6099 fix(styles): add a11y improvements for Input control [ci visual]
  packages/styles/src/input.scss
  packages/styles/stories/Components/Forms/input/input.stories.js
  packages/styles/stories/Components/Forms/input/primary.example.html
  packages/styles/stories/Components/Forms/input/states.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11Y

#6102 fix(styles): add a11y updates for textarea [ci visual]
  packages/styles/src/textarea.scss
  packages/styles/stories/Components/Forms/textarea/counter.example.html
  packages/styles/stories/Components/Forms/textarea/disabled-and-read-only.example.html
  packages/styles/stories/Components/Forms/textarea/primary.example.html
  packages/styles/stories/Components/Forms/textarea/states.example.html
  packages/styles/stories/Components/Forms/textarea/textarea.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11Y
