Repository SAP/fundamental-styles, pull requests merged in 2025-03, with the labels that each got.

#5964 fix(common-css): migrate sass import [ci visual]
  packages/common-css/src/_common-mixins.scss
  packages/common-css/src/_common-settings.scss
  packages/common-css/src/common-css.scss
  packages/common-css/src/sap-border-radius.scss
  packages/common-css/src/sap-busy-indicator.scss
  packages/common-css/src/sap-colors.scss
  packages/common-css/src/sap-container-type.scss
  packages/common-css/src/sap-content-paddings.scss
  packages/common-css/src/sap-display.scss
  packages/common-css/src/sap-elevation.scss
  packages/common-css/src/sap-flex.scss
  packages/common-css/src/sap-heading.scss
  packages/common-css/src/sap-label.scss
  packages/common-css/src/sap-margin.scss
  packages/common-css/src/sap-overflow.scss
  packages/common-css/src/sap-padding.scss
  packages/common-css/src/sap-position.scss
  packages/common-css/src/sap-shadow.scss
  packages/common-css/src/sap-sr-only.scss
  packages/common-css/src/sap-text.scss
  packages/common-css/src/sap-title.scss
  packages/common-css/src/sap-tool-layout.scss
  packages/common-css/src/sap-typography.scss
  packages/styles/src/fundamental-styles.scss
  packages/workspace-plugins/src/executors/sync-components/index.ts
  yarn.lock
Labels: tooling, common-css

#5990 fix(styles): updates related to User Menu implementation [ci visual]
  packages/styles/src/mixins/list/_list-subline.scss
  packages/styles/src/panel.scss
  packages/styles/src/user-menu.scss
  packages/styles/stories/Components/user-menu/default.example.html
  packages/styles/stories/Components/user-menu/mobile.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: UXC Updates

#5989 chore(deps): storybook v.8.6.3 [ci visual]
  .storybook/main.ts
  package.json
  yarn.lock
Labels: tooling, storybook

#5991 chore(deps): bump deps [ci visual]
  .github/actions/nodejs/action.yml
  netlify.toml
  package.json
  packages/cx/src/fundamental-cx.scss
  yarn.lock
Labels: Dependencies

#5992 docs: bump docs
  packages/configuration/src/lib/previous-versions.ts
Labels: documentation

#5995 fix(styles): restyle CX side nav [ci visual]
  packages/cx/src/_nested-list.scss
  packages/cx/src/side-nav.scss
  packages/cx/stories/Components/cx-side-navigation/cosy-narrow.example.html
  packages/cx/stories/Components/cx-side-navigation/wrapping-long-text.example.html
Labels: UXC Updates

#5999 fix(styles): remove again the hover in Side Nav narrow state [ci visual]
  packages/cx/src/side-nav.scss
Labels: UXC Updates

#6001 chore(ci): ci cleanup [ci visual]
  .github/actions/nodejs/action.yml
  .github/workflows/create-release.yml
  .github/workflows/on-pull.yml
  package.json
  yarn.lock
Labels: Dependencies, tooling

#6003 fix(styles): show outline on focus for input group [ci visual]
  packages/styles/src/input-group.scss
  packages/styles/src/mixins/_forms.scss
Labels: Enhancement

#6007 fix(styles): bring CSS for byline list from fund-ngx
  packages/styles/src/mixins/list/_list-base.scss
  packages/styles/src/mixins/list/_list-byline.scss
  packages/styles/stories/Components/List/list/byline/byline-list.stories.js
  packages/styles/stories/Components/List/list/byline/group-header.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: Enhancement

#6006 fix(styles): style properly the title of facets [ci visual]
  packages/styles/src/facet.scss
Labels: Bug

#6008 chore(deps): theming-base-content 11.28.2 [ci visual]
  package.json
  packages/styles/src/icons/_settingsTNT.scss
  packages/styles/stories/Components/Icons/icon/TNTIcons/dataTNT.json
  packages/styles/tests/__snapshots__/styles.test.ts.snap
  yarn.lock
Labels: Dependencies, Theming

#6009 chore(deps): update storybook and nx
  package.json
  yarn.lock
Labels: Dependencies
