Repository SAP/fundamental-styles, pull requests merged in 2025-07, with the labels that each got.

#6113 fix(styles): a11y updates for Input Group [ci visual]
  packages/styles/src/input-group.scss
  packages/styles/stories/Components/Forms/input-group/focus.example.html
  packages/styles/stories/Components/Forms/input-group/input-group.stories.js
  packages/styles/stories/Components/Forms/input-group/input-with-actions.example.html
  packages/styles/stories/Components/Forms/input-group/input-with-icons.example.html
  packages/styles/stories/Components/Forms/input-group/sizes.example.html
  packages/styles/stories/Components/Forms/input-group/states.example.html
  packages/styles/stories/Components/Forms/input-group/test-five.example.html
  packages/styles/stories/Components/Forms/input-group/test-four.example.html
  packages/styles/stories/Components/Forms/input-group/test-one.example.html
  packages/styles/stories/Components/Forms/input-group/test-six.example.html
  packages/styles/stories/Components/Forms/input-group/test-three.example.html
  packages/styles/stories/Components/Forms/input-group/test-two.example.html
  packages/styles/stories/Components/Forms/input-group/text-add-on.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11Y

#6119 chore(ci): storybook 9.0.17
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  packages/common-css/package.json
  packages/common-css/stories/introduction.stories.ts
  packages/cx/package.json
  packages/cx/stories/introduction.stories.ts
  packages/doc-ui/src/components/DocsPage/DocsPage.tsx
  packages/doc-ui/src/components/SAPContainer.tsx
  packages/doc-ui/src/contexts/SAPContext.ts
  packages/styles/package.json
  packages/styles/stories/introduction.stories.ts
  packages/workspace-plugins/src/generators/create-package/files/package-info/stories/introduction.stories.tsx.template
  stories/docs/compact-docs.stories.ts
  stories/docs/introduction.stories.ts
  yarn.lock
Labels: Dependencies

#6120 chore(deps): update nx v.21.3.0
  package.json
  yarn.lock
Labels: Dependencies

#6124 fix(common-css): optimizations for common-css flex [ci visual]
  packages/common-css/src/sap-flex.scss
  packages/common-css/stories/flex/flex.stories.js
Labels: common-css

#6134 fix(styles): update Panel spacings to accommodate Title focus
  packages/styles/src/panel.scss
  packages/styles/stories/Components/panel/panel.stories.js
  packages/styles/stories/Components/panel/transparent.example.html
Labels: enhancement

#6133 fix(common-css): doc examples fixes[ci visual]
  packages/common-css/src/_common-mixins.scss
  packages/common-css/stories/border-radius/border-radius.example.html
  packages/common-css/stories/busy-indicator/busy-indicator.stories.js
  packages/common-css/stories/colors/all-colors/all-background-color.example.html
  packages/common-css/stories/colors/all-colors/all-colors.stories.js
  packages/common-css/stories/colors/main-colors/main-background-color.example.html
  packages/common-css/stories/colors/main-colors/main-colors.stories.js
  packages/common-css/stories/display/display.stories.js
  packages/common-css/stories/focus/focus.stories.js
  packages/common-css/stories/margin/margin.stories.js
  packages/common-css/stories/padding/padding.stories.js
  packages/common-css/stories/page-title/title.stories.js
  packages/common-css/stories/position/position-classes.example.html
  packages/common-css/stories/position/position-mixins.example.html
  packages/common-css/stories/text/text.stories.js
  packages/common-css/stories/typography/common-cases.example.html
  packages/common-css/stories/typography/typography.stories.js
Labels: common-css

#6135 chore(deps): update storybook 9.10
  package.json
  yarn.lock
Labels: Dependencies
