Repository SAP/fundamental-styles, pull requests merged in 2025-08, with the labels that each got.

#6140 fix(styles): update Illustrated messages examples for a11y [ci visual]
  packages/styles/stories/Components/illustrated-message/illustrated-message.stories.js
  packages/styles/stories/Components/illustrated-message/medium.example.html
  packages/styles/stories/Components/illustrated-message/small.example.html
  packages/styles/stories/Components/illustrated-message/xsmall.example.html
Labels: A11Y

#6147 feat(common-css): add additional features to Border [ci visual]
  packages/common-css/src/_common-mixins.scss
  packages/common-css/src/_common-variables.scss
  packages/common-css/src/common-css.scss
  packages/common-css/src/sap-border.scss
  packages/common-css/stories/border/border-mixin.example.html
  packages/common-css/stories/border/border.example.html
  packages/common-css/stories/border/border.stories.js
Labels: common-css

#6158 chore(deps): theming-base-content 11.32.1 [ci visual]
  package.json
  yarn.lock
Labels: Dependencies, Theming

#6159 chore(deps): storybook 9.1.3 [ci visual]
  package.json
  yarn.lock
Labels: Dependencies
