Repository SAP/fundamental-styles, pull requests merged in 2025-04, with the labels that each got.

#6021 chore(deps): theming-base-content 11.29.0 [ci visual]
  package.json
  yarn.lock
Labels: Dependencies, Theming

#6022 chore(deps): storybook v. 8.6.12
  package.json
  yarn.lock
Labels: storybook

#6023 chore(deps): nx v. 20.7.2
  package.json
  yarn.lock
Labels: Dependencies

#6024 fix(styles): remove z-index from readonly input [ci visual]
  packages/styles/src/mixins/_forms.scss
Labels: Bug

#6025 fix(styles): design and a11y updates for Bar [ci visual]
  packages/styles/src/bar.scss
  packages/styles/stories/Components/bar/bar.stories.js
  packages/styles/stories/Components/bar/default.example.html
  packages/styles/stories/Components/bar/floating-footer.example.html
  packages/styles/stories/Components/bar/footer.example.html
  packages/styles/stories/Components/bar/header-with-subheader.example.html
  packages/styles/stories/Components/bar/header.example.html
  packages/styles/stories/Components/bar/responsive.example.html
  packages/styles/stories/Components/bar/subheader.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11y, design changes

#6026 fix(styles): add design and a11y updates for Breadcrumb [ci visual]
  packages/styles/src/breadcrumb.scss
  packages/styles/stories/Components/breadcrumb/current-item.example.html
  packages/styles/stories/Components/breadcrumb/overflow.example.html
  packages/styles/stories/Components/breadcrumb/standard.example.html
  packages/styles/stories/Components/breadcrumb/styles.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11y, design changes

#6028 fix(styles): update Action Sheet [ci visual]
  packages/styles/src/action-sheet.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/stories/Components/action-sheet/action-sheet-mobile.example.html
  packages/styles/stories/Components/action-sheet/action-sheet.stories.js
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: design changes

#6027 fix(styles): deaign and a11y updates for Busy Indicator [ci visual]
  packages/styles/src/busy-indicator.scss
  packages/styles/stories/Components/busy-indicator/busy-dialog.example.html
  packages/styles/stories/Components/busy-indicator/contrast-mode.example.html
  packages/styles/stories/Components/busy-indicator/extended-busy-indicator-inside-message-toast.example.html
  packages/styles/stories/Components/busy-indicator/extended-busy-indicator.example.html
  packages/styles/stories/Components/busy-indicator/standard.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11y, design changes

#6029 fix(styles): add design and a11y updates for Button controls [ci visual]
  packages/styles/src/button.scss
  packages/styles/src/mixins/button/_button-types.scss
  packages/styles/stories/Components/button-split/split-menu-button.example.html
  packages/styles/stories/Components/button/badge-on-button.example.html
  packages/styles/stories/Components/button/button-states.example.html
  packages/styles/stories/Components/button/button.stories.js
  packages/styles/stories/Components/button/focusable-disabled.example.html
  packages/styles/stories/Components/button/icon-and-text.example.html
  packages/styles/stories/Components/button/menu-button.example.html
  packages/styles/stories/Components/button/styles.example.html
  packages/styles/stories/Components/button/toggle.example.html
  packages/styles/stories/Components/segmented-button/segmented-button-vertical.example.html
  packages/styles/stories/Components/segmented-button/segmented-button.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11y, design changes

#6033 fix(styles): a11y and design updates for Carousel [ci visual]
  packages/styles/src/carousel.scss
  packages/styles/src/message-page.scss
  packages/styles/stories/Components/carousel/carousel-backgrounds.example.html
  packages/styles/stories/Components/carousel/carousel-bottom.example.html
  packages/styles/stories/Components/carousel/carousel-no-navigation.example.html
  packages/styles/stories/Components/carousel/carousel-top.example.html
  packages/styles/stories/Components/carousel/carousel.stories.js
  packages/styles/stories/Components/carousel/error.example.html
  packages/styles/stories/Components/carousel/horizontal-carousel.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11y, design changes

#6038 fix(styles): a11y update for Message box [ci visual]
  packages/styles/stories/Components/message-box/message-box.stories.js
  packages/styles/stories/Components/message-box/responsive.example.html
  packages/styles/stories/Components/message-box/structure.example.html
  packages/styles/stories/Components/message-box/types.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11y

#6036 fix(styles): dialog design and a11y updates [ci visual]
  packages/styles/src/_dialog-placeholders.scss
  packages/styles/src/dialog.scss
  packages/styles/src/theming/sap_fiori_3.scss
  packages/styles/src/theming/sap_fiori_3_dark.scss
  packages/styles/src/theming/sap_fiori_3_hcb.scss
  packages/styles/src/theming/sap_fiori_3_hcw.scss
  packages/styles/src/theming/sap_fiori_3_light_dark.scss
  packages/styles/src/theming/sap_horizon.scss
  packages/styles/src/theming/sap_horizon_dark.scss
  packages/styles/src/theming/sap_horizon_hcb.scss
  packages/styles/src/theming/sap_horizon_hcw.scss
  packages/styles/stories/Components/dialog/default-dialog.example.html
  packages/styles/stories/Components/dialog/device-specifications.example.html
  packages/styles/stories/Components/dialog/draggable.example.html
  packages/styles/stories/Components/dialog/horizontal-form-in-dialog.example.html
  packages/styles/stories/Components/dialog/loading.example.html
  packages/styles/stories/Components/dialog/resizable.example.html
  packages/styles/stories/Components/dialog/selectable.example.html
  packages/styles/stories/Components/dialog/sizes.example.html
  packages/styles/stories/Components/dialog/vertical-form-in-dialog.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11y, design changes

#6035 fix(styles): adopt fonts from theming-base
  .storybook/preview-head.html
  README.md
  package.json
  packages/doc-ui/src/components/DocsPage/custom.scss
  packages/styles/README.md
  packages/styles/src/fonts/sap_fiori_3_fonts.scss
  packages/styles/src/fonts/sap_fonts.scss
  packages/styles/src/fonts/sap_horizon_fonts.scss
  packages/styles/src/mixins/_icons.scss
  packages/styles/src/theming/sap_fiori_3_set.scss
  packages/styles/src/theming/sap_horizon_set.scss
  packages/theming-preview/src/theme-manager.js
  yarn.lock
Labels: Theming, tooling

#6040 fix(styles): update Feed Input component [ci visual]
  packages/styles/src/button.scss
  packages/styles/src/feed-input.scss
  packages/styles/src/theming/common/button/_sap_fiori.scss
  packages/styles/src/theming/common/button/_sap_fiori_hc.scss
  packages/styles/src/theming/common/button/_sap_horizon.scss
  packages/styles/src/theming/common/button/_sap_horizon_hc.scss
  packages/styles/stories/Components/feed-input/disabled.example.html
  packages/styles/stories/Components/feed-input/input-growth.example.html
  packages/styles/stories/Components/feed-input/not-empty.example.html
  packages/styles/stories/Components/feed-input/over-max-height.example.html
  packages/styles/stories/Components/feed-input/placeholder-image.example.html
  packages/styles/stories/Components/feed-input/standard.example.html
  packages/styles/stories/Components/feed-input/without-user-image.example.html
  packages/styles/tests/__snapshots__/styles.test.ts.snap
Labels: A11y, design changes
